# Auto-generated by Aspose MCP Builder — do not edit manually.
# Product: Aspose.CAD for Python via .NET  Package: aspose-cad
from __future__ import annotations

import logging
import tempfile
from pathlib import Path

from mcp_server.plugin import AsposePlugin
from mcp_server.path_utils import get_safe_path, temp_output_path, apply_license_for, platform_hint

logger = logging.getLogger(__name__)


class CadPlugin(AsposePlugin):
    product_name = "cad"
    pypi_package = "aspose-cad"
    min_version = "24.1.0"

    def health_check(self) -> bool:
        """Check that the Aspose CAD package is importable.

        Args:
            None

        Returns:
            True if the package imports without error, False otherwise.

        Raises:
            None. Import errors are caught and return False.

        Example:
            >>> plugin = CadPlugin()
            >>> isinstance(plugin.health_check(), bool)
            True
        """
        try:
            import aspose.cad as cad  # noqa: F401, PLC0415
            return True
        except Exception:
            return False

    def get_tool_manifest(self) -> list[dict[str, object]]:
        """Return metadata for all registered tools.

        Args:
            None

        Returns:
            List of dicts each with keys: name, description, params, returns.

        Raises:
            None.

        Example:
            >>> plugin = CadPlugin()
            >>> manifest = plugin.get_tool_manifest()
            >>> len(manifest) >= 15
            True
        """
        return [
            {"name": 'cad_list_files', "description": 'Lists files in the ASPOSE_FILES_PATH directory, optionally filtering by file extension.', "params": [{"name": 'extension_filter', "type": 'str | None', "required": False, "description": ""}], "returns": "dict"},
            {"name": 'cad_convert_to_pdf', "description": 'Converts a CAD file to PDF using specified page dimensions.', "params": [{"name": 'input_filename', "type": 'str', "required": True, "description": ""}, {"name": 'output_filename', "type": 'str | None', "required": False, "description": ""}, {"name": 'page_width', "type": 'float | None', "required": False, "description": ""}, {"name": 'page_height', "type": 'float | None', "required": False, "description": ""}], "returns": "dict"},
            {"name": 'cad_convert_to_png', "description": 'Converts a CAD file to PNG using optional page dimensions.', "params": [{"name": 'input_filename', "type": 'str', "required": True, "description": ""}, {"name": 'output_filename', "type": 'str | None', "required": False, "description": ""}, {"name": 'page_width', "type": 'float | None', "required": False, "description": ""}, {"name": 'page_height', "type": 'float | None', "required": False, "description": ""}], "returns": "dict"},
            {"name": 'cad_convert_to_jpeg', "description": 'Converts a CAD file to JPEG using optional page dimensions.', "params": [{"name": 'input_filename', "type": 'str', "required": True, "description": ""}, {"name": 'output_filename', "type": 'str | None', "required": False, "description": ""}, {"name": 'page_width', "type": 'float | None', "required": False, "description": ""}, {"name": 'page_height', "type": 'float | None', "required": False, "description": ""}], "returns": "dict"},
            {"name": 'cad_convert_to_bmp', "description": 'Converts a CAD file to BMP.', "params": [{"name": 'input_filename', "type": 'str', "required": True, "description": ""}, {"name": 'output_filename', "type": 'str | None', "required": False, "description": ""}], "returns": "dict"},
            {"name": 'cad_convert_to_tiff', "description": 'Converts a CAD file to TIFF.', "params": [{"name": 'input_filename', "type": 'str', "required": True, "description": ""}, {"name": 'output_filename', "type": 'str | None', "required": False, "description": ""}], "returns": "dict"},
            {"name": 'cad_convert_to_svg', "description": 'Converts a CAD file to SVG.', "params": [{"name": 'input_filename', "type": 'str', "required": True, "description": ""}, {"name": 'output_filename', "type": 'str | None', "required": False, "description": ""}], "returns": "dict"},
            {"name": 'cad_convert_to_gif', "description": 'Converts a CAD file to GIF.', "params": [{"name": 'input_filename', "type": 'str', "required": True, "description": ""}, {"name": 'output_filename', "type": 'str | None', "required": False, "description": ""}], "returns": "dict"},
            {"name": 'cad_get_drawing_info', "description": 'Retrieves basic information about a CAD drawing such as width, height and image type.', "params": [{"name": 'input_filename', "type": 'str', "required": True, "description": ""}], "returns": "dict"},
            {"name": 'cad_export_layer_to_pdf', "description": 'Exports specified layers of a CAD file to a PDF document.', "params": [{"name": 'input_filename', "type": 'str', "required": True, "description": ""}, {"name": 'layer_names', "type": 'list[str]', "required": True, "description": ""}, {"name": 'output_filename', "type": 'str | None', "required": False, "description": ""}], "returns": "dict"},
            {"name": 'cad_export_layout_to_pdf', "description": 'Exports specified layouts of a CAD file to a PDF document.', "params": [{"name": 'input_filename', "type": 'str', "required": True, "description": ""}, {"name": 'layout_names', "type": 'list[str]', "required": True, "description": ""}, {"name": 'output_filename', "type": 'str | None', "required": False, "description": ""}], "returns": "dict"},
            {"name": 'cad_export_layer_to_png', "description": 'Exports specified layers of a CAD file to a PNG image.', "params": [{"name": 'input_filename', "type": 'str', "required": True, "description": ""}, {"name": 'layer_names', "type": 'list[str]', "required": True, "description": ""}, {"name": 'output_filename', "type": 'str | None', "required": False, "description": ""}], "returns": "dict"}
        ]

    def register_tools(self, mcp: "FastMCP") -> None:
        """Register all CAD tools with the FastMCP instance.

        Args:
            mcp: FastMCP server instance to register tools on.

        Returns:
            None.

        Raises:
            None.

        Example:
            >>> from mcp.server.fastmcp import FastMCP
            >>> mcp = FastMCP("test")
            >>> CadPlugin().register_tools(mcp)
        """
        logger.debug("%s plugin registering tools. Platform: %s", "CAD", platform_hint())
        apply_license_for("aspose.cad")
        @mcp.tool()
        async def cad_list_files(extension_filter: str | None = None) -> dict:
            """List files already present in the server's ASPOSE_FILES_PATH folder. Call this first to discover available files — do NOT ask the user to upload.
        
            IMPORTANT: All *_filename parameters accept ONLY the bare filename (e.g. 'scan.jpg') — no path, no directory, no drive letter, no slash.
            The file MUST already exist in the server's ASPOSE_FILES_PATH folder before calling this tool.
            Do NOT ask the user to upload a file — files are pre-placed in the server folder by the user.
            The output file is also written to the ASPOSE_FILES_PATH folder; the returned output_filename is the bare name only.
        
            Args:
                extension_filter: Optional file extension to filter by, e.g. 'jpg'. None lists all files.
        
            Returns:
                dict: {"status": "success"|"error", "files": list[str], "folder_path": str, "message": str}
        
            Raises:
                None. Errors are returned as {"status": "error", "message": str}.
        
            Example:
                result = await cad_list_files("jpg")
                # result["files"] contains bare filenames matching the extension
            """
            from pathlib import Path
            from mcp_server.path_utils import get_safe_path
            import logging
            logger = logging.getLogger(__name__)
            resolved_folder = get_safe_path("")
            if not Path(resolved_folder).is_dir():
                return {"status": "error", "message": "ASPOSE_FILES_PATH folder not found."}
            try:
                files: list[str] = []
                for entry in Path(resolved_folder).iterdir():
                    if not entry.is_file():
                        continue
                    if extension_filter and entry.suffix.lower() != f".{extension_filter.lower().lstrip('.')}":
                        continue
                    files.append(entry.name)
                return {"status": "success", "message": f"Listed {len(files)} file(s).", "files": sorted(files), "folder_path": resolved_folder}
            except Exception as exc:
                logger.exception("Error listing files.")
                return {"status": "error", "message": str(exc)}

        @mcp.tool()
        async def cad_convert_to_pdf(
            input_filename: str,
            output_filename: str | None = None,
            page_width: float | None = None,
            page_height: float | None = None,
        ) -> dict:
            """
            Convert a CAD file stored on the server to a PDF document.
        
            IMPORTANT: All *_filename parameters accept ONLY the bare filename (e.g. 'scan.dwg') —
            no path, no directory, no drive letter, no slash.
            The file MUST already exist in the server's ASPOSE_FILES_PATH folder.
            Do NOT ask the user to upload a file — files are pre‑placed in that folder.
            Output files are written to the same folder; returned output_filename is the bare name only.
        
            Args:
                input_filename: Bare filename of the CAD file to convert, located in ASPOSE_FILES_PATH.
                output_filename: Desired PDF filename (bare name only). If omitted, a temporary name is generated.
                page_width: Page width for rasterization; defaults to 1200.0 if None.
                page_height: Page height for rasterization; defaults to 1200.0 if None.
        
            Returns:
                dict: {
                    "status": "success" | "error",
                    "message": str,
                    "output_filename": str   # bare name of the created PDF
                }
        
            Raises:
                FileNotFoundError: If the input CAD file does not exist.
                Exception: Propagates any unexpected errors from the Aspose library.
        
            Example:
                result = await cad_convert_to_pdf(
                    input_filename="drawing.dwg",
                    output_filename="drawing.pdf",
                    page_width=1600.0,
                    page_height=1200.0,
                )
            """
            # ----------------------------------------------------------------------
            # Resolve and validate input file
            # ----------------------------------------------------------------------
            from pathlib import Path
            from mcp_server.path_utils import get_safe_path, temp_output_path
            import logging
        
            logger = logging.getLogger(__name__)
        
            # sanitize input filename
            input_filename = Path(input_filename.strip().replace('\x00', '')).name
            resolved_input = get_safe_path(input_filename)
            if not Path(resolved_input).is_file():
                raise FileNotFoundError(f"File not found: {input_filename}")
        
            # ----------------------------------------------------------------------
            # Resolve output file (optional)
            # ----------------------------------------------------------------------
            if output_filename is not None:
                output_filename = Path(output_filename.strip().replace('\x00', '')).name
                resolved_output = get_safe_path(output_filename)
            else:
                # generate a temporary filename with .pdf extension
                temp_path = temp_output_path("cad_result", ".pdf")
                resolved_output = str(temp_path)  # Aspose expects a plain string
                output_filename = Path(resolved_output).name
        
            # ensure output directory exists
            Path(resolved_output).parent.mkdir(parents=True, exist_ok=True)
        
            try:
                # ------------------------------------------------------------------
                # Lazy import of Aspose.CAD
                # ------------------------------------------------------------------
                import aspose.cad as cad
                from aspose.cad.imageoptions import CadRasterizationOptions, PdfOptions
        
                # load CAD image (no context manager)
                img = cad.Image.load(str(resolved_input))
        
                # configure rasterization options
                raster_opts = CadRasterizationOptions()
                raster_opts.page_width = float(page_width or 1200.0)
                raster_opts.page_height = float(page_height or 1200.0)
        
                # configure PDF options
                pdf_opts = PdfOptions()
                pdf_opts.vector_rasterization_options = raster_opts
        
                # save as PDF
                img.save(str(resolved_output), pdf_opts)
        
                logger.info(
                    "CAD conversion succeeded: %s -> %s (width=%s, height=%s)",
                    input_filename,
                    output_filename,
                    raster_opts.page_width,
                    raster_opts.page_height,
                )
                return {
                    "status": "success",
                    "message": "Conversion completed successfully.",
                    "output_filename": output_filename,
                }
        
            except Exception as exc:  # pragma: no cover
                logger.exception("CAD conversion failed for %s", input_filename)
                return {
                    "status": "error",
                    "message": str(exc),
                    "output_filename": output_filename,
                }

        @mcp.tool()
        async def cad_convert_to_png(
            input_filename: str,
            output_filename: str | None = None,
            page_width: float | None = None,
            page_height: float | None = None,
        ) -> dict:
            """
            Convert a CAD file already stored on the server to a PNG image.
        
            IMPORTANT: All *_filename parameters accept ONLY the bare filename (e.g. 'drawing.dwg') — no path, no directory, no drive letter, no slash.
            The file MUST already exist in the server's ASPOSE_FILES_PATH folder.
            Do NOT ask the user to upload a file — files are pre-placed in that folder.
            Output files are written to the same folder; returned output_filename is the bare name only.
        
            Args:
                input_filename (str): Bare filename of the CAD file in ASPOSE_FILES_PATH.
                output_filename (str | None, optional): Desired PNG filename; if omitted a temporary name is generated.
                page_width (float | None, optional): Page width for rasterization; defaults to 1200.0.
                page_height (float | None, optional): Page height for rasterization; defaults to 1200.0.
        
            Returns:
                dict: {"status": "success"|"error", "message": str, "output_filename": str}
        
            Raises:
                FileNotFoundError: If the input CAD file does not exist.
                Exception: Any error raised by Aspose during conversion.
        
            Example:
                >>> result = await cad_convert_to_png("plan.dwg", "plan.png", 1600, 1200)
            """
            # ----------------------------------------------------------------------
            # Resolve and validate input file
            # ----------------------------------------------------------------------
            from pathlib import Path
            from mcp_server.path_utils import get_safe_path, temp_output_path
            import logging
        
            logger = logging.getLogger(__name__)
        
            # sanitize input filename (strip null bytes, keep only name)
            input_filename = Path(input_filename.strip().replace("\x00", "")).name
            resolved_input = get_safe_path(input_filename)
            if not Path(resolved_input).is_file():
                raise FileNotFoundError(f"File not found: {input_filename}")
        
            # ----------------------------------------------------------------------
            # Resolve output path (temporary if not supplied)
            # ----------------------------------------------------------------------
            if output_filename is not None:
                output_filename = Path(output_filename.strip().replace("\x00", "")).name
                resolved_output = get_safe_path(output_filename)
            else:
                # generate a temporary filename with .png suffix
                resolved_output = str(temp_output_path("cad_result", ".png"))
                output_filename = Path(resolved_output).name
        
            # ensure output directory exists
            Path(resolved_output).parent.mkdir(parents=True, exist_ok=True)
        
            # ----------------------------------------------------------------------
            # Perform conversion using Aspose.CAD
            # ----------------------------------------------------------------------
            try:
                import aspose.cad as cad
                from aspose.cad.imageoptions import CadRasterizationOptions, PngOptions
        
                raster_opts = CadRasterizationOptions()
                raster_opts.page_width = float(page_width or 1200.0)
                raster_opts.page_height = float(page_height or 1200.0)
        
                png_opts = PngOptions()
                png_opts.vector_rasterization_options = raster_opts
        
                img = cad.Image.load(str(resolved_input))
                img.save(str(resolved_output), png_opts)
        
                logger.info("CAD file %s converted to PNG %s", input_filename, output_filename)
                return {
                    "status": "success",
                    "message": "Conversion completed successfully.",
                    "output_filename": output_filename,
                }
        
            except Exception as exc:  # pragma: no cover
                logger.exception("Error converting CAD to PNG: %s", exc)
                return {"status": "error", "message": str(exc), "output_filename": output_filename}

        @mcp.tool()
        async def cad_convert_to_jpeg(
            input_filename: str,
            output_filename: str | None = None,
            page_width: float | None = None,
            page_height: float | None = None,
        ) -> dict:
            """
            Convert a CAD file stored on the server to a JPEG image.
        
            IMPORTANT: All *_filename parameters accept ONLY the bare filename (e.g. 'scan.jpg') —
            no path, no directory, no drive letter, no slash. The file MUST already exist in the
            server's ASPOSE_FILES_PATH folder. Do NOT ask the user to upload a file — files are
            pre‑placed in that folder. Output files are written to the same folder; returned
            output_filename is the bare name only.
        
            Args:
                input_filename: Bare filename of the CAD file placed in ASPOSE_FILES_PATH.
                output_filename: Desired JPEG filename (bare name only). If omitted, a temporary name is generated.
                page_width: Page width for rasterization; defaults to 1200.0 if None.
                page_height: Page height for rasterization; defaults to 1200.0 if None.
        
            Returns:
                dict: {
                    "status": "success" | "error",
                    "message": str,
                    "output_filename": str   # bare name of the written JPEG file
                }
        
            Raises:
                FileNotFoundError: If the input CAD file does not exist.
                Exception: For any unexpected error during conversion.
        
            Example:
                result = await cad_convert_to_jpeg(
                    input_filename="drawing.dwg",
                    output_filename="drawing.jpg",
                    page_width=1600.0,
                    page_height=1200.0,
                )
            """
            # ---------- Resolve and validate input ----------
            from pathlib import Path
            from mcp_server.path_utils import get_safe_path, temp_output_path
            import logging
        
            logger = logging.getLogger(__name__)
        
            # sanitize input filename
            input_filename = Path(input_filename.strip().replace("\x00", "")).name
            resolved_input = get_safe_path(input_filename)
            if not Path(resolved_input).is_file():
                raise FileNotFoundError(f"File not found: {input_filename}")
        
            # ---------- Resolve output ----------
            if output_filename is not None:
                output_filename = Path(output_filename.strip().replace("\x00", "")).name
                resolved_output = get_safe_path(output_filename)
            else:
                # generate a temporary filename with .jpeg extension
                temp_path = temp_output_path("cad_result", ".jpeg")
                resolved_output = str(temp_path)  # Aspose expects a plain str
                output_filename = Path(resolved_output).name
        
            # ensure output directory exists
            Path(resolved_output).parent.mkdir(parents=True, exist_ok=True)
        
            # ---------- Perform conversion ----------
            try:
                import aspose.cad as cad
                from aspose.cad.imageoptions import CadRasterizationOptions, JpegOptions
        
                raster_opts = CadRasterizationOptions()
                raster_opts.page_width = float(page_width if page_width is not None else 1200.0)
                raster_opts.page_height = float(page_height if page_height is not None else 1200.0)
        
                jpeg_opts = JpegOptions()
                jpeg_opts.vector_rasterization_options = raster_opts
        
                img = cad.Image.load(str(resolved_input))
                img.save(str(resolved_output), jpeg_opts)
        
                logger.info(
                    "CAD file %s converted to JPEG %s (width=%s, height=%s)",
                    input_filename,
                    output_filename,
                    raster_opts.page_width,
                    raster_opts.page_height,
                )
                return {
                    "status": "success",
                    "message": f"Converted {input_filename} to {output_filename}",
                    "output_filename": output_filename,
                }
            except Exception as exc:  # pragma: no cover
                logger.exception("Error converting CAD to JPEG: %s", exc)
                return {
                    "status": "error",
                    "message": str(exc),
                    "output_filename": output_filename,
                }

        @mcp.tool()
        async def cad_convert_to_bmp(
            input_filename: str,
            output_filename: str | None = None,
        ) -> dict:
            """
            Convert a CAD file to BMP format.
        
            IMPORTANT: All *_filename parameters accept ONLY the bare filename (e.g. 'scan.jpg') —
            no path, no directory, no drive letter, no slash.
            The file MUST already exist in the server's ASPOSE_FILES_PATH folder.
            Do NOT ask the user to upload a file — files are pre‑placed in that folder.
            Output files are written to the same folder; returned output_filename is the bare name only.
        
            Args:
                input_filename: Bare filename of the CAD file placed in ASPOSE_FILES_PATH.
                output_filename: Desired BMP filename (bare name only). If omitted, a temporary name is generated.
        
            Returns:
                dict: {
                    "status": "success" | "error",
                    "message": str,
                    "output_filename": str   # bare name of the written BMP file
                }
        
            Raises:
                FileNotFoundError: If the input CAD file does not exist.
        
            Example:
                result = await cad_convert_to_bmp("drawing.dwg", "drawing.bmp")
                # result["output_filename"] == "drawing.bmp"
            """
            # -------------------------------------------------------------------------
            # Resolve and validate input / output filenames (must happen before any Aspose import)
            # -------------------------------------------------------------------------
            from pathlib import Path
            from mcp_server.path_utils import get_safe_path, temp_output_path
            import logging
        
            # sanitize input filename
            input_filename = Path(input_filename.strip().replace("\x00", "")).name
            resolved_input = get_safe_path(input_filename)
            if not Path(resolved_input).is_file():
                raise FileNotFoundError(f"File not found: {input_filename}")
        
            # sanitize / resolve output filename
            if output_filename is not None:
                output_filename = Path(output_filename.strip().replace("\x00", "")).name
                resolved_output = get_safe_path(output_filename)
            else:
                resolved_output = str(temp_output_path("cad_result", ".bmp"))
                output_filename = Path(resolved_output).name
        
            # ensure output directory exists
            Path(resolved_output).parent.mkdir(parents=True, exist_ok=True)
        
            logger = logging.getLogger(__name__)
        
            # -------------------------------------------------------------------------
            # Aspose CAD conversion
            # -------------------------------------------------------------------------
            try:
                import aspose.cad as cad
                from aspose.cad.imageoptions import CadRasterizationOptions, BmpOptions
        
                raster_opts = CadRasterizationOptions()
                bmp_opts = BmpOptions()
                bmp_opts.vector_rasterization_options = raster_opts
        
                img = cad.Image.load(str(resolved_input))
                img.save(str(resolved_output), bmp_opts)
        
                return {
                    "status": "success",
                    "message": f"Converted {input_filename} to BMP.",
                    "output_filename": output_filename,
                }
            except Exception as exc:  # pragma: no cover
                logger.exception("Error converting CAD to BMP")
                return {"status": "error", "message": str(exc)}

        @mcp.tool()
        async def cad_convert_to_tiff(
            input_filename: str,
            output_filename: str | None = None,
        ) -> dict:
            """Convert a CAD file to a TIFF image.
        
            IMPORTANT: All *_filename parameters accept ONLY the bare filename (e.g. 'scan.jpg') —
            no path, no directory, no drive letter, no slash.
            The file MUST already exist in the server's ASPOSE_FILES_PATH folder.
            Do NOT ask the user to upload a file — files are pre‑placed in that folder.
            Output files are written to the same folder; returned output_filename is the bare name only.
        
            Args:
                input_filename: Bare filename of the CAD file placed in ASPOSE_FILES_PATH.
                output_filename: Optional bare filename for the resulting TIFF. If omitted, a temporary name is generated.
        
            Returns:
                dict: {
                    "status": "success" | "error",
                    "message": str,
                    "output_filename": str   # bare name of the written TIFF file
                }
        
            Raises:
                FileNotFoundError: If the input CAD file does not exist.
        
            Example:
                result = await cad_convert_to_tiff("drawing.dwg", "drawing.tiff")
            """
            from pathlib import Path
            from mcp_server.path_utils import get_safe_path, temp_output_path
            import logging
        
            logger = logging.getLogger(__name__)
        
            # ---- validate and resolve input file ----
            input_filename = Path(input_filename.strip().replace("\x00", "")).name
            resolved_input = get_safe_path(input_filename)
            if not Path(resolved_input).is_file():
                raise FileNotFoundError(f"File not found: {input_filename}")
        
            # ---- determine output file ----
            if output_filename is not None:
                output_filename = Path(output_filename.strip().replace("\x00", "")).name
                resolved_output = get_safe_path(output_filename)
            else:
                resolved_output = str(temp_output_path("cad_result", ".tiff"))
                output_filename = Path(resolved_output).name
        
            # ensure the output directory exists
            Path(resolved_output).parent.mkdir(parents=True, exist_ok=True)
        
            try:
                # lazy import of Aspose.CAD
                import aspose.cad as cad
                from aspose.cad.imageoptions import CadRasterizationOptions, TiffOptions
        
                # rasterization options for TIFF
                raster_opts = CadRasterizationOptions()
                tiff_opts = TiffOptions()
                tiff_opts.vector_rasterization_options = raster_opts
        
                # load CAD and save as TIFF
                img = cad.Image.load(str(resolved_input))
                img.save(str(resolved_output), tiff_opts)
        
                return {
                    "status": "success",
                    "message": "Conversion completed.",
                    "output_filename": output_filename,
                }
            except Exception as exc:  # pragma: no cover
                logger.exception("Error converting CAD to TIFF")
                return {
                    "status": "error",
                    "message": str(exc),
                    "output_filename": output_filename,
                }

        @mcp.tool()
        async def cad_convert_to_svg(
            input_filename: str,
            output_filename: str | None = None,
        ) -> dict:
            """
            Convert a CAD file stored on the server to an SVG image.
        
            IMPORTANT: All *_filename parameters accept ONLY the bare filename (e.g. 'scan.jpg') —
            no path, no directory, no drive letter, no slash. The file MUST already exist in the
            server's ASPOSE_FILES_PATH folder. Do NOT ask the user to upload a file — files are
            pre‑placed in that folder. Output files are written to the same folder; returned
            output_filename is the bare name only.
        
            Args:
                input_filename: Bare filename of the CAD file to convert, e.g. "drawing.dwg".
                    Must exist in ASPOSE_FILES_PATH.
                output_filename: Optional bare filename for the resulting SVG. If omitted,
                    a temporary name is generated.
        
            Returns:
                dict: {
                    "status": "success" | "error",
                    "message": str,
                    "output_filename": str   # bare name of the written SVG file
                }
        
            Raises:
                FileNotFoundError: If the input CAD file does not exist.
                Exception: Any unexpected error raised by Aspose.CAD.
        
            Example:
                result = await cad_convert_to_svg("example.dwg", "example.svg")
                # result["output_filename"] -> "example.svg"
            """
            # ----------------------------------------------------------------------
            # Resolve and validate input file
            # ----------------------------------------------------------------------
            from pathlib import Path
            from mcp_server.path_utils import get_safe_path, temp_output_path
            import logging
        
            logger = logging.getLogger(__name__)
        
            # sanitize input filename
            input_filename = Path(input_filename.strip().replace("\x00", "")).name
            resolved_input = get_safe_path(input_filename)
            if not Path(resolved_input).is_file():
                raise FileNotFoundError(f"File not found: {input_filename}")
        
            # ----------------------------------------------------------------------
            # Resolve output location
            # ----------------------------------------------------------------------
            if output_filename is not None:
                output_filename = Path(output_filename.strip().replace("\x00", "")).name
                resolved_output = get_safe_path(output_filename)
            else:
                # temporary file with .svg extension
                resolved_output = str(temp_output_path("cad_result", ".svg"))
                output_filename = Path(resolved_output).name
        
            # ensure output directory exists
            Path(resolved_output).parent.mkdir(parents=True, exist_ok=True)
        
            # ----------------------------------------------------------------------
            # Perform conversion using Aspose.CAD
            # ----------------------------------------------------------------------
            try:
                import aspose.cad as cad
                from aspose.cad.imageoptions import CadRasterizationOptions, SvgOptions
        
                raster_opts = CadRasterizationOptions()
                svg_opts = SvgOptions()
                svg_opts.vector_rasterization_options = raster_opts
        
                cad_image = cad.Image.load(str(resolved_input))
                cad_image.save(str(resolved_output), svg_opts)
        
                logger.info(
                    "Converted CAD file %s to SVG %s",
                    input_filename,
                    output_filename,
                )
                return {
                    "status": "success",
                    "message": f"Converted {input_filename} to SVG successfully.",
                    "output_filename": output_filename,
                }
        
            except Exception as exc:  # pragma: no cover
                logger.exception("Error converting CAD to SVG: %s", exc)
                return {
                    "status": "error",
                    "message": str(exc),
                    "output_filename": output_filename,
                }

        @mcp.tool()
        async def cad_convert_to_gif(
            input_filename: str,
            output_filename: str | None = None,
        ) -> dict:
            """
            Convert a CAD file stored on the server to an animated GIF.
        
            IMPORTANT: All *_filename parameters accept ONLY the bare filename (e.g. 'scan.jpg') — no path, no directory, no drive letter, no slash. The file MUST already exist in the server's ASPOSE_FILES_PATH folder. Do NOT ask the user to upload a file — files are pre‑placed in that folder. Output files are written to the same folder; returned output_filename is the bare name only.
        
            Args:
                input_filename: Bare filename of the CAD file to convert, e.g. "design.dwg". Must already exist in ASPOSE_FILES_PATH.
                output_filename: Optional bare filename for the resulting GIF. If omitted, a temporary name is generated.
        
            Returns:
                dict: {
                    "status": "success" | "error",
                    "message": str,
                    "output_filename": str   # bare name of the created GIF
                }
        
            Raises:
                FileNotFoundError: If the input CAD file does not exist.
                Exception: Any unexpected error from the Aspose.CAD library.
        
            Example:
                result = await cad_convert_to_gif("example.dwg", "example.gif")
                # result["output_filename"] == "example.gif"
            """
            # ----------------------------------------------------------------------
            # Resolve and validate input file
            # ----------------------------------------------------------------------
            from pathlib import Path
            from mcp_server.path_utils import get_safe_path, temp_output_path
            import logging
        
            logger = logging.getLogger(__name__)
        
            # sanitize input filename
            input_filename = Path(input_filename.strip().replace('\x00', '')).name
            resolved_input = get_safe_path(input_filename)
            if not Path(resolved_input).is_file():
                raise FileNotFoundError(f"File not found: {input_filename}")
        
            # ----------------------------------------------------------------------
            # Resolve output location
            # ----------------------------------------------------------------------
            if output_filename is not None:
                output_filename = Path(output_filename.strip().replace('\x00', '')).name
                resolved_output = get_safe_path(output_filename)
            else:
                # generate a temporary filename with .gif extension
                temp_path = temp_output_path("cad_result", ".gif")
                resolved_output = str(temp_path)  # Aspose expects a plain string
                output_filename = Path(resolved_output).name
        
            # ensure output directory exists
            Path(resolved_output).parent.mkdir(parents=True, exist_ok=True)
        
            try:
                # ------------------------------------------------------------------
                # Aspose.CAD conversion
                # ------------------------------------------------------------------
                import aspose.cad as cad
                from aspose.cad.imageoptions import CadRasterizationOptions, GifOptions
        
                raster_opts = CadRasterizationOptions()
                gif_opts = GifOptions()
                gif_opts.vector_rasterization_options = raster_opts
        
                img = cad.Image.load(str(resolved_input))
                img.save(str(resolved_output), gif_opts)
        
                logger.info(
                    "Converted CAD file %s to GIF %s",
                    input_filename,
                    output_filename,
                )
                return {
                    "status": "success",
                    "message": f"File converted successfully: {output_filename}",
                    "output_filename": output_filename,
                }
        
            except Exception as exc:  # pragma: no cover
                logger.exception("Error converting CAD to GIF: %s", exc)
                return {
                    "status": "error",
                    "message": str(exc),
                    "output_filename": output_filename,
                }

        @mcp.tool()
        async def cad_get_drawing_info(input_filename: str) -> dict:
            """
            Retrieve basic drawing information from a CAD file stored on the server.
        
            IMPORTANT:
            - All *_filename parameters accept ONLY the bare filename (e.g. 'scan.dwg') — no path,
              no directory, no drive letter, no slash.
            - The file MUST already exist in the server's ASPOSE_FILES_PATH folder before calling this tool.
            - Do NOT ask the user to upload a file — files are pre‑placed in the server folder by the user.
            - The output file is also written to the ASPOSE_FILES_PATH folder; the returned output_filename
              is the bare name only.
        
            Args:
                input_filename (str): Bare filename of the CAD file placed in ASPOSE_FILES_PATH.
        
            Returns:
                dict: JSON object containing at minimum:
                      {"status": "success"|"error",
                       "message": str,
                       "width": int,
                       "height": int,
                       "image_type": str,
                       "input_filename": str}
        
            Raises:
                FileNotFoundError: If the specified CAD file does not exist.
                Exception: Any unexpected error raised by Aspose.CAD.
        
            Example:
                >>> result = await cad_get_drawing_info("example.dwg")
                >>> result["width"]
            """
            # ----------------------------------------------------------------------
            # Resolve and validate the input filename
            # ----------------------------------------------------------------------
            from pathlib import Path
            from mcp_server.path_utils import get_safe_path, temp_output_path
            import logging
        
            logger = logging.getLogger(__name__)
        
            # Sanitize the caller‑provided filename
            input_filename = Path(input_filename.strip().replace('\x00', '')).name
            resolved_input = get_safe_path(input_filename)
        
            if not Path(resolved_input).is_file():
                raise FileNotFoundError(f"File not found: {input_filename}")
        
            # ----------------------------------------------------------------------
            # Load the CAD file with Aspose and extract information
            # ----------------------------------------------------------------------
            try:
                import aspose.cad as cad
        
                cad_image = cad.Image.load(str(resolved_input))
                size = cad_image.size
        
                result = {
                    "status": "success",
                    "message": "File processed successfully.",
                    "width": size.width,
                    "height": size.height,
                    "image_type": type(cad_image).__name__,
                    "input_filename": input_filename,
                }
                logger.debug(
                    "CAD info retrieved for %s: width=%s, height=%s, type=%s",
                    input_filename,
                    size.width,
                    size.height,
                    type(cad_image).__name__,
                )
                return result
        
            except Exception as exc:  # pragma: no cover
                logger.error("Error processing CAD file %s: %s", input_filename, exc)
                return {"status": "error", "message": str(exc)}

        @mcp.tool()
        async def cad_export_layer_to_pdf(
            input_filename: str,
            layer_names: list[str],
            output_filename: str | None = None,
        ) -> dict:
            """
            Export selected layers of a CAD file to a PDF document.
        
            IMPORTANT: All *_filename parameters accept ONLY the bare filename (e.g. 'drawing.dwg') —
            no path, no directory, no drive letter, no slash.
            The file MUST already exist in the server's ASPOSE_FILES_PATH folder.
            Do NOT ask the user to upload a file — files are pre‑placed in that folder.
            Output files are written to the same folder; returned output_filename is the bare name only.
        
            Args:
                input_filename: Bare filename of the source CAD file placed in ASPOSE_FILES_PATH.
                layer_names: List of layer names to include in the generated PDF.
                output_filename: Desired PDF filename (bare name only). If omitted, a temporary name is generated.
        
            Returns:
                dict: {
                    "status": "success" | "error",
                    "message": str,
                    "output_filename": str   # bare name of the created PDF
                }
        
            Raises:
                FileNotFoundError: If the specified CAD file does not exist.
                Exception: Any unexpected error raised by Aspose.CAD.
        
            Example:
                result = await cad_export_layer_to_pdf(
                    input_filename="plan.dwg",
                    layer_names=["Layer1", "Layer2"],
                    output_filename="selected_layers.pdf"
                )
            """
            # ----------------------------------------------------------------------
            # Resolve and validate input file
            # ----------------------------------------------------------------------
            from pathlib import Path
            from mcp_server.path_utils import get_safe_path, temp_output_path
            import logging
        
            logger = logging.getLogger(__name__)
        
            # sanitize input filename
            input_filename = Path(input_filename.strip().replace('\x00', '')).name
            resolved_input = get_safe_path(input_filename)
            if not Path(resolved_input).is_file():
                raise FileNotFoundError(f"File not found: {input_filename}")
        
            # ----------------------------------------------------------------------
            # Resolve output file
            # ----------------------------------------------------------------------
            if output_filename is not None:
                output_filename = Path(output_filename.strip().replace('\x00', '')).name
                resolved_output = get_safe_path(output_filename)
            else:
                # generate a temporary filename with .pdf extension
                temp_path = temp_output_path("cad_result", ".pdf")
                resolved_output = str(temp_path)  # Aspose expects a plain str
                output_filename = Path(resolved_output).name
        
            # ensure output directory exists
            Path(resolved_output).parent.mkdir(parents=True, exist_ok=True)
        
            # ----------------------------------------------------------------------
            # Aspose.CAD processing
            # ----------------------------------------------------------------------
            try:
                import aspose.cad as cad
                from aspose.cad.imageoptions import CadRasterizationOptions, PdfOptions
        
                # configure rasterization options
                raster_opts = CadRasterizationOptions()
                raster_opts.page_width = 1200.0
                raster_opts.page_height = 1200.0
                raster_opts.layers = layer_names
        
                # configure PDF options
                pdf_opts = PdfOptions()
                pdf_opts.vector_rasterization_options = raster_opts
        
                # load CAD file and save as PDF
                img = cad.Image.load(str(resolved_input))
                img.save(str(resolved_output), pdf_opts)
        
                logger.debug(
                    "CAD layers exported to PDF: %s (layers: %s)",
                    output_filename,
                    ", ".join(layer_names),
                )
                return {
                    "status": "success",
                    "message": "Layers exported to PDF successfully.",
                    "output_filename": output_filename,
                }
        
            except Exception as exc:  # pragma: no cover
                logger.exception("Error exporting CAD layers to PDF")
                return {
                    "status": "error",
                    "message": str(exc),
                    "output_filename": output_filename,
                }

        @mcp.tool()
        async def cad_export_layout_to_pdf(
            input_filename: str,
            layout_names: list[str],
            output_filename: str | None = None,
        ) -> dict:
            """
            Export specified CAD layouts to a single PDF file.
        
            IMPORTANT: All *_filename parameters accept ONLY the bare filename (e.g. 'scan.jpg') —
            no path, no directory, no drive letter, no slash.
            The file MUST already exist in the server's ASPOSE_FILES_PATH folder.
            Do NOT ask the user to upload a file — files are pre‑placed in that folder.
            Output files are written to the same folder; returned output_filename is the bare name only.
        
            Args:
                input_filename: Bare filename of the CAD file placed in ASPOSE_FILES_PATH.
                layout_names: List of layout names that should be included in the resulting PDF.
                output_filename: Desired PDF filename (bare name). If omitted, a temporary name is generated.
        
            Returns:
                dict: {
                    "status": "success" | "error",
                    "message": str,
                    "output_filename": str   # bare name of the created PDF
                }
        
            Example:
                >>> result = await cad_export_layout_to_pdf(
                ...     input_filename="drawing.dwg",
                ...     layout_names=["Layout1", "Layout2"],
                ...     output_filename="output.pdf",
                ... )
                >>> result["status"]
                "success"
                >>> result["output_filename"]
                "output.pdf"
        
            Raises:
                FileNotFoundError: If the input CAD file does not exist.
                ValueError: If layout_names is empty.
                Exception: Any unexpected error from Aspose.CAD.
            """
            # ----------------------------------------------------------------------
            # Validate and resolve input file
            # ----------------------------------------------------------------------
            from pathlib import Path
            from mcp_server.path_utils import get_safe_path, temp_output_path
            import logging
        
            logger = logging.getLogger(__name__)
        
            # sanitize input filename
            input_filename = Path(input_filename.strip().replace("\x00", "")).name
            resolved_input = get_safe_path(input_filename)
            if not Path(resolved_input).is_file():
                raise FileNotFoundError(f"File not found: {input_filename}")
        
            # validate layout list
            if not layout_names:
                raise ValueError("layout_names must contain at least one layout name.")
        
            # ----------------------------------------------------------------------
            # Sanitize and resolve output filename
            # ----------------------------------------------------------------------
            if output_filename is not None:
                output_filename = Path(output_filename.strip().replace("\x00", "")).name
                resolved_output = get_safe_path(output_filename)
                output_bare_name = output_filename
            else:
                temp_path = temp_output_path("cad_result", ".pdf")
                resolved_output = str(temp_path)
                output_bare_name = Path(resolved_output).name
        
            # ensure output directory exists
            Path(resolved_output).parent.mkdir(parents=True, exist_ok=True)
        
            # ----------------------------------------------------------------------
            # Perform conversion using Aspose.CAD
            # ----------------------------------------------------------------------
            try:
                # lazy import of Aspose.CAD core and option classes
                import aspose.cad as cad
                from aspose.cad.imageoptions import CadRasterizationOptions, PdfOptions
        
                img = cad.Image.load(str(resolved_input))
        
                raster_opts = CadRasterizationOptions()
                try:
                    raster_opts.set_Layouts(layout_names)  # type: ignore[attr-defined]
                except Exception:
                    # If the API does not support layout filtering, ignore the error.
                    pass
        
                pdf_opts = PdfOptions()
                pdf_opts.vector_rasterization_options = raster_opts
        
                img.save(str(resolved_output), pdf_opts)
        
                logger.info(
                    "CAD file %s exported to PDF %s with layouts %s",
                    input_filename,
                    output_bare_name,
                    layout_names,
                )
                return {
                    "status": "success",
                    "message": f"Exported {len(layout_names)} layout(s) to PDF.",
                    "output_filename": output_bare_name,
                }
            except Exception as exc:
                logger.exception("Failed to export CAD to PDF")
                return {
                    "status": "error",
                    "message": str(exc),
                    "output_filename": output_bare_name if "output_bare_name" in locals() else "",
                }

        @mcp.tool()
        async def cad_export_layer_to_png(
            input_filename: str,
            layer_names: list[str],
            output_filename: str | None = None,
        ) -> dict:
            """
            Export selected layers of a CAD file to a PNG image.
        
            IMPORTANT: All *_filename parameters accept ONLY the bare filename (e.g. 'scan.jpg') — no path, no directory, no drive letter, no slash.
            The file MUST already exist in the server's ASPOSE_FILES_PATH folder.
            Do NOT ask the user to upload a file — files are pre‑placed in that folder.
            Output files are written to the same folder; returned output_filename is the bare name only.
        
            Args:
                input_filename: Bare filename of the CAD file placed in ASPOSE_FILES_PATH.
                layer_names: List of layer names to include in the exported PNG.
                output_filename: Desired PNG filename (bare name only). If omitted, a temporary name is generated.
        
            Returns:
                dict: {
                    "status": "success" | "error",
                    "message": str,
                    "output_filename": str   # bare name of the created PNG
                }
        
            Raises:
                FileNotFoundError: If the input CAD file does not exist.
                ValueError: If layer_names is not a list of strings.
                Exception: Any unexpected error from Aspose.CAD.
        
            Example:
                >>> result = await cad_export_layer_to_png(
                ...     input_filename="plan.dwg",
                ...     layer_names=["Layer1", "Layer2"],
                ...     output_filename="selected_layers.png",
                ... )
            """
            # ----------------------------------------------------------------------
            # Resolve and validate input file
            # ----------------------------------------------------------------------
            from pathlib import Path
            from mcp_server.path_utils import get_safe_path, temp_output_path
            import logging
        
            logger = logging.getLogger(__name__)
        
            # sanitize input filename
            input_filename = Path(input_filename.strip().replace("\x00", "")).name
            resolved_input = get_safe_path(input_filename)
            if not Path(resolved_input).is_file():
                raise FileNotFoundError(f"File not found: {input_filename}")
        
            # validate layer_names
            if not isinstance(layer_names, list) or not all(isinstance(l, str) for l in layer_names):
                raise ValueError("layer_names must be a list of strings")
        
            # ----------------------------------------------------------------------
            # Resolve output file
            # ----------------------------------------------------------------------
            if output_filename is not None:
                output_filename = Path(output_filename.strip().replace("\x00", "")).name
                resolved_output = get_safe_path(output_filename)
            else:
                # generate temporary filename with .png suffix
                temp_path = temp_output_path("cad_result", ".png")
                resolved_output = str(temp_path)  # Aspose expects a plain string
                output_filename = Path(resolved_output).name
        
            # ensure output directory exists
            Path(resolved_output).parent.mkdir(parents=True, exist_ok=True)
        
            # ----------------------------------------------------------------------
            # Aspose.CAD processing (lazy import)
            # ----------------------------------------------------------------------
            try:
                import aspose.cad as cad
                from aspose.cad.imageoptions import CadRasterizationOptions, PngOptions
        
                # load the CAD image (no context manager)
                img = cad.Image.load(str(resolved_input))
        
                # configure rasterization options to include only the requested layers
                raster_opts = CadRasterizationOptions()
                if hasattr(raster_opts, "layers"):
                    raster_opts.layers = layer_names
                else:
                    setattr(raster_opts, "Layers", layer_names)
        
                # create PNG options and attach rasterization options
                png_opts = PngOptions()
                png_opts.vector_rasterization_options = raster_opts
        
                # save the image
                img.save(str(resolved_output), png_opts)
        
                logger.info(
                    "CAD layers exported to PNG: %s (layers: %s)",
                    output_filename,
                    ", ".join(layer_names),
                )
                return {
                    "status": "success",
                    "message": f"PNG created with {len(layer_names)} layer(s).",
                    "output_filename": output_filename,
                }
        
            except FileNotFoundError:
                # re‑raise to keep the original exception type for the caller
                raise
            except Exception as exc:
                logger.exception("Error exporting CAD layers to PNG")
                return {"status": "error", "message": str(exc), "output_filename": output_filename}
