# Auto-generated by Aspose MCP Builder — do not edit manually.
# Product: Aspose.Diagram for Python via .NET  Package: aspose-diagram-python
from __future__ import annotations

import logging
import tempfile
from pathlib import Path

from mcp_server.plugin import AsposePlugin
from mcp_server.path_utils import get_safe_path, temp_output_path, apply_license_for, platform_hint

logger = logging.getLogger(__name__)


class DiagramPlugin(AsposePlugin):
    product_name = "diagram"
    pypi_package = "aspose-diagram-python"
    min_version = "24.1.0"

    def health_check(self) -> bool:
        """Check that the Aspose DIAGRAM package is importable.

        Args:
            None

        Returns:
            True if the package imports without error, False otherwise.

        Raises:
            None. Import errors are caught and return False.

        Example:
            >>> plugin = DiagramPlugin()
            >>> isinstance(plugin.health_check(), bool)
            True
        """
        try:
            import aspose.diagram  # noqa: F401, PLC0415
            return True
        except Exception:
            return False

    def get_tool_manifest(self) -> list[dict[str, object]]:
        """Return metadata for all registered tools.

        Args:
            None

        Returns:
            List of dicts each with keys: name, description, params, returns.

        Raises:
            None.

        Example:
            >>> plugin = DiagramPlugin()
            >>> manifest = plugin.get_tool_manifest()
            >>> len(manifest) >= 15
            True
        """
        return [
            {"name": 'diagram_list_files', "description": 'Lists all files in the ASPOSE_FILES_PATH directory, optionally filtering by file extension.', "params": [{"name": 'extension_filter', "type": 'str | None', "required": False, "description": ""}], "returns": "dict"},
            {"name": 'diagram_convert_to_pdf', "description": 'Converts a Visio diagram to PDF format.', "params": [{"name": 'input_filename', "type": 'str', "required": True, "description": ""}, {"name": 'output_filename', "type": 'str | None', "required": False, "description": ""}], "returns": "dict"},
            {"name": 'diagram_convert_to_png', "description": 'Converts a Visio diagram to PNG image format.', "params": [{"name": 'input_filename', "type": 'str', "required": True, "description": ""}, {"name": 'output_filename', "type": 'str | None', "required": False, "description": ""}], "returns": "dict"},
            {"name": 'diagram_convert_to_jpeg', "description": 'Converts a Visio diagram to JPEG image format.', "params": [], "returns": "dict"},
            {"name": 'diagram_convert_to_svg', "description": 'Converts a Visio diagram to SVG vector image format.', "params": [{"name": 'input_filename', "type": 'str', "required": True, "description": ""}, {"name": 'output_filename', "type": 'str | None', "required": False, "description": ""}], "returns": "dict"},
            {"name": 'diagram_convert_to_tiff', "description": 'Converts a Visio diagram to TIFF image format.', "params": [], "returns": "dict"},
            {"name": 'diagram_convert_to_html', "description": 'Converts a Visio diagram to an HTML representation.', "params": [{"name": 'input_filename', "type": 'str', "required": True, "description": ""}, {"name": 'output_filename', "type": 'str | None', "required": False, "description": ""}], "returns": "dict"},
            {"name": 'diagram_convert_to_xps', "description": 'Converts a Visio diagram to XPS document format.', "params": [{"name": 'input_filename', "type": 'str', "required": True, "description": ""}, {"name": 'output_filename', "type": 'str | None', "required": False, "description": ""}], "returns": "dict"},
            {"name": 'diagram_convert_to_vsdx', "description": 'Converts a Visio diagram (including legacy .vsd) to the modern VSDX format.', "params": [{"name": 'input_filename', "type": 'str', "required": True, "description": ""}, {"name": 'output_filename', "type": 'str | None', "required": False, "description": ""}], "returns": "dict"},
            {"name": 'diagram_convert_to_vsdm', "description": 'Converts a Visio diagram to the macro‑enabled VSDM format.', "params": [{"name": 'input_filename', "type": 'str', "required": True, "description": ""}, {"name": 'output_filename', "type": 'str | None', "required": False, "description": ""}], "returns": "dict"},
            {"name": 'diagram_convert_to_vdx', "description": 'Converts a Visio diagram to the older VDX (Visio 2002‑2003) format.', "params": [{"name": 'input_filename', "type": 'str', "required": True, "description": ""}, {"name": 'output_filename', "type": 'str | None', "required": False, "description": ""}], "returns": "dict"},
            {"name": 'diagram_convert_to_bmp', "description": 'Converts a Visio diagram to BMP image format.', "params": [{"name": 'input_filename', "type": 'str', "required": True, "description": ""}, {"name": 'output_filename', "type": 'str | None', "required": False, "description": ""}], "returns": "dict"},
            {"name": 'diagram_convert_to_gif', "description": 'Converts a Visio diagram to GIF image format.', "params": [{"name": 'input_filename', "type": 'str', "required": True, "description": ""}, {"name": 'output_filename', "type": 'str | None', "required": False, "description": ""}], "returns": "dict"},
            {"name": 'diagram_convert_to_emf', "description": 'Converts a Visio diagram to EMF vector image format.', "params": [{"name": 'input_filename', "type": 'str', "required": True, "description": ""}, {"name": 'output_filename', "type": 'str | None', "required": False, "description": ""}], "returns": "dict"},
            {"name": 'diagram_get_diagram_info', "description": 'Retrieves basic information about a Visio diagram, including page count, page names, and shape counts per page.', "params": [{"name": 'input_filename', "type": 'str', "required": True, "description": ""}], "returns": "dict"},
            {"name": 'diagram_export_page_to_pdf', "description": 'Exports a single page of a Visio diagram to a PDF file.', "params": [{"name": 'input_filename', "type": 'str', "required": True, "description": ""}, {"name": 'page_index', "type": 'int', "required": True, "description": ""}, {"name": 'output_filename', "type": 'str | None', "required": False, "description": ""}], "returns": "dict"},
            {"name": 'diagram_export_page_to_png', "description": 'Exports a single page of a Visio diagram to a PNG image.', "params": [{"name": 'input_filename', "type": 'str', "required": True, "description": ""}, {"name": 'page_index', "type": 'int', "required": True, "description": ""}, {"name": 'output_filename', "type": 'str | None', "required": False, "description": ""}], "returns": "dict"},
            {"name": 'diagram_list_shapes', "description": "Lists all shapes on a specified page of a Visio diagram, including each shape's name and plain text.", "params": [{"name": 'input_filename', "type": 'str', "required": True, "description": ""}, {"name": 'page_index', "type": 'int | None', "required": False, "description": ""}], "returns": "dict"},
            {"name": 'diagram_detect_format', "description": 'Detects the file format of a given Visio document.', "params": [{"name": 'input_filename', "type": 'str', "required": True, "description": ""}], "returns": "dict"}
        ]

    def register_tools(self, mcp: "FastMCP") -> None:
        """Register all DIAGRAM tools with the FastMCP instance.

        Args:
            mcp: FastMCP server instance to register tools on.

        Returns:
            None.

        Raises:
            None.

        Example:
            >>> from mcp.server.fastmcp import FastMCP
            >>> mcp = FastMCP("test")
            >>> DiagramPlugin().register_tools(mcp)
        """
        logger.debug("%s plugin registering tools. Platform: %s", "DIAGRAM", platform_hint())
        apply_license_for("aspose.diagram")
        @mcp.tool()
        async def diagram_list_files(extension_filter: str | None = None) -> dict:
            """List files already present in the server's ASPOSE_FILES_PATH folder. Call this first to discover available files — do NOT ask the user to upload.
        
            IMPORTANT: All *_filename parameters accept ONLY the bare filename (e.g. 'scan.jpg') — no path, no directory, no drive letter, no slash.
            The file MUST already exist in the server's ASPOSE_FILES_PATH folder before calling this tool.
            Do NOT ask the user to upload a file — files are pre-placed in the server folder by the user.
            The output file is also written to the ASPOSE_FILES_PATH folder; the returned output_filename is the bare name only.
        
            Args:
                extension_filter: Optional file extension to filter by, e.g. 'jpg'. None lists all files.
        
            Returns:
                dict: {"status": "success"|"error", "files": list[str], "folder_path": str, "message": str}
        
            Raises:
                None. Errors are returned as {"status": "error", "message": str}.
        
            Example:
                result = await diagram_list_files("jpg")
                # result["files"] contains bare filenames matching the extension
            """
            from pathlib import Path
            from mcp_server.path_utils import get_safe_path
            import logging
        
            logger = logging.getLogger(__name__)
            resolved_folder = get_safe_path("")
            if not Path(resolved_folder).is_dir():
                return {"status": "error", "message": "ASPOSE_FILES_PATH folder not found."}
            try:
                files: list[str] = []
                for entry in Path(resolved_folder).iterdir():
                    if not entry.is_file():
                        continue
                    if extension_filter and entry.suffix.lower() != f".{extension_filter.lower().lstrip('.')}":
                        continue
                    files.append(entry.name)
                return {
                    "status": "success",
                    "message": f"Listed {len(files)} file(s).",
                    "files": sorted(files),
                    "folder_path": resolved_folder,
                }
            except Exception as exc:
                logger.exception("Error listing files.")
                return {"status": "error", "message": str(exc)}

        @mcp.tool()
        async def diagram_convert_to_pdf(
            input_filename: str,
            output_filename: str | None = None,
        ) -> dict:
            """
            Convert a Visio diagram stored on the server to PDF.
        
            IMPORTANT:
            * All *_filename parameters accept ONLY the bare filename (e.g. 'drawing.vsdx') — no path, no directory, no drive letter, no slash.
            * The file MUST already exist in the server's ASPOSE_FILES_PATH folder before calling this tool.
            * Do NOT ask the user to upload a file — files are pre‑placed in the server folder by the user.
            * The output file is also written to the ASPOSE_FILES_PATH folder; the returned output_filename is the bare name only.
        
            Args:
                input_filename: Bare filename of the source Visio file, e.g. 'diagram.vsdx'.
                output_filename: Optional bare filename for the resulting PDF. If omitted, a temporary
                                 filename is generated.
        
            Returns:
                dict: {
                    "status": "success" | "error",
                    "message": str,
                    "output_filename": str   # bare name of the created PDF
                }
        
            Raises:
                FileNotFoundError: If the input file does not exist in ASPOSE_FILES_PATH.
                Exception: For any unexpected errors during conversion.
        
            Example:
                result = await diagram_convert_to_pdf("example.vsdx", "example.pdf")
                # result -> {"status":"success","message":"Converted successfully","output_filename":"example.pdf"}
            """
            # ----------------------------------------------------------------------
            # Resolve and validate input file
            # ----------------------------------------------------------------------
            from pathlib import Path
            from mcp_server.path_utils import get_safe_path, temp_output_path
            import logging
        
            logger = logging.getLogger(__name__)
        
            # sanitize input filename (strip null bytes, keep only the name)
            input_filename = Path(input_filename.strip().replace("\x00", "")).name
            resolved_input = get_safe_path(input_filename)
            if not Path(resolved_input).is_file():
                raise FileNotFoundError(f"File not found: {input_filename}")
        
            # ----------------------------------------------------------------------
            # Resolve output location
            # ----------------------------------------------------------------------
            if output_filename is not None:
                output_filename = Path(output_filename.strip().replace("\x00", "")).name
                resolved_output = get_safe_path(output_filename)
            else:
                # generate a temporary filename with .pdf suffix
                temp_path = temp_output_path("aspose_diagram_result", ".pdf")
                resolved_output = str(temp_path)  # Aspose expects a plain string
                output_filename = Path(resolved_output).name
        
            # ensure output directory exists
            Path(resolved_output).parent.mkdir(parents=True, exist_ok=True)
        
            # ----------------------------------------------------------------------
            # Perform conversion using Aspose.Diagram
            # ----------------------------------------------------------------------
            try:
                # lazy import as required by the deployment rules
                from aspose.diagram import Diagram, SaveFileFormat
        
                diagram = Diagram(resolved_input)
                diagram.save(resolved_output, SaveFileFormat.PDF)
        
                logger.info(
                    "Converted Visio file '%s' to PDF '%s'",
                    input_filename,
                    output_filename,
                )
                return {
                    "status": "success",
                    "message": "Conversion completed successfully.",
                    "output_filename": output_filename,
                }
        
            except Exception as exc:  # pragma: no cover
                logger.exception("Failed to convert Visio to PDF: %s", exc)
                return {
                    "status": "error",
                    "message": str(exc),
                    "output_filename": output_filename,
                }

        @mcp.tool()
        async def diagram_convert_to_png(
            input_filename: str,
            output_filename: str | None = None,
        ) -> dict:
            """
            Convert a Visio diagram file stored on the server to a PNG image.
        
            IMPORTANT:
            * All *_filename parameters accept ONLY the bare filename (e.g. 'scan.vsdx') — no path, no directory, no drive letter, no slash.
            * The file MUST already exist in the server's ASPOSE_FILES_PATH folder before calling this tool.
            * Do NOT ask the user to upload a file — files are pre‑placed in the server folder by the user.
            * The output file is also written to the ASPOSE_FILES_PATH folder; the returned output_filename is the bare name only.
        
            Args:
                input_filename: Bare filename of the source Visio file, e.g. "diagram.vsdx".
                output_filename: Optional bare filename for the resulting PNG. If omitted, a temporary
                                 filename is generated.
        
            Returns:
                dict: {
                    "status": "success" | "error",
                    "message": str,
                    "output_filename": str   # bare name of the PNG file (generated or supplied)
                }
        
            Raises:
                FileNotFoundError: If the input file does not exist in ASPOSE_FILES_PATH.
                ValueError: If the diagram cannot be saved (e.g., invalid page index).
                Exception: For any unexpected Aspose errors.
        
            Example:
                result = await diagram_convert_to_png("example.vsdx", "example.png")
                # result["output_filename"] == "example.png"
            """
            # ----------------------------------------------------------------------
            # Resolve and validate input file
            # ----------------------------------------------------------------------
            from pathlib import Path
            from mcp_server.path_utils import get_safe_path, temp_output_path
            import logging
        
            logger = logging.getLogger(__name__)
        
            # sanitize input filename (strip null bytes, keep only name)
            input_filename = Path(input_filename.strip().replace("\x00", "")).name
            resolved_input = get_safe_path(input_filename)
            if not Path(resolved_input).is_file():
                raise FileNotFoundError(f"File not found: {input_filename}")
        
            # ----------------------------------------------------------------------
            # Resolve output location
            # ----------------------------------------------------------------------
            if output_filename is not None:
                output_filename = Path(output_filename.strip().replace("\x00", "")).name
                resolved_output = get_safe_path(output_filename)
            else:
                # generate a temporary filename with .png suffix
                temp_path = temp_output_path("aspose_diagram_result", ".png")
                resolved_output = str(temp_path)  # Aspose expects a plain str
                output_filename = Path(resolved_output).name
        
            # Ensure the output directory exists
            Path(resolved_output).parent.mkdir(parents=True, exist_ok=True)
        
            # ----------------------------------------------------------------------
            # Perform conversion using Aspose.Diagram
            # ----------------------------------------------------------------------
            try:
                # Lazy import of Aspose
                from aspose.diagram import Diagram, SaveFileFormat, saving
        
                diagram = Diagram(resolved_input)
        
                opts = saving.ImageSaveOptions(SaveFileFormat.PNG)
                opts.page_index = 0  # first page
        
                diagram.save(resolved_output, opts)
        
                logger.info(
                    "Converted Visio '%s' to PNG '%s'",
                    input_filename,
                    output_filename,
                )
                return {
                    "status": "success",
                    "message": "Conversion completed successfully.",
                    "output_filename": output_filename,
                }
        
            except Exception as exc:  # pragma: no cover
                logger.exception("Failed to convert Visio to PNG: %s", exc)
                return {
                    "status": "error",
                    "message": str(exc),
                    "output_filename": output_filename,
                }

        @mcp.tool()
        def diagram_convert_to_jpeg() -> dict:
            """Converts a Visio diagram to JPEG image format.
        
            Args:
                None
        
            Returns:
                dict: {"status": "stub", "message": str}
        
            Raises:
                None
        
            Example:
                >>> result = diagram_convert_to_jpeg()
                >>> result['status']
                'stub'
            """
            return {"status": "stub", "message": "This is a dry-run stub."}

        @mcp.tool()
        async def diagram_convert_to_svg(
            input_filename: str,
            output_filename: str | None = None,
        ) -> dict:
            """
            Convert a Visio diagram file to SVG format.
        
            IMPORTANT: All *_filename parameters accept ONLY the bare filename (e.g. 'scan.jpg') —
            no path, no directory, no drive letter, no slash.
            The file MUST already exist in the server's ASPOSE_FILES_PATH folder.
            Do NOT ask the user to upload a file — files are pre‑placed in that folder.
            Output files are written to the same folder; returned output_filename is the bare name only.
        
            Args:
                input_filename: Bare filename of the source Visio file located in ASPOSE_FILES_PATH.
                output_filename: Desired SVG filename (bare name only). If omitted, a temporary file is generated.
        
            Returns:
                dict: {
                    "status": "success" | "error",
                    "message": str,
                    "output_filename": str   # bare name of the generated SVG file
                }
        
            Raises:
                FileNotFoundError: If the input file does not exist.
                Exception: Any unexpected error raised by Aspose.Diagram.
        
            Example:
                result = await diagram_convert_to_svg("example.vsdx", "example.svg")
                # result["output_filename"] == "example.svg"
            """
            # ----------------------------------------------------------------------
            # Resolve and validate input file
            # ----------------------------------------------------------------------
            from pathlib import Path
            from mcp_server.path_utils import get_safe_path, temp_output_path
            import logging
        
            logger = logging.getLogger(__name__)
        
            # sanitize input filename
            input_filename = Path(input_filename.strip().replace("\x00", "")).name
            resolved_input = get_safe_path(input_filename)
            if not Path(resolved_input).is_file():
                raise FileNotFoundError(f"File not found: {input_filename}")
        
            # ----------------------------------------------------------------------
            # Resolve output location
            # ----------------------------------------------------------------------
            if output_filename is not None:
                output_filename = Path(output_filename.strip().replace("\x00", "")).name
                resolved_output = get_safe_path(output_filename)
                output_basename = output_filename
            else:
                # generate a temporary filename with .svg extension
                temp_path = temp_output_path("aspose_diagram_result", ".svg")
                resolved_output = str(temp_path)  # Aspose expects a plain string
                output_basename = Path(resolved_output).name
        
            # ensure output directory exists
            Path(resolved_output).parent.mkdir(parents=True, exist_ok=True)
        
            # ----------------------------------------------------------------------
            # Perform conversion using Aspose.Diagram
            # ----------------------------------------------------------------------
            try:
                # Lazy import of Aspose.Diagram
                from aspose.diagram import Diagram, SaveFileFormat, saving
        
                diagram = Diagram(str(resolved_input))
                opts = saving.ImageSaveOptions(SaveFileFormat.SVG)
                diagram.save(str(resolved_output), opts)
        
                logger.info(
                    "Converted Visio file %s to SVG %s",
                    input_filename,
                    output_basename,
                )
                return {
                    "status": "success",
                    "message": "File converted to SVG successfully.",
                    "output_filename": output_basename,
                }
            except Exception as exc:  # pragma: no cover
                logger.exception("Error converting Visio to SVG: %s", exc)
                return {
                    "status": "error",
                    "message": str(exc),
                    "output_filename": output_basename,
                }

        @mcp.tool()
        def diagram_convert_to_tiff() -> dict:
            """Converts a Visio diagram to TIFF image format.
        
            Args:
                None
        
            Returns:
                dict: {"status": "stub", "message": str}
        
            Raises:
                None
        
            Example:
                >>> result = diagram_convert_to_tiff()
                >>> result['status']
                'stub'
            """
            return {"status": "stub", "message": "This is a dry-run stub."}

        @mcp.tool()
        async def diagram_convert_to_html(
            input_filename: str,
            output_filename: str | None = None,
        ) -> dict:
            """
            Convert a Visio diagram to HTML.
        
            IMPORTANT:
            - All *_filename parameters accept ONLY the bare filename (e.g. 'diagram.vsdx') — no path, no directory, no drive letter, no slash.
            - The file MUST already exist in the server's ASPOSE_FILES_PATH folder before calling this tool.
            - Do NOT ask the user to upload a file — files are pre-placed in the server folder by the user.
            - The output file is also written to the ASPOSE_FILES_PATH folder; the returned output_filename is the bare name only.
        
            Args:
                input_filename (str): Bare filename of the source Visio file located in ASPOSE_FILES_PATH.
                output_filename (str | None, optional): Desired HTML filename; if omitted a temporary file is generated.
        
            Returns:
                dict: Status object containing at minimum {"status": "success"|"error", "message": str, "output_filename": str}.
        
            Raises:
                FileNotFoundError: If the input file does not exist.
                Exception: Any error raised by Aspose.Diagram during conversion.
        
            Example:
                result = await diagram_convert_to_html("example.vsdx", "example.html")
            """
            # Imports required before any Aspose usage
            import logging
            from pathlib import Path
            from mcp_server.path_utils import get_safe_path, temp_output_path
        
            logger = logging.getLogger(__name__)
        
            # ---- Validate and resolve input file ----
            input_filename = Path(input_filename.strip().replace("\x00", "")).name
            resolved_input = get_safe_path(input_filename)
            if not Path(resolved_input).is_file():
                raise FileNotFoundError(f"File not found: {input_filename}")
        
            # ---- Prepare output file ----
            if output_filename is not None:
                output_filename = Path(output_filename.strip().replace("\x00", "")).name
                resolved_output = get_safe_path(output_filename)
            else:
                # temporary file with .html extension
                resolved_output = str(temp_output_path("aspose_diagram_result", ".html"))
                output_filename = Path(resolved_output).name
        
            # Ensure output directory exists
            Path(resolved_output).parent.mkdir(parents=True, exist_ok=True)
        
            # ---- Aspose.Diagram conversion ----
            try:
                # Lazy import of Aspose.Diagram after validation
                import aspose.diagram as aspose_diagram
                from aspose.diagram import SaveFileFormat
        
                diagram = aspose_diagram.Diagram(str(resolved_input))
                diagram.save(str(resolved_output), SaveFileFormat.HTML)
        
                return {
                    "status": "success",
                    "message": "Diagram converted to HTML successfully.",
                    "output_filename": output_filename,
                }
            except Exception as exc:
                logger.error("Error converting diagram to HTML: %s", exc)
                return {"status": "error", "message": str(exc)}

        @mcp.tool()
        async def diagram_convert_to_xps(
            input_filename: str,
            output_filename: str | None = None,
        ) -> dict:
            """
            Convert a Visio diagram file to XPS format.
        
            IMPORTANT:
            * All *_filename parameters accept ONLY the bare filename (e.g. 'diagram.vsdx') — no path, no directory, no drive letter, no slash.
            * The file MUST already exist in the server's ASPOSE_FILES_PATH folder before calling this tool.
            * Do NOT ask the user to upload a file — files are pre‑placed in the server folder by the user.
            * The output file is also written to the ASPOSE_FILES_PATH folder; the returned output_filename is the bare name only.
        
            Args:
                input_filename: Bare filename of the source Visio file located in ASPOSE_FILES_PATH.
                output_filename: Desired XPS filename (bare name only). If omitted, a temporary file is generated.
        
            Returns:
                dict: {
                    "status": "success" | "error",
                    "message": str,
                    "output_filename": str   # bare name of the generated XPS file
                }
        
            Raises:
                FileNotFoundError: If the input file does not exist.
                Exception: Propagates any Aspose‑Diagram errors as an error status.
        
            Example:
                result = await diagram_convert_to_xps("example.vsdx", "example.xps")
                # result -> {"status":"success","message":"File converted to XPS","output_filename":"example.xps"}
            """
            # ---------- Validate and resolve input ----------
            from pathlib import Path
            from mcp_server.path_utils import get_safe_path, temp_output_path
            import logging
        
            logger = logging.getLogger(__name__)
        
            # sanitize input filename
            input_filename = Path(input_filename.strip().replace("\x00", "")).name
            resolved_input = get_safe_path(input_filename)
            if not Path(resolved_input).is_file():
                raise FileNotFoundError(f"File not found: {input_filename}")
        
            # ---------- Resolve output ----------
            if output_filename is not None:
                output_filename = Path(output_filename.strip().replace("\x00", "")).name
                resolved_output = get_safe_path(output_filename)
            else:
                # generate temporary filename with .xps extension
                temp_path = temp_output_path("aspose_diagram_result", ".xps")
                resolved_output = str(temp_path)
        
            # ensure output directory exists
            Path(resolved_output).parent.mkdir(parents=True, exist_ok=True)
        
            # ---------- Aspose.Diagram processing ----------
            try:
                # lazy import as required
                from aspose.diagram import Diagram, SaveFileFormat
        
                diagram = Diagram(str(resolved_input))
                diagram.save(str(resolved_output), SaveFileFormat.XPS)
        
                logger.info(
                    "Converted Visio file '%s' to XPS '%s'",
                    input_filename,
                    Path(resolved_output).name,
                )
                return {
                    "status": "success",
                    "message": "File converted to XPS",
                    "output_filename": Path(resolved_output).name,
                }
            except Exception as exc:  # pragma: no cover
                logger.error("Error converting Visio to XPS: %s", exc)
                return {"status": "error", "message": str(exc)}

        @mcp.tool()
        async def diagram_convert_to_vsdx(
            input_filename: str,
            output_filename: str | None = None,
        ) -> dict:
            """
            Convert a Visio file to VSDX format using Aspose.Diagram.
        
            IMPORTANT:
            * All *_filename parameters accept ONLY the bare filename (e.g. 'scan.vsd') — no path, no directory, no drive letter, no slash.
            * The file MUST already exist in the server's ASPOSE_FILES_PATH folder before calling this tool.
            * Do NOT ask the user to upload a file — files are pre‑placed in the server folder by the user.
            * The output file is also written to the ASPOSE_FILES_PATH folder; the returned output_filename is the bare name only.
        
            Args:
                input_filename: Bare filename of the source Visio file located in ASPOSE_FILES_PATH.
                output_filename: Desired VSDX filename (bare name only). If omitted, a temporary filename is generated.
        
            Returns:
                dict: {
                    "status": "success" | "error",
                    "message": str,
                    "output_filename": str   # bare name of the generated VSDX file
                }
        
            Raises:
                FileNotFoundError: If the input file does not exist.
                Exception: Propagated as an error status if Aspose processing fails.
        
            Example:
                result = await diagram_convert_to_vsdx("example.vsd", "example_converted.vsdx")
                # result["output_filename"] == "example_converted.vsdx"
            """
            # ------------------------------------------------------------------
            # Resolve and validate input file
            # ------------------------------------------------------------------
            from pathlib import Path
            from mcp_server.path_utils import get_safe_path, temp_output_path
            import logging
        
            logger = logging.getLogger(__name__)
        
            # sanitize input filename
            input_filename = Path(input_filename.strip().replace("\x00", "")).name
            resolved_input = get_safe_path(input_filename)
            if not Path(resolved_input).is_file():
                raise FileNotFoundError(f"File not found: {input_filename}")
        
            # ------------------------------------------------------------------
            # Resolve output file (or generate temporary one)
            # ------------------------------------------------------------------
            if output_filename is not None:
                output_filename = Path(output_filename.strip().replace("\x00", "")).name
                resolved_output = get_safe_path(output_filename)
            else:
                # generate temporary file with .vsdx extension
                temp_path = temp_output_path("aspose_diagram_result", ".vsdx")
                resolved_output = str(temp_path)  # Aspose expects a plain string
                output_filename = Path(resolved_output).name
        
            # ensure output directory exists
            Path(resolved_output).parent.mkdir(parents=True, exist_ok=True)
        
            # ------------------------------------------------------------------
            # Perform conversion using Aspose.Diagram
            # ------------------------------------------------------------------
            try:
                # Lazy import of Aspose.Diagram
                from aspose.diagram import Diagram, SaveFileFormat
        
                logger.debug(
                    "Loading Visio file %s for conversion to VSDX.", resolved_input
                )
                diagram = Diagram(str(resolved_input))
        
                logger.debug("Saving converted file to %s.", resolved_output)
                diagram.save(str(resolved_output), SaveFileFormat.VSDX)
        
                return {
                    "status": "success",
                    "message": f"File converted successfully to {output_filename}.",
                    "output_filename": output_filename,
                }
        
            except Exception as exc:  # pragma: no cover
                logger.exception("Aspose.Diagram conversion failed.")
                return {
                    "status": "error",
                    "message": str(exc),
                    "output_filename": output_filename,
                }

        @mcp.tool()
        async def diagram_convert_to_vsdm(
            input_filename: str,
            output_filename: str | None = None,
        ) -> dict:
            """
            Convert a Visio file to VSDM format.
        
            IMPORTANT:
            * All *_filename parameters accept ONLY the bare filename (e.g. 'scan.jpg') — no path, no directory, no drive letter, no slash.
            * The file MUST already exist in the server's ASPOSE_FILES_PATH folder before calling this tool.
            * Do NOT ask the user to upload a file — files are pre‑placed in the server folder by the user.
            * The output file is also written to the ASPOSE_FILES_PATH folder; the returned output_filename is the bare name only.
        
            Args:
                input_filename: bare filename of the source Visio file, e.g. "diagram.vsdx" — must already exist in ASPOSE_FILES_PATH.
                output_filename: optional bare filename for the resulting VSDM file. If omitted, a temporary file is created.
        
            Returns:
                dict: {
                    "status": "success" | "error",
                    "message": str,
                    "output_filename": str   # bare name of the generated VSDM file
                }
        
            Raises:
                FileNotFoundError: if the input file does not exist.
                Exception: any unexpected error raised by Aspose.Diagram.
        
            Example:
                result = await diagram_convert_to_vsdm("example.vsdx", "example_converted.vsdm")
                # result -> {"status":"success","message":"File saved","output_filename":"example_converted.vsdm"}
            """
            # ---------- Resolve and validate input ----------
            from pathlib import Path
            from mcp_server.path_utils import get_safe_path, temp_output_path
            import logging
        
            logger = logging.getLogger(__name__)
        
            # sanitize input filename
            input_filename = Path(input_filename.strip().replace("\x00", "")).name
            resolved_input = get_safe_path(input_filename)
            if not Path(resolved_input).is_file():
                raise FileNotFoundError(f"File not found: {input_filename}")
        
            # ---------- Resolve output ----------
            if output_filename is not None:
                output_filename = Path(output_filename.strip().replace("\x00", "")).name
                resolved_output = get_safe_path(output_filename)
            else:
                # generate a temporary filename with .vsdm extension
                temp_path = temp_output_path("aspose_diagram_result", ".vsdm")
                resolved_output = str(temp_path)  # Aspose expects a plain string
                output_filename = Path(resolved_output).name
        
            # ensure output directory exists
            Path(resolved_output).parent.mkdir(parents=True, exist_ok=True)
        
            # ---------- Aspose processing ----------
            try:
                import aspose.diagram as diagram_mod
        
                # Load the diagram
                diagram = diagram_mod.Diagram(str(resolved_input))
        
                # Save as VSDM
                diagram.save(str(resolved_output), diagram_mod.SaveFileFormat.VSDM)
        
                logger.info("Converted %s to VSDM as %s", input_filename, output_filename)
                return {
                    "status": "success",
                    "message": "File converted and saved successfully.",
                    "output_filename": output_filename,
                }
            except Exception as exc:  # pragma: no cover
                logger.exception("Error converting %s to VSDM: %s", input_filename, exc)
                return {
                    "status": "error",
                    "message": str(exc),
                    "output_filename": output_filename,
                }

        @mcp.tool()
        async def diagram_convert_to_vdx(
            input_filename: str,
            output_filename: str | None = None,
        ) -> dict:
            """
            Convert a Visio file stored on the server to VDX format.
        
            IMPORTANT:
            All *_filename parameters accept ONLY the bare filename (e.g. 'diagram.vsdx') — no path, no directory, no drive letter, no slash.
            The file MUST already exist in the server's ASPOSE_FILES_PATH folder before calling this tool.
            Do NOT ask the user to upload a file — files are pre‑placed in the server folder by the user.
            The output file is also written to the ASPOSE_FILES_PATH folder; the returned output_filename is the bare name only.
        
            Args:
                input_filename: bare filename of the source Visio file, e.g. ``'example.vsdx'``.
                output_filename: optional bare filename for the resulting VDX file. If omitted, a temporary filename is generated.
        
            Returns:
                dict: {
                    "status": "success" | "error",
                    "message": str,
                    "output_filename": str   # present only on success, bare name of the VDX file
                }
        
            Raises:
                FileNotFoundError: if the input file does not exist.
                Exception: any unexpected error during conversion.
        
            Example:
                result = await diagram_convert_to_vdx("sample.vsdx", "sample_converted.vdx")
            """
            from pathlib import Path
            from mcp_server.path_utils import get_safe_path, temp_output_path
            import logging
        
            logger = logging.getLogger(__name__)
        
            # ---- Validate and resolve input file ----
            input_filename = Path(input_filename.strip().replace("\x00", "")).name
            resolved_input = get_safe_path(input_filename)
            if not Path(resolved_input).is_file():
                raise FileNotFoundError(f"File not found: {input_filename}")
        
            # ---- Resolve output file ----
            if output_filename is not None:
                output_filename = Path(output_filename.strip().replace("\x00", "")).name
                resolved_output = get_safe_path(output_filename)
            else:
                temp_path = temp_output_path("aspose_diagram_result", ".vdx")
                resolved_output = str(temp_path)
                output_filename = Path(resolved_output).name
        
            # Ensure the output directory exists
            Path(resolved_output).parent.mkdir(parents=True, exist_ok=True)
        
            try:
                # Lazy import Aspose.Diagram
                from aspose.diagram import Diagram, SaveFileFormat
        
                diagram = Diagram(str(resolved_input))
                diagram.save(str(resolved_output), SaveFileFormat.VDX)
        
                logger.info("Converted %s to VDX as %s", input_filename, output_filename)
                return {
                    "status": "success",
                    "message": "File converted to VDX successfully.",
                    "output_filename": output_filename,
                }
            except Exception as exc:  # pragma: no cover
                logger.exception("Error converting %s to VDX: %s", input_filename, exc)
                return {"status": "error", "message": str(exc)}

        @mcp.tool()
        async def diagram_convert_to_bmp(
            input_filename: str,
            output_filename: str | None = None,
        ) -> dict:
            """
            Convert a Visio diagram file to BMP format.
        
            IMPORTANT: All *_filename parameters accept ONLY the bare filename (e.g. 'scan.jpg') —
            no path, no directory, no drive letter, no slash.
            The file MUST already exist in the server's ASPOSE_FILES_PATH folder.
            Do NOT ask the user to upload a file — files are pre‑placed in that folder.
            Output files are written to the same folder; returned output_filename is the bare name only.
        
            Args:
                input_filename: Bare filename of the source Visio file, e.g. ``'diagram.vsdx'``.
                output_filename: Optional bare filename for the resulting BMP file. If omitted,
                                 a temporary filename is generated.
        
            Returns:
                dict: Contains ``status`` (``"success"`` or ``"error"``), a human‑readable ``message``,
                      and ``output_filename`` – the bare name of the generated BMP file.
        
            Raises:
                FileNotFoundError: If the input file does not exist.
                Exception: For any error raised by Aspose.Diagram during conversion.
        
            Example:
                result = await diagram_convert_to_bmp("example.vsdx", "example.bmp")
                # result -> {"status": "success", "message": "...", "output_filename": "example.bmp"}
            """
            from pathlib import Path
            from mcp_server.path_utils import get_safe_path, temp_output_path
            import logging
        
            logger = logging.getLogger(__name__)
        
            # ---- Resolve input file -------------------------------------------------
            input_filename = Path(input_filename.strip().replace("\x00", "")).name
            resolved_input = get_safe_path(input_filename)
            if not Path(resolved_input).is_file():
                raise FileNotFoundError(f"File not found: {input_filename}")
        
            # ---- Resolve output file ------------------------------------------------
            if output_filename is not None:
                output_filename = Path(output_filename.strip().replace("\x00", "")).name
                resolved_output = get_safe_path(output_filename)
            else:
                # generate a temporary BMP file name
                temp_path = temp_output_path("aspose_diagram_result", ".bmp")
                resolved_output = str(temp_path)
                output_filename = Path(resolved_output).name
        
            # Ensure the output directory exists
            Path(resolved_output).parent.mkdir(parents=True, exist_ok=True)
        
            # ---- Perform conversion -------------------------------------------------
            try:
                # Lazy import after validation
                from aspose.diagram import Diagram, SaveFileFormat, saving
        
                logger.debug("Loading diagram from %s", resolved_input)
                diagram = Diagram(str(resolved_input))
        
                logger.debug("Saving diagram as BMP to %s", resolved_output)
                opts = saving.ImageSaveOptions(SaveFileFormat.BMP)
                diagram.save(str(resolved_output), opts)
        
                return {
                    "status": "success",
                    "message": "Diagram converted to BMP successfully.",
                    "output_filename": output_filename,
                }
            except Exception as exc:  # pragma: no cover
                logger.exception("Error converting diagram to BMP")
                return {"status": "error", "message": str(exc)}

        @mcp.tool()
        async def diagram_convert_to_gif(
            input_filename: str,
            output_filename: str | None = None,
        ) -> dict:
            """
            Convert a Visio diagram file to an animated GIF.
        
            IMPORTANT: All *_filename parameters accept ONLY the bare filename (e.g. 'scan.jpg') —
            no path, no directory, no drive letter, no slash.
            The file MUST already exist in the server's ASPOSE_FILES_PATH folder.
            Do NOT ask the user to upload a file — files are pre‑placed in that folder.
            Output files are written to the same folder; returned output_filename is the bare name only.
        
            Args:
                input_filename: bare filename of the source Visio file, e.g. 'diagram.vsdx'.
                output_filename: optional bare filename for the resulting GIF. If omitted, a temporary name is generated.
        
            Returns:
                dict: {
                    "status": "success" | "error",
                    "message": str,
                    "output_filename": str   # present on success, bare name of the generated GIF
                }
        
            Raises:
                FileNotFoundError: if the input file does not exist.
        
            Example:
                result = await diagram_convert_to_gif("example.vsdx", "example.gif")
            """
            from pathlib import Path
            from mcp_server.path_utils import get_safe_path, temp_output_path
            import logging
        
            logger = logging.getLogger(__name__)
        
            # ---- Validate and resolve input file ----
            input_filename = Path(input_filename.strip().replace('\x00', '')).name
            resolved_input = get_safe_path(input_filename)
            if not Path(resolved_input).is_file():
                raise FileNotFoundError(f"File not found: {input_filename}")
        
            # ---- Resolve output file ----
            if output_filename is not None:
                output_filename = Path(output_filename.strip().replace('\x00', '')).name
                resolved_output = get_safe_path(output_filename)
            else:
                # generate a temporary filename with .gif extension
                temp_path = temp_output_path("aspose_diagram_result", ".gif")
                resolved_output = str(temp_path)          # Aspose expects a plain string
                output_filename = Path(resolved_output).name
        
            # Ensure the output directory exists
            Path(resolved_output).parent.mkdir(parents=True, exist_ok=True)
        
            try:
                # ---- Lazy import Aspose.Diagram ----
                import aspose.diagram as ad
                from aspose.diagram import saving
        
                # Load the Visio diagram
                diagram = ad.Diagram(str(resolved_input))
        
                # Prepare GIF save options
                opts = saving.ImageSaveOptions(ad.SaveFileFormat.GIF)
        
                # Save the diagram as GIF using the options
                diagram.save(str(resolved_output), opts)
        
                logger.info("Converted %s to GIF %s", input_filename, output_filename)
                return {
                    "status": "success",
                    "message": "File converted to GIF successfully.",
                    "output_filename": output_filename,
                }
            except Exception as exc:  # pragma: no cover
                logger.exception("Error converting diagram to GIF")
                return {
                    "status": "error",
                    "message": str(exc),
                }

        @mcp.tool()
        async def diagram_convert_to_emf(
            input_filename: str,
            output_filename: str | None = None,
        ) -> dict:
            """
            Convert a Visio diagram file to EMF format.
        
            IMPORTANT: All *_filename parameters accept ONLY the bare filename (e.g. 'scan.jpg') —
            no path, no directory, no drive letter, no slash.
            The file MUST already exist in the server's ASPOSE_FILES_PATH folder.
            Do NOT ask the user to upload a file — files are pre‑placed in that folder.
            Output files are written to the same folder; returned output_filename is the bare name only.
        
            Args:
                input_filename: Bare filename of the source Visio file, e.g. "diagram.vsdx". Must exist in ASPOSE_FILES_PATH.
                output_filename: Optional bare filename for the resulting EMF file. If omitted, a temporary filename is generated.
        
            Returns:
                dict: {
                    "status": "success" | "error",
                    "message": str,
                    "output_filename": str   # bare name of the generated EMF file
                }
        
            Raises:
                FileNotFoundError: If the input file does not exist.
                Exception: Any unexpected error from Aspose.Diagram.
        
            Example:
                result = await diagram_convert_to_emf("example.vsdx", "example.emf")
                # result["output_filename"] -> "example.emf"
            """
            # ----------------------------------------------------------------------
            # Imports that are NOT Aspose – must appear before any Aspose usage
            # ----------------------------------------------------------------------
            from pathlib import Path
            from mcp_server.path_utils import get_safe_path, temp_output_path
            import logging
        
            logger = logging.getLogger(__name__)
        
            # ----------------------------------------------------------------------
            # Validate and resolve input file
            # ----------------------------------------------------------------------
            input_filename = Path(input_filename.strip().replace('\x00', '')).name
            resolved_input = get_safe_path(input_filename)
            if not Path(resolved_input).is_file():
                raise FileNotFoundError(f"File not found: {input_filename}")
        
            # ----------------------------------------------------------------------
            # Prepare output file
            # ----------------------------------------------------------------------
            if output_filename is not None:
                output_filename = Path(output_filename.strip().replace('\x00', '')).name
                resolved_output = get_safe_path(output_filename)
            else:
                # generate a temporary filename with .emf extension
                temp_path = temp_output_path("aspose_diagram_result", ".emf")
                resolved_output = str(temp_path)
                output_filename = Path(resolved_output).name
        
            # Ensure the output directory exists
            Path(resolved_output).parent.mkdir(parents=True, exist_ok=True)
        
            # ----------------------------------------------------------------------
            # Aspose.Diagram processing
            # ----------------------------------------------------------------------
            try:
                # Lazy import of Aspose
                import aspose.diagram as diagram_mod
                from aspose.diagram import SaveFileFormat, saving
        
                # Load the diagram
                diagram = diagram_mod.Diagram(str(resolved_input))
        
                # Prepare image save options for EMF
                opts = saving.ImageSaveOptions(SaveFileFormat.EMF)
        
                # Save as EMF using the options
                diagram.save(str(resolved_output), opts)
        
                logger.info(
                    "Converted Visio file %s to EMF %s",
                    input_filename,
                    output_filename,
                )
                return {
                    "status": "success",
                    "message": "Conversion completed successfully.",
                    "output_filename": output_filename,
                }
        
            except Exception as exc:  # pragma: no cover
                logger.exception("Error converting Visio to EMF: %s", exc)
                return {
                    "status": "error",
                    "message": str(exc),
                    "output_filename": output_filename,
                }

        @mcp.tool()
        async def diagram_get_diagram_info(
            input_filename: str,
        ) -> dict:
            """
            Retrieve basic information about a Visio diagram stored on the server.
        
            IMPORTANT:
            * All *_filename parameters accept ONLY the bare filename (e.g. 'scan.vsdx') — no path, no directory, no drive letter, no slash.
            * The file MUST already exist in the server's ASPOSE_FILES_PATH folder before calling this tool.
            * Do NOT ask the user to upload a file — files are pre‑placed in the server folder by the user.
            * The output file is also written to the ASPOSE_FILES_PATH folder; the returned output_filename is the bare name only.
        
            Args:
                input_filename: Bare filename of the Visio file to inspect, e.g. "diagram.vsdx". The file must reside in ASPOSE_FILES_PATH.
        
            Returns:
                dict: A dictionary containing:
                    - status (str): "success" or "error".
                    - message (str): Human‑readable description of the result or error.
                    - page_count (int, optional): Number of pages in the diagram (present on success).
                    - page_names (list[str], optional): Names of each page (present on success).
                    - shapes_per_page (list[int], optional): Shape count for each page (present on success).
        
            Raises:
                FileNotFoundError: If the specified input file does not exist in ASPOSE_FILES_PATH.
                Exception: Any unexpected error raised by Aspose.Diagram.
        
            Example:
                >>> result = await diagram_get_diagram_info("sample.vsdx")
                >>> result["page_count"]
                3
            """
            # ------------------------------------------------------------------
            # Resolve and validate the input file (must be a bare filename)
            # ------------------------------------------------------------------
            from pathlib import Path
            from mcp_server.path_utils import get_safe_path, temp_output_path
            import logging
        
            logger = logging.getLogger(__name__)
        
            # Sanitize the provided filename
            input_filename = Path(input_filename.strip().replace('\x00', '')).name
            resolved_input = get_safe_path(input_filename)
        
            if not Path(resolved_input).is_file():
                raise FileNotFoundError(f"File not found: {input_filename}")
        
            # ------------------------------------------------------------------
            # Load the diagram using Aspose.Diagram and collect information
            # ------------------------------------------------------------------
            try:
                # Lazy import of Aspose.Diagram
                from aspose.diagram import Diagram
        
                diagram = Diagram(resolved_input)
        
                page_count = diagram.pages.count
                page_names = [diagram.pages[i].name for i in range(page_count)]
                shapes_per_page = [diagram.pages[i].shapes.count for i in range(page_count)]
        
                logger.debug(
                    "Diagram '%s' processed: %d pages, names=%s, shapes=%s",
                    input_filename,
                    page_count,
                    page_names,
                    shapes_per_page,
                )
        
                return {
                    "status": "success",
                    "message": f"Diagram '{input_filename}' inspected successfully.",
                    "page_count": page_count,
                    "page_names": page_names,
                    "shapes_per_page": shapes_per_page,
                }
        
            except Exception as exc:  # Catch any Aspose‑related errors
                logger.exception("Error processing diagram %s: %s", input_filename, exc)
                return {
                    "status": "error",
                    "message": str(exc),
                }

        @mcp.tool()
        async def diagram_export_page_to_pdf(
            input_filename: str,
            page_index: int,
            output_filename: str | None = None,
        ) -> dict:
            """
            Convert a single page of a Visio diagram to PDF.
        
            IMPORTANT:
            * All *_filename parameters accept ONLY the bare filename (e.g. 'scan.vsdx') — no path, no directory, no drive letter, no slash.
            * The file MUST already exist in the server's ASPOSE_FILES_PATH folder before calling this tool.
            * Do NOT ask the user to upload a file — files are pre‑placed in the server folder by the user.
            * The output file is also written to the ASPOSE_FILES_PATH folder; the returned output_filename is the bare name only.
        
            Args:
                input_filename: Bare filename of the source Visio file located in ASPOSE_FILES_PATH.
                page_index: Zero‑based index of the page to export.
                output_filename: Desired PDF filename (bare name only). If omitted, a temporary file is generated.
        
            Returns:
                dict: {
                    "status": "success" | "error",
                    "message": str,
                    "output_filename": str   # bare name of the created PDF
                }
        
            Raises:
                FileNotFoundError: If the input Visio file does not exist.
                ValueError: If page_index is negative.
                Exception: For any unexpected error from Aspose.
        
            Example:
                result = await diagram_export_page_to_pdf(
                    input_filename="example.vsdx",
                    page_index=0,
                    output_filename="page0.pdf"
                )
                # result["output_filename"] -> "page0.pdf"
            """
            # ----------------------------------------------------------------------
            # Resolve and validate input file
            # ----------------------------------------------------------------------
            from pathlib import Path
            from mcp_server.path_utils import get_safe_path, temp_output_path
            import logging
        
            logger = logging.getLogger(__name__)
        
            # sanitize input filename
            input_filename = Path(input_filename.strip().replace("\x00", "")).name
            resolved_input = get_safe_path(input_filename)
            if not Path(resolved_input).is_file():
                raise FileNotFoundError(f"File not found: {input_filename}")
        
            # ----------------------------------------------------------------------
            # Resolve output file
            # ----------------------------------------------------------------------
            if output_filename is not None:
                output_filename = Path(output_filename.strip().replace("\x00", "")).name
                resolved_output = get_safe_path(output_filename)
            else:
                # generate a temporary filename with .pdf suffix
                temp_path = temp_output_path("aspose_diagram_result", ".pdf")
                resolved_output = str(temp_path)  # Aspose expects a plain string
                output_filename = Path(resolved_output).name
        
            # ensure output directory exists
            Path(resolved_output).parent.mkdir(parents=True, exist_ok=True)
        
            # ----------------------------------------------------------------------
            # Perform conversion using Aspose.Diagram
            # ----------------------------------------------------------------------
            try:
                # Lazy import of Aspose
                from aspose.diagram import Diagram
                from aspose.diagram import saving
        
                diagram = Diagram(resolved_input)
        
                pdf_opts = saving.PdfSaveOptions()
                pdf_opts.page_index = page_index
        
                diagram.save(resolved_output, pdf_opts)
        
                logger.info(
                    "Exported page %s of %s to PDF %s",
                    page_index,
                    input_filename,
                    output_filename,
                )
                return {
                    "status": "success",
                    "message": f"Page {page_index} exported to PDF successfully.",
                    "output_filename": output_filename,
                }
        
            except Exception as exc:  # pragma: no cover
                logger.exception("Failed to export Visio page to PDF")
                return {
                    "status": "error",
                    "message": str(exc),
                    "output_filename": output_filename,
                }

        @mcp.tool()
        async def diagram_export_page_to_png(
            input_filename: str,
            page_index: int,
            output_filename: str | None = None,
        ) -> dict:
            """
            Convert a specific page of a Visio file to PNG.
        
            IMPORTANT:
            - All *_filename parameters accept ONLY the bare filename (e.g. 'scan.jpg') — no path, no directory, no drive letter, no slash.
            - The file MUST already exist in the server's ASPOSE_FILES_PATH folder before calling this tool.
            - Do NOT ask the user to upload a file — files are pre‑placed in the server folder by the user.
            - The output file is also written to the ASPOSE_FILES_PATH folder; the returned output_filename is the bare name only.
        
            Args:
                input_filename (str): Bare filename of the source Visio file located in ASPOSE_FILES_PATH.
                page_index (int): Zero‑based index of the page to export.
                output_filename (str | None, optional): Desired PNG filename; if omitted a temporary file is generated.
        
            Returns:
                dict: {
                    "status": "success" | "error",
                    "message": str,
                    "output_filename": str   # bare name of the created PNG file
                }
        
            Raises:
                FileNotFoundError: If the input file does not exist.
                ValueError: If `page_index` is negative.
        
            Example:
                result = await diagram_export_page_to_png(
                    input_filename="drawing.vsdx",
                    page_index=0,
                    output_filename="page0.png"
                )
            """
            # ----------------------------------------------------------------------
            # Resolve and validate input file
            # ----------------------------------------------------------------------
            from pathlib import Path
            from mcp_server.path_utils import get_safe_path, temp_output_path
            import logging
        
            logger = logging.getLogger(__name__)
        
            # sanitize filename (strip nulls, keep only name)
            input_filename = Path(input_filename.strip().replace("\x00", "")).name
            resolved_input = get_safe_path(input_filename)
            if not Path(resolved_input).is_file():
                raise FileNotFoundError(f"File not found: {input_filename}")
        
            # ----------------------------------------------------------------------
            # Resolve output location
            # ----------------------------------------------------------------------
            if output_filename is not None:
                output_filename = Path(output_filename.strip().replace("\x00", "")).name
                resolved_output = get_safe_path(output_filename)
            else:
                # temporary file with .png suffix
                temp_path = temp_output_path("aspose_diagram_result", ".png")
                resolved_output = str(temp_path)  # Aspose expects a plain str
                output_filename = Path(resolved_output).name
        
            # ensure output directory exists
            Path(resolved_output).parent.mkdir(parents=True, exist_ok=True)
        
            # ----------------------------------------------------------------------
            # Validate page_index
            # ----------------------------------------------------------------------
            if page_index < 0:
                raise ValueError("page_index must be non‑negative")
        
            # ----------------------------------------------------------------------
            # Aspose Diagram processing
            # ----------------------------------------------------------------------
            try:
                # lazy import as required by the rules
                from aspose.diagram import Diagram, SaveFileFormat, saving
        
                logger.debug(
                    "Loading diagram %s, exporting page %d to %s",
                    resolved_input,
                    page_index,
                    resolved_output,
                )
                diagram = Diagram(resolved_input)
        
                opts = saving.ImageSaveOptions(SaveFileFormat.PNG)
                opts.page_index = page_index
        
                diagram.save(resolved_output, opts)
        
                logger.info("Page %d exported to PNG: %s", page_index, resolved_output)
        
                return {
                    "status": "success",
                    "message": f"Page {page_index} exported to PNG.",
                    "output_filename": output_filename,
                }
        
            except Exception as exc:  # pragma: no cover
                logger.error("Failed to export page %d: %s", page_index, exc)
                return {
                    "status": "error",
                    "message": str(exc),
                    "output_filename": output_filename,
                }

        @mcp.tool()
        async def diagram_list_shapes(
            input_filename: str,
            page_index: int | None = None,
        ) -> dict:
            """
            List shapes on a Visio page.
        
            IMPORTANT: All *_filename parameters accept ONLY the bare filename (e.g. 'scan.vsdx') —
            no path, no directory, no drive letter, no slash.
            The file MUST already exist in the server's ASPOSE_FILES_PATH folder.
            Do NOT ask the user to upload a file — files are pre‑placed in that folder.
            Output files are written to the same folder; returned output_filename is the bare name only.
        
            Args:
                input_filename: bare filename of the Visio file located in ASPOSE_FILES_PATH.
                page_index: zero‑based index of the page to inspect; if omitted the first page (0) is used.
        
            Returns:
                dict: At minimum contains:
                    - "status": "success" or "error"
                    - "message": description of the result
                    - "shapes": list of dicts with each shape's "name" and "text" (present only on success)
                    - "input_filename": the bare name of the processed file
        
            Raises:
                FileNotFoundError: if the specified Visio file does not exist.
                IndexError: if the provided page_index is out of range.
                Exception: any unexpected error from Aspose.Diagram.
        
            Example:
                result = await diagram_list_shapes("example.vsdx", page_index=2)
                # result["shapes"] -> [{'name': 'Rectangle', 'text': 'Hello'}]
            """
            import logging
            from pathlib import Path
            from mcp_server.path_utils import get_safe_path
        
            logger = logging.getLogger(__name__)
        
            # ---- Validate and resolve input file ----
            input_filename = Path(input_filename.strip().replace('\x00', '')).name
            resolved_input = get_safe_path(input_filename)
            if not Path(resolved_input).is_file():
                raise FileNotFoundError(f"File not found: {input_filename}")
        
            # ---- Default page index ----
            if page_index is None:
                page_index = 0
        
            try:
                # Lazy import of Aspose.Diagram
                import aspose.diagram as aspose_diagram
        
                # Load the Visio document
                diagram = aspose_diagram.Diagram(str(resolved_input))
        
                # Validate page index using the correct page count property
                total_pages = diagram.pages.count
                if page_index < 0 or page_index >= total_pages:
                    raise IndexError(
                        f"page_index {page_index} is out of range (0‑{total_pages - 1})"
                    )
        
                # Access the requested page
                page = diagram.pages[page_index]
        
                # Retrieve shapes
                shape_infos = []
                for shape in page.shapes:
                    # Aspose.Diagram Shape objects expose .name and .text properties
                    shape_name = getattr(shape, "name", "")
                    shape_text = getattr(shape, "text", "")
                    shape_infos.append({"name": shape_name, "text": shape_text})
        
                return {
                    "status": "success",
                    "message": f"Found {len(shape_infos)} shape(s) on page {page_index}.",
                    "shapes": shape_infos,
                    "input_filename": input_filename,
                }
        
            except Exception as exc:  # pragma: no cover
                logger.exception("Error listing shapes from Visio file.")
                return {"status": "error", "message": str(exc)}

        @mcp.tool()
        async def diagram_detect_format(input_filename: str) -> dict:
            """
            Detect the file format of a diagram file stored on the server.
        
            IMPORTANT:
            * All *_filename parameters accept ONLY the bare filename (e.g. 'scan.vsdx') — no path, no directory, no drive letter, no slash.
            * The file MUST already exist in the server's ASPOSE_FILES_PATH folder before calling this tool.
            * Do NOT ask the user to upload a file — files are pre‑placed in the server folder by the user.
            * The output file is also written to the ASPOSE_FILES_PATH folder; the returned output_filename is the bare name only.
        
            Args:
                input_filename: Bare filename only, e.g. 'diagram.vsdx' — must already exist in ASPOSE_FILES_PATH.
        
            Returns:
                dict: A dictionary containing at minimum:
                    - "status": "success" or "error".
                    - "message": Human‑readable description.
                    - "format": Detected format type string (present only on success).
        
            Raises:
                FileNotFoundError: If the specified input file does not exist.
                Exception: Any unexpected error raised by Aspose.Diagram.
        
            Example:
                >>> result = await diagram_detect_format("example.vsdx")
                >>> result
                {'status': 'success', 'message': 'Format detected', 'format': 'Vsdx'}
            """
            # ----------------------------------------------------------------------
            # Resolve and validate the input file (must be a bare filename)
            # ----------------------------------------------------------------------
            from pathlib import Path
            from mcp_server.path_utils import get_safe_path, temp_output_path
            import logging
        
            logger = logging.getLogger(__name__)
        
            # Sanitize the filename and resolve the absolute safe path
            input_filename = Path(input_filename.strip().replace('\x00', '')).name
            resolved_input = get_safe_path(input_filename)
        
            if not Path(resolved_input).is_file():
                raise FileNotFoundError(f"File not found: {input_filename}")
        
            # ----------------------------------------------------------------------
            # Perform format detection using Aspose.Diagram
            # ----------------------------------------------------------------------
            try:
                import aspose.diagram as diagram
        
                info = diagram.FileFormatUtil.detect_file_format(resolved_input)
                format_str = str(info.file_format_type)
        
                logger.debug(
                    "Detected format for file %s (resolved: %s): %s",
                    input_filename,
                    resolved_input,
                    format_str,
                )
        
                return {
                    "status": "success",
                    "message": "Format detected",
                    "format": format_str,
                }
        
            except Exception as exc:  # pragma: no cover
                logger.error(
                    "Error detecting format for file %s (resolved: %s): %s",
                    input_filename,
                    resolved_input,
                    exc,
                )
                return {"status": "error", "message": str(exc)}
