# Auto-generated by Aspose MCP Builder — do not edit manually.
# Product: Aspose.Email for Python via .NET  Package: aspose-email-for-python-via-net
from __future__ import annotations

import logging
import tempfile
from pathlib import Path

from mcp_server.plugin import AsposePlugin
from mcp_server.path_utils import get_safe_path, temp_output_path, apply_license_for, platform_hint

logger = logging.getLogger(__name__)




# Post-generation fixup: email uses ASPOSE_INPUT_DIR, not ASPOSE_INPUT_DIR.
def get_safe_path(filename: str) -> str:  # type: ignore[override]
    """Resolve a bare filename against ASPOSE_INPUT_DIR (email path model)."""
    import os as _os
    from pathlib import Path as _Path
    _d = _os.environ.get('ASPOSE_INPUT_DIR', '').strip()
    if not _d:
        raise FileNotFoundError(
            f'File not found: {filename} — ASPOSE_INPUT_DIR environment variable is not configured.'
        )
    _resolved = str(_Path(_d) / _Path(filename).name)
    return _resolved
class EmailPlugin(AsposePlugin):
    product_name = "email"
    pypi_package = "aspose-email-for-python-via-net"
    min_version = "24.1.0"

    def health_check(self) -> bool:
        """Check that the Aspose EMAIL package is importable.

        Args:
            None

        Returns:
            True if the package imports without error, False otherwise.

        Raises:
            None. Import errors are caught and return False.

        Example:
            >>> plugin = EmailPlugin()
            >>> isinstance(plugin.health_check(), bool)
            True
        """
        try:
            import aspose.email  # noqa: F401, PLC0415
            return True
        except Exception:
            return False

    def get_tool_manifest(self) -> list[dict[str, object]]:
        """Return metadata for all registered tools.

        Args:
            None

        Returns:
            List of dicts each with keys: name, description, params, returns.

        Raises:
            None.

        Example:
            >>> plugin = EmailPlugin()
            >>> manifest = plugin.get_tool_manifest()
            >>> len(manifest) >= 15
            True
        """
        return [
            {"name": 'email_read_message', "description": 'Loads an email file and returns basic properties such as subject, from, to, body and attachment count.', "params": [{"name": 'input_filename', "type": 'str', "required": True, "description": ""}], "returns": "dict"},
            {"name": 'email_create_message', "description": 'Creates a new email message with the supplied fields and saves it as an EML file.', "params": [{"name": 'subject', "type": 'str', "required": True, "description": ""}, {"name": 'from_address', "type": 'str', "required": True, "description": ""}, {"name": 'to_addresses', "type": 'list[str]', "required": True, "description": ""}, {"name": 'body', "type": 'str', "required": True, "description": ""}, {"name": 'output_filename', "type": 'str | None', "required": False, "description": ""}], "returns": "dict"},
            {"name": 'email_convert_to_msg', "description": 'Converts an email file to Outlook MSG (Unicode) format.', "params": [{"name": 'input_filename', "type": 'str', "required": True, "description": ""}, {"name": 'output_filename', "type": 'str | None', "required": False, "description": ""}], "returns": "dict"},
            {"name": 'email_convert_to_eml', "description": 'Converts an email file to EML (RFC 822) format.', "params": [{"name": 'input_filename', "type": 'str', "required": True, "description": ""}, {"name": 'output_filename', "type": 'str | None', "required": False, "description": ""}], "returns": "dict"},
            {"name": 'email_convert_to_mhtml', "description": 'Converts an email file to MHTML format.', "params": [{"name": 'input_filename', "type": 'str', "required": True, "description": ""}, {"name": 'output_filename', "type": 'str | None', "required": False, "description": ""}], "returns": "dict"},
            {"name": 'email_convert_to_html', "description": 'Converts an email file to HTML format.', "params": [{"name": 'input_filename', "type": 'str', "required": True, "description": ""}, {"name": 'output_filename', "type": 'str | None', "required": False, "description": ""}], "returns": "dict"},
            {"name": 'email_extract_attachments', "description": 'Extracts all attachments from an email and saves them to the ASPOSE_OUTPUT_DIR directory.', "params": [{"name": 'input_filename', "type": 'str', "required": True, "description": ""}], "returns": "dict"},
            {"name": 'email_list_headers', "description": 'Lists all MIME headers of an email as a dictionary.', "params": [{"name": 'input_filename', "type": 'str', "required": True, "description": ""}], "returns": "dict"},
            {"name": 'email_read_pst_folders', "description": 'Opens a PST file and returns the display name and message count of each top‑level folder.', "params": [{"name": 'input_filename', "type": 'str', "required": True, "description": ""}], "returns": "dict"},
            {"name": 'email_extract_from_pst', "description": 'Extracts all messages from a specified PST folder (or the root folder) and saves them as EML files.', "params": [{"name": 'input_filename', "type": 'str', "required": True, "description": ""}, {"name": 'folder_name', "type": 'str | None', "required": False, "description": ""}, {"name": 'output_filename', "type": 'str | None', "required": False, "description": ""}], "returns": "dict"},
            {"name": 'email_read_mbox', "description": 'Iterates through an MBOX archive and returns the subjects of contained messages.', "params": [{"name": 'input_filename', "type": 'str', "required": True, "description": ""}, {"name": 'max_count', "type": 'int | None', "required": False, "description": ""}], "returns": "dict"},
            {"name": 'email_detect_format', "description": 'Detects the file format of an email file (EML, MSG, MHTML, HTML, etc.).', "params": [{"name": 'input_filename', "type": 'str', "required": True, "description": ""}], "returns": "dict"},
            {"name": 'email_save_message', "description": 'Loads an email file and saves it using the specified SaveOptions preset.', "params": [{"name": 'input_filename', "type": 'str', "required": True, "description": ""}, {"name": 'output_filename', "type": 'str | None', "required": True, "description": ""}, {"name": 'save_option', "type": 'str', "required": True, "description": ""}], "returns": "dict"},
            {"name": 'email_folder_get_subfolders', "description": 'Returns the list of sub‑folders for a given folder inside a PST file.', "params": [{"name": 'input_filename', "type": 'str', "required": True, "description": ""}, {"name": 'folder_name', "type": 'str | None', "required": False, "description": ""}], "returns": "dict"},
            {"name": 'email_pst_get_message_count', "description": 'Counts the number of messages in a specified PST folder.', "params": [{"name": 'input_filename', "type": 'str', "required": True, "description": ""}, {"name": 'folder_name', "type": 'str | None', "required": False, "description": ""}], "returns": "dict"},
            {"name": 'email_pst_list_message_subjects', "description": 'Lists the subjects of all messages in a specified PST folder.', "params": [{"name": 'input_filename', "type": 'str', "required": True, "description": ""}, {"name": 'folder_name', "type": 'str | None', "required": False, "description": ""}], "returns": "dict"},
            {"name": 'email_mbox_read_next_message', "description": 'Reads the next message from an MBOX file and returns its subject.', "params": [{"name": 'input_filename', "type": 'str', "required": True, "description": ""}], "returns": "dict"},
            {"name": 'email_mbox_dispose', "description": 'Releases the file handle associated with an opened MBOX reader.', "params": [{"name": 'input_filename', "type": 'str', "required": True, "description": ""}], "returns": "dict"}
        ]

    def register_tools(self, mcp: "FastMCP") -> None:
        """Register all EMAIL tools with the FastMCP instance.

        Args:
            mcp: FastMCP server instance to register tools on.

        Returns:
            None.

        Raises:
            None.

        Example:
            >>> from mcp.server.fastmcp import FastMCP
            >>> mcp = FastMCP("test")
            >>> EmailPlugin().register_tools(mcp)
        """
        logger.debug("%s plugin registering tools. Platform: %s", "EMAIL", platform_hint())
        apply_license_for("aspose.email")
        @mcp.tool()
        async def email_read_message(input_filename: str) -> dict:
            """
            Read an email file and return its main properties.
        
            IMPORTANT: All *_filename parameters accept ONLY the bare filename (e.g. 'scan.jpg') —
            no path, no directory, no drive letter, no slash.
            The file MUST already exist in the server's ASPOSE_INPUT_DIR folder.
            Do NOT ask the user to upload a file — files are pre‑placed in that folder.
            Output files are written to the same folder; returned output_filename is the bare name only.
        
            Args:
                input_filename: bare filename only, e.g. 'message.eml' — must already exist in ASPOSE_INPUT_DIR.
        
            Returns:
                dict: {
                    "status": "success" | "error",
                    "message": str,
                    "subject": str,
                    "from_address": str,
                    "to": list[str],
                    "cc": list[str],
                    "body": str,
                    "html_body": str,
                    "attachment_count": int,
                    "date": str
                }
        
            Raises:
                FileNotFoundError: If the specified email file does not exist in the allowed folder.
        
            Example:
                >>> result = await email_read_message("sample.eml")
                # result == {
                #     "status": "success",
                #     "message": "Email read successfully.",
                #     "subject": "...",
                #     ...
                # }
            """
            # ----------------------------------------------------------------------
            # Resolve input file inside ASPOSE_INPUT_DIR (email‑specific handling)
            # ----------------------------------------------------------------------
            from pathlib import Path
            from mcp_server.path_utils import get_safe_path
            import logging
        
            logger = logging.getLogger(__name__)
        
            # sanitize filename
            input_filename = Path(input_filename.strip().replace('\x00', '')).name
        
            # obtain a safe absolute path within the allowed folder
            resolved_input = get_safe_path(input_filename)
        
            if not Path(resolved_input).is_file():
                raise FileNotFoundError(f"File not found: {input_filename}")
        
            try:
                # ------------------------------------------------------------------
                # Load the email using Aspose.Email
                # ------------------------------------------------------------------
                import aspose.email as ae
        
                msg = ae.MailMessage.load(resolved_input)
        
                # Extract required properties
                subject = msg.subject or ""
                from_address = str(msg.from_address) if msg.from_address else ""
                to = [str(addr) for addr in msg.to] if hasattr(msg, "to") else []
                cc = [str(addr) for addr in msg.cc] if hasattr(msg, "cc") else []
                body = msg.body or ""
                html_body = msg.html_body or ""
                attachment_count = len(msg.attachments) if hasattr(msg, "attachments") else 0
                date = str(msg.date) if hasattr(msg, "date") and msg.date else ""
        
                logger.debug(
                    "Email loaded: subject=%s, from=%s, to=%s, cc=%s, attachments=%d",
                    subject,
                    from_address,
                    to,
                    cc,
                    attachment_count,
                )
        
                return {
                    "status": "success",
                    "message": "Email read successfully.",
                    "subject": subject,
                    "from_address": from_address,
                    "to": to,
                    "cc": cc,
                    "body": body,
                    "html_body": html_body,
                    "attachment_count": attachment_count,
                    "date": date,
                }
        
            except Exception as exc:  # pragma: no cover
                logger.exception("Failed to read email %s", input_filename)
                return {"status": "error", "message": str(exc)}

        @mcp.tool()
        async def email_create_message(
            subject: str,
            from_address: str,
            to_addresses: list[str],
            body: str,
            output_filename: str | None = None,
        ) -> dict:
            """
            Create a new email message and save it as an EML file.
        
            IMPORTANT:
            - All *_filename parameters accept ONLY the bare filename (e.g. 'scan.jpg') — no path, no directory, no drive letter, no slash.
            - The file MUST already exist in the server's ASPOSE_INPUT_DIR folder before calling this tool.
            - Do NOT ask the user to upload a file — files are pre-placed in the server folder by the user.
            - Output files are written to ASPOSE_OUTPUT_DIR (falls back to ASPOSE_INPUT_DIR if unset).
        
            Args:
                subject (str): Subject line of the new email.
                from_address (str): Sender email address.
                to_addresses (list[str]): List of recipient email addresses.
                body (str): Plain‑text body of the email.
                output_filename (str | None, optional): Name of the output EML file; defaults to "new_email.eml".
        
            Returns:
                dict: {"status": "success"|"error", "message": str, "output_filename": str}
        
            Raises:
                ValueError: If any email address is invalid.
                Exception: For unexpected errors during message creation or saving.
        
            Example:
                result = await email_create_message(
                    subject="Hello",
                    from_address="sender@example.com",
                    to_addresses=["recipient@example.com"],
                    body="Test body",
                    output_filename="my_email.eml"
                )
            """
            import os
            import logging
            from pathlib import Path
        
            logger = logging.getLogger(__name__)
        
            # Simple email validation
            def _is_valid_email(addr: str) -> bool:
                return "@" in addr and "." in addr.split("@")[-1]
        
            if not _is_valid_email(from_address):
                raise ValueError(f"Invalid sender email address: {from_address}")
            for addr in to_addresses:
                if not _is_valid_email(addr):
                    raise ValueError(f"Invalid recipient email address: {addr}")
        
            # Resolve output directory
            _out_dir = os.environ.get("ASPOSE_OUTPUT_DIR", "").strip() or os.environ.get("ASPOSE_INPUT_DIR", "").strip()
            if not _out_dir:
                raise FileNotFoundError(
                    "Neither ASPOSE_OUTPUT_DIR nor ASPOSE_INPUT_DIR environment variables are configured."
                )
            Path(_out_dir).mkdir(parents=True, exist_ok=True)
        
            if output_filename is not None:
                output_filename = Path(output_filename.strip().replace("\x00", "")).name
            else:
                output_filename = "new_email.eml"
        
            resolved_output = str(Path(_out_dir) / output_filename)
        
            try:
                import aspose.email as ae
        
                # Build the message
                msg = ae.MailMessage()
                msg.subject = subject
                msg.from_address = ae.MailAddress(from_address)
                for addr in to_addresses:
                    msg.to.append(ae.MailAddress(str(addr)))
                msg.body = body
        
                # Save as EML
                msg.save(resolved_output, ae.SaveOptions.default_eml)
        
                logger.info("Email saved to %s", resolved_output)
                return {"status": "success", "message": "Email created successfully.", "output_filename": output_filename}
            except Exception as exc:  # pragma: no cover
                logger.exception("Failed to create email")
                return {"status": "error", "message": str(exc), "output_filename": output_filename}

        @mcp.tool()
        async def email_convert_to_msg(
            input_filename: str,
            output_filename: str | None = None,
        ) -> dict:
            """
            Convert an email file (EML, MHTML, HTML, etc.) to MSG format.
        
            IMPORTANT:
            * All *_filename parameters accept ONLY the bare filename (e.g. 'message.eml') — no path, no directory, no drive letter, no slash.
            * The file MUST already exist in the server's ASPOSE_INPUT_DIR folder before calling this tool.
            * Do NOT ask the user to upload a file — files are pre‑placed in the server folder by the user.
            * Output files are written to ASPOSE_OUTPUT_DIR (falls back to ASPOSE_INPUT_DIR if unset).
        
            Args:
                input_filename: Bare filename of the source email (e.g. 'email.eml') — must already exist in ASPOSE_INPUT_DIR.
                output_filename: Optional bare filename for the resulting MSG file. If omitted, the output name is derived
                                 from the input filename with a .msg extension.
        
            Returns:
                dict: {
                    "status": "success" | "error",
                    "message": str,
                    "output_filename": str   # bare name of the written MSG file
                }
        
            Raises:
                FileNotFoundError: If the input file cannot be located.
                PermissionError:   If the output directory cannot be written to.
                Exception:         For any unexpected Aspose errors.
        
            Example:
                >>> result = await email_convert_to_msg("sample.eml", "sample_converted.msg")
                >>> result["status"]
                'success'
            """
            import os
            import logging
            from pathlib import Path
        
            logger = logging.getLogger(__name__)
        
            # ---------- Resolve input ----------
            # Sanitize and keep only the filename
            input_filename = Path(input_filename.strip().replace('\x00', '')).name
            _input_dir = os.environ.get("ASPOSE_INPUT_DIR", "").strip()
            if not _input_dir:
                raise FileNotFoundError(
                    f"File not found: {input_filename} — ASPOSE_INPUT_DIR environment variable is not configured."
                )
            resolved_input = str(Path(_input_dir) / input_filename)
            if not Path(resolved_input).is_file():
                raise FileNotFoundError(f"File not found: {input_filename} (ASPOSE_INPUT_DIR={_input_dir})")
        
            # ---------- Resolve output ----------
            _out_dir = os.environ.get("ASPOSE_OUTPUT_DIR", "").strip() or os.environ.get("ASPOSE_INPUT_DIR", "").strip()
            Path(_out_dir).mkdir(parents=True, exist_ok=True)
        
            if output_filename is not None:
                output_filename = Path(output_filename.strip().replace('\x00', '')).name
                output_basename = output_filename
            else:
                output_basename = Path(input_filename).stem + ".msg"
        
            resolved_output = str(Path(_out_dir) / output_basename)
        
            try:
                # ---------- Perform conversion ----------
                import aspose.email as ae
        
                msg = ae.MailMessage.load(resolved_input)  # no context manager needed
                msg.save(resolved_output, ae.SaveOptions.default_msg_unicode)
        
                logger.info("Email converted: %s -> %s", resolved_input, resolved_output)
        
                return {
                    "status": "success",
                    "message": f"Converted '{input_filename}' to MSG successfully.",
                    "output_filename": output_basename,
                }
        
            except Exception as exc:  # pragma: no cover
                logger.exception("Failed to convert email to MSG")
                return {
                    "status": "error",
                    "message": str(exc),
                    "output_filename": output_basename,
                }

        @mcp.tool()
        async def email_convert_to_eml(
            input_filename: str,
            output_filename: str | None = None,
        ) -> dict:
            """
            Convert an email file from the server's input folder to EML format.
        
            IMPORTANT:
            * All *_filename parameters accept ONLY the bare filename (e.g. 'scan.jpg') — no path, no directory, no drive letter, no slash.
            * The file MUST already exist in the server's ASPOSE_INPUT_DIR folder before calling this tool.
            * Do NOT ask the user to upload a file — files are pre‑placed in the server folder by the user.
            * Output files are written to ASPOSE_OUTPUT_DIR (falls back to ASPOSE_INPUT_DIR if unset).
        
            Args:
                input_filename: Bare filename of the source email file (e.g. 'message.msg').
                output_filename: Optional bare filename for the resulting EML file. If omitted,
                                 the output name is derived from the input filename with a .eml extension.
        
            Returns:
                dict: {
                    "status": "success" | "error",
                    "message": str,
                    "output_filename": str   # bare name of the written EML file (present only on success)
                }
        
            Raises:
                FileNotFoundError: If the input file cannot be located in ASPOSE_INPUT_DIR.
                Exception: For any unexpected errors during conversion.
        
            Example:
                result = await email_convert_to_eml("example.msg", "example.eml")
                # result -> {"status": "success", "message": "Converted to EML.", "output_filename": "example.eml"}
            """
            import os
            import logging
            from pathlib import Path
        
            logger = logging.getLogger(__name__)
        
            # Resolve input file in ASPOSE_INPUT_DIR
            input_filename = Path(input_filename.strip().replace('\x00', '')).name
            _input_dir = os.environ.get("ASPOSE_INPUT_DIR", "").strip()
            if not _input_dir:
                raise FileNotFoundError(
                    f"File not found: {input_filename} — ASPOSE_INPUT_DIR environment variable is not configured."
                )
            resolved_input = str(Path(_input_dir) / input_filename)
            if not Path(resolved_input).is_file():
                raise FileNotFoundError(f"File not found: {input_filename} (ASPOSE_INPUT_DIR={_input_dir})")
        
            # Resolve output location in ASPOSE_OUTPUT_DIR (fallback to ASPOSE_INPUT_DIR)
            _out_dir = os.environ.get("ASPOSE_OUTPUT_DIR", "").strip() or os.environ.get("ASPOSE_INPUT_DIR", "").strip()
            Path(_out_dir).mkdir(parents=True, exist_ok=True)
        
            if output_filename is not None:
                output_filename = Path(output_filename.strip().replace('\x00', '')).name
                resolved_output = str(Path(_out_dir) / output_filename)
                output_basename = output_filename
            else:
                output_basename = Path(input_filename).stem + ".eml"
                resolved_output = str(Path(_out_dir) / output_basename)
        
            try:
                import aspose.email as ae
        
                # Load the source email and save as EML
                msg = ae.MailMessage.load(resolved_input)
                msg.save(resolved_output, ae.SaveOptions.default_eml)
        
                logger.info("Converted %s to EML as %s", resolved_input, resolved_output)
                return {
                    "status": "success",
                    "message": "Converted to EML.",
                    "output_filename": output_basename,
                }
            except Exception as exc:  # pragma: no cover
                logger.error("Failed to convert email to EML: %s", exc)
                return {"status": "error", "message": str(exc)}

        @mcp.tool()
        async def email_convert_to_mhtml(
            input_filename: str,
            output_filename: str | None = None,
        ) -> dict:
            """
            Convert an email file stored on the server to MHTML format.
        
            IMPORTANT:
            * All *_filename parameters accept ONLY the bare filename (e.g. 'scan.jpg') — no path, no directory, no drive letter, no slash.
            * The file MUST already exist in the server's ASPOSE_INPUT_DIR folder before calling this tool.
            * Do NOT ask the user to upload a file — files are pre‑placed in the server folder by the user.
            * Output files are written to ASPOSE_OUTPUT_DIR (falls back to ASPOSE_INPUT_DIR if unset).
        
            Args:
                input_filename: Bare filename of the source email (e.g. 'message.msg'). Must exist in ASPOSE_INPUT_DIR.
                output_filename: Optional bare filename for the resulting MHTML file. If omitted, the output name is
                                 the input stem with a `.mhtml` extension.
        
            Returns:
                dict: {
                    "status": "success" | "error",
                    "message": str,
                    "output_filename": str   # bare name of the written MHTML file (only on success)
                }
        
            Raises:
                FileNotFoundError: If the input file does not exist in ASPOSE_INPUT_DIR.
                Exception: For any unexpected errors during processing.
        
            Example:
                result = await email_convert_to_mhtml("example.msg")
                # result -> {"status":"success","message":"Converted to MHTML","output_filename":"example.mhtml"}
            """
            # ------------------------------------------------------------------
            # Resolve input file (ASPOSE_INPUT_DIR)
            # ------------------------------------------------------------------
            from pathlib import Path
            import os
            import logging
        
            logger = logging.getLogger(__name__)
        
            # sanitize input filename
            input_filename = Path(input_filename.strip().replace('\x00', '')).name
            _input_dir = os.environ.get("ASPOSE_INPUT_DIR", "").strip()
            if not _input_dir:
                raise FileNotFoundError(
                    f"File not found: {input_filename} — ASPOSE_INPUT_DIR environment variable is not configured."
                )
            resolved_input = str(Path(_input_dir) / input_filename)
            if not Path(resolved_input).is_file():
                raise FileNotFoundError(f"File not found: {input_filename} (ASPOSE_INPUT_DIR={_input_dir})")
        
            # ------------------------------------------------------------------
            # Resolve output file (ASPOSE_OUTPUT_DIR)
            # ------------------------------------------------------------------
            _out_dir = os.environ.get("ASPOSE_OUTPUT_DIR", "").strip() or _input_dir
            Path(_out_dir).mkdir(parents=True, exist_ok=True)
        
            if output_filename is not None:
                output_filename = Path(output_filename.strip().replace('\x00', '')).name
                resolved_output = str(Path(_out_dir) / output_filename)
                output_basename = output_filename
            else:
                output_basename = Path(input_filename).stem + ".mhtml"
                resolved_output = str(Path(_out_dir) / output_basename)
        
            # ------------------------------------------------------------------
            # Perform conversion using Aspose.Email
            # ------------------------------------------------------------------
            try:
                import aspose.email as ae
        
                # Load the source email
                msg = ae.MailMessage.load(resolved_input)
        
                # Save as MHTML
                msg.save(resolved_output, ae.SaveOptions.default_mhtml)
        
                logger.info(
                    "Converted email '%s' to MHTML '%s'.",
                    input_filename,
                    output_basename,
                )
                return {
                    "status": "success",
                    "message": "Converted to MHTML",
                    "output_filename": output_basename,
                }
            except Exception as exc:  # pragma: no cover
                logger.error("Failed to convert email to MHTML: %s", exc)
                return {"status": "error", "message": str(exc)}

        @mcp.tool()
        async def email_convert_to_html(
            input_filename: str,
            output_filename: str | None = None,
        ) -> dict:
            """
            Convert an email file stored in ASPOSE_INPUT_DIR to an HTML document.
        
            IMPORTANT:
            * All *_filename parameters accept ONLY the bare filename (e.g. 'message.eml') — no path, no directory, no drive letter, no slash.
            * The file MUST already exist in the server's ASPOSE_INPUT_DIR folder before calling this tool.
            * Do NOT ask the user to upload a file — files are pre‑placed in the server folder by the user.
            * Output files are written to ASPOSE_OUTPUT_DIR (falls back to ASPOSE_INPUT_DIR if unset).
        
            Args:
                input_filename: Bare filename of the source email (e.g. 'email.msg'). Must exist in ASPOSE_INPUT_DIR.
                output_filename: Optional bare filename for the resulting HTML file. If omitted, the output name is derived
                                 from the input filename with a .html extension.
        
            Returns:
                dict: {
                    "status": "success" | "error",
                    "message": description of the operation or error,
                    "output_filename": bare name of the written HTML file (present only on success)
                }
        
            Raises:
                FileNotFoundError: If the input file cannot be located in ASPOSE_INPUT_DIR.
                Exception: Propagates any Aspose‑Email errors as an error status in the return dict.
        
            Example:
                >>> result = await email_convert_to_html("sample.msg")
                >>> result["status"]
                'success'
                >>> result["output_filename"]
                'sample.html'
            """
            # ----------------------------------------------------------------------
            # Resolve input file (ASPOSE_INPUT_DIR)
            # ----------------------------------------------------------------------
            from pathlib import Path
            import os
            import logging
        
            logger = logging.getLogger(__name__)
        
            # sanitize filename
            input_filename = Path(input_filename.strip().replace("\x00", "")).name
        
            _input_dir = os.environ.get("ASPOSE_INPUT_DIR", "").strip()
            if not _input_dir:
                raise FileNotFoundError(
                    "ASPOSE_INPUT_DIR environment variable is not configured."
                )
            resolved_input = str(Path(_input_dir) / input_filename)
            if not Path(resolved_input).is_file():
                raise FileNotFoundError(
                    f"File not found: {input_filename} (ASPOSE_INPUT_DIR={_input_dir})"
                )
        
            # ----------------------------------------------------------------------
            # Resolve output file (ASPOSE_OUTPUT_DIR)
            # ----------------------------------------------------------------------
            _out_dir = (
                os.environ.get("ASPOSE_OUTPUT_DIR", "").strip()
                or os.environ.get("ASPOSE_INPUT_DIR", "").strip()
            )
            Path(_out_dir).mkdir(parents=True, exist_ok=True)
        
            if output_filename is not None:
                output_filename = Path(output_filename.strip().replace("\x00", "")).name
                output_basename = output_filename
                resolved_output = str(Path(_out_dir) / output_filename)
            else:
                output_basename = Path(input_filename).stem + ".html"
                resolved_output = str(Path(_out_dir) / output_basename)
        
            # ----------------------------------------------------------------------
            # Perform conversion using Aspose.Email
            # ----------------------------------------------------------------------
            try:
                import aspose.email as ae
        
                msg = ae.MailMessage.load(resolved_input)  # no context manager needed
                msg.save(resolved_output, ae.SaveOptions.default_html)
        
                return {
                    "status": "success",
                    "message": f"Converted '{input_filename}' to HTML.",
                    "output_filename": output_basename,
                }
            except Exception as exc:  # pragma: no cover
                logger.exception("Failed to convert email to HTML")
                return {"status": "error", "message": str(exc)}

        @mcp.tool()
        async def email_extract_attachments(input_filename: str) -> dict:
            """
            Extract all attachments from an email file stored on the server.
        
            IMPORTANT:
            * All *_filename parameters accept ONLY the bare filename (e.g. 'message.eml') — no path, no directory, no drive letter, no slash.
            * The file MUST already exist in the server's ASPOSE_INPUT_DIR folder before calling this tool.
            * Do NOT ask the user to upload a file — files are pre‑placed in the server folder by the user.
            * Output files are written to ASPOSE_OUTPUT_DIR (falls back to ASPOSE_INPUT_DIR if unset).
        
            Args:
                input_filename: bare filename of the email file containing attachments, e.g. 'mail.eml'.
        
            Returns:
                dict: {
                    "status": "success" | "error",
                    "message": str,
                    "saved_files": list[str],          # names of the extracted attachment files
                    "output_filename": str            # empty because multiple files are written
                }
        
            Raises:
                FileNotFoundError: if the input email file cannot be located.
                PermissionError: if the server cannot write to the output directory.
                Exception: for any unexpected Aspose errors.
        
            Example:
                result = await email_extract_attachments("example.eml")
                # result["saved_files"] might be ["photo.jpg", "doc.pdf"]
            """
            import os
            import logging
            from pathlib import Path
        
            logger = logging.getLogger(__name__)
        
            # ---------- Resolve input ----------
            input_filename = Path(input_filename.strip().replace('\x00', '')).name
            _input_dir = os.environ.get("ASPOSE_INPUT_DIR", "").strip()
            if not _input_dir:
                raise FileNotFoundError(
                    f"File not found: {input_filename} — ASPOSE_INPUT_DIR environment variable is not configured."
                )
            resolved_input = str(Path(_input_dir) / input_filename)
            if not Path(resolved_input).is_file():
                raise FileNotFoundError(f"File not found: {input_filename} (ASPOSE_INPUT_DIR={_input_dir})")
        
            # ---------- Resolve output directory ----------
            _out_dir = os.environ.get("ASPOSE_OUTPUT_DIR", "").strip() or os.environ.get("ASPOSE_INPUT_DIR", "").strip()
            try:
                Path(_out_dir).mkdir(parents=True, exist_ok=True)
            except Exception as exc:
                logger.error("Failed to create output directory: %s", exc)
                return {"status": "error", "message": f"Cannot create output directory: {exc}", "saved_files": [], "output_filename": ""}
        
            # ---------- Extract attachments ----------
            try:
                import aspose.email as ae  # lazy import as required
                msg = ae.MailMessage.load(resolved_input)  # load the email
        
                saved_files = []
                for att in msg.attachments:
                    att_path = str(Path(_out_dir) / att.name)
                    att.save(att_path)
                    saved_files.append(att.name)
        
                if not saved_files:
                    return {
                        "status": "success",
                        "message": "No attachments found in the email.",
                        "saved_files": [],
                        "output_filename": ""
                    }
        
                return {
                    "status": "success",
                    "message": f"Extracted {len(saved_files)} attachment(s).",
                    "saved_files": saved_files,
                    "output_filename": ""  # multiple files; placeholder per spec
                }
        
            except Exception as exc:  # catch Aspose and any other errors
                logger.exception("Error extracting attachments from %s", input_filename)
                return {"status": "error", "message": str(exc), "saved_files": [], "output_filename": ""}

        @mcp.tool()
        async def email_list_headers(input_filename: str) -> dict:
            """
            Extract all headers from an email file located in the server's ASPOSE_INPUT_DIR.
        
            IMPORTANT: All *_filename parameters accept ONLY the bare filename (e.g. 'scan.jpg') —
            no path, no directory, no drive letter, no slash.
            The file MUST already exist in the server's ASPOSE_INPUT_DIR folder.
            Do NOT ask the user to upload a file — files are pre‑placed in that folder.
            Output files are written to the same folder; returned output_filename is the bare name only.
        
            Args:
                input_filename: Bare filename of the email file to inspect, e.g. 'message.eml'.
        
            Returns:
                dict: A dictionary containing at minimum:
                      - "status": "success" if headers were read, otherwise "error".
                      - "message": Human‑readable description of the result or error.
                      - "headers": Mapping of header names to their values (present only on success).
        
            Raises:
                FileNotFoundError: If the specified email file does not exist.
        
            Example:
                # result = await email_list_headers("sample.eml")
                # if result["status"] == "success":
                #     # result["headers"] contains the extracted headers
                #     pass
            """
            import logging
            from pathlib import Path
            from mcp_server.path_utils import get_safe_path
        
            logger = logging.getLogger(__name__)
        
            # ---- Input file resolution (email‑specific) ----
            input_filename = Path(input_filename.strip().replace('\x00', '')).name
            resolved_input = get_safe_path(input_filename)
        
            if not Path(resolved_input).is_file():
                raise FileNotFoundError(f"File not found: {input_filename}")
        
            try:
                import aspose.email as ae
        
                # Load the email message
                msg = ae.MailMessage.load(resolved_input)
        
                # Extract headers into a plain dict
                headers = {k: msg.headers[k] for k in msg.headers.keys()}
        
                return {
                    "status": "success",
                    "message": "Headers extracted successfully.",
                    "headers": headers,
                }
            except Exception as exc:  # pragma: no cover
                logger.exception("Failed to extract email headers")
                return {"status": "error", "message": str(exc)}

        @mcp.tool()
        async def email_read_pst_folders(input_filename: str) -> dict:
            """
            Read folder names and message counts from a PST file located in the server's ASPOSE_INPUT_DIR.
        
            IMPORTANT: All *_filename parameters accept ONLY the bare filename (e.g. 'archive.pst') —
            no path, no directory, no drive letter, no slash.
            The file MUST already exist in the server's ASPOSE_INPUT_DIR folder.
            Do NOT ask the user to upload a file — files are pre‑placed in that folder.
            Output files are written to the same folder; returned output_filename is the bare name only.
        
            Args:
                input_filename: Bare filename of the PST file, e.g. "archive.pst". The file must already exist in ASPOSE_INPUT_DIR.
        
            Returns:
                dict: A dictionary containing at minimum:
                    - "status": "success" or "error".
                    - "message": Human‑readable description.
                    - "folders": List of dictionaries with "display_name" and "content_count" for each top‑level folder
                                 (present only on success).
        
            Raises:
                FileNotFoundError: If the specified PST file does not exist in ASPOSE_INPUT_DIR.
        
            Example:
                >>> result = await email_read_pst_folders("archive.pst")
                >>> # result => {"status": "success", "message": "...", "folders": [{"display_name": "...", "content_count": ...}, ...]}
            """
            # Imports are kept inside the function as required
            import logging
            from pathlib import Path
            from mcp_server.path_utils import get_safe_path
        
            logger = logging.getLogger(__name__)
        
            # Sanitize filename to ensure only a bare name is used
            input_filename = Path(input_filename.strip().replace('\x00', '')).name
        
            # Resolve the safe path using the server‑provided utility
            resolved_input = get_safe_path(input_filename)
        
            # Verify the file exists before any Aspose import
            if not Path(resolved_input).is_file():
                raise FileNotFoundError(f"File not found: {input_filename}")
        
            try:
                # Lazy import of Aspose.Email after validation
                import aspose.email as ae
        
                logger.debug("Loading PST file from %s", resolved_input)
                pst = ae.storage.pst.PersonalStorage.from_file(resolved_input)
        
                folders_info = []
                for folder in pst.root_folder.get_sub_folders():
                    folders_info.append({
                        "display_name": folder.display_name,
                        "content_count": folder.content_count
                    })
        
                return {
                    "status": "success",
                    "message": f"Read {len(folders_info)} folder(s) from PST file '{input_filename}'.",
                    "folders": folders_info
                }
        
            except Exception as exc:
                logger.exception("Error reading PST file %s", input_filename)
                return {"status": "error", "message": str(exc)}

        @mcp.tool()
        async def email_extract_from_pst(
            input_filename: str,
            folder_name: str | None = None,
            output_filename: str | None = None,
        ) -> dict:
            """
            Extract all messages from a PST file and save them as individual EML files.
        
            IMPORTANT:
            * All *_filename parameters accept ONLY the bare filename (e.g. 'archive.pst') — no path, no directory, no drive letter, no slash.
            * The file MUST already exist in the server's ASPOSE_INPUT_DIR folder before calling this tool.
            * Do NOT ask the user to upload a file — files are pre‑placed in the server folder by the user.
            * Output files are written to ASPOSE_OUTPUT_DIR (falls back to ASPOSE_INPUT_DIR if unset).
        
            Args:
                input_filename: PST file to process (bare filename, must exist in ASPOSE_INPUT_DIR).
                folder_name: Name of the folder inside the PST to extract from; if omitted the root folder is used.
                output_filename: Base name for output files; each message will be saved as <subject>.eml if not provided.
                                 If supplied, files are named `<output_filename>_N.eml` where N is a sequential index.
        
            Returns:
                dict: {
                    "status": "success" | "error",
                    "message": description of the operation,
                    "created_files": list of EML filenames written,
                    "output_filename": str (the supplied base name or empty string)
                }
        
            Raises:
                FileNotFoundError: If the input PST file cannot be located.
                Exception: Propagates unexpected errors from Aspose with an error status.
        
            Example:
                result = await email_extract_from_pst(
                    input_filename="myarchive.pst",
                    folder_name="Inbox",
                    output_filename="msg"
                )
                # result["created_files"] might be ["msg_1.eml", "msg_2.eml", ...]
            """
            import os
            import logging
            from pathlib import Path
        
            # Resolve input file (ASPOSE_INPUT_DIR)
            input_filename = Path(input_filename.strip().replace("\x00", "")).name
            _input_dir = os.environ.get("ASPOSE_INPUT_DIR", "").strip()
            if not _input_dir:
                raise FileNotFoundError(
                    f"File not found: {input_filename} — ASPOSE_INPUT_DIR environment variable is not configured."
                )
            resolved_input = str(Path(_input_dir) / input_filename)
            if not Path(resolved_input).is_file():
                raise FileNotFoundError(
                    f"File not found: {input_filename} (ASPOSE_INPUT_DIR={_input_dir})"
                )
        
            # Resolve output directory (ASPOSE_OUTPUT_DIR fallback to INPUT)
            _out_dir = os.environ.get("ASPOSE_OUTPUT_DIR", "").strip() or os.environ.get("ASPOSE_INPUT_DIR", "").strip()
            Path(_out_dir).mkdir(parents=True, exist_ok=True)
        
            # Normalise optional output base name
            if output_filename is not None:
                output_filename = Path(output_filename.strip().replace("\x00", "")).name
                # Strip any extension – we will add our own .eml suffix
                output_base = output_filename.rsplit(".", 1)[0]
            else:
                output_base = None
        
            created_files: list[str] = []
            logger = logging.getLogger(__name__)
        
            try:
                import aspose.email as ae
        
                # Load PST
                pst = ae.storage.pst.PersonalStorage.from_file(resolved_input)
        
                # Choose folder
                if folder_name:
                    try:
                        folder = pst.root_folder.get_sub_folder(folder_name)
                    except Exception as exc:
                        raise FileNotFoundError(f"Folder '{folder_name}' not found in PST.") from exc
                else:
                    folder = pst.root_folder
        
                # Enumerate messages
                for idx, msg_info in enumerate(folder.enumerate_messages(), start=1):
                    try:
                        msg = pst.extract_message(msg_info)
        
                        # Determine filename
                        if output_base:
                            eml_name = f"{output_base}_{idx}.eml"
                        else:
                            subject = msg_info.subject or f"message_{idx}"
                            # Sanitize subject to a safe filename
                            safe_subject = "".join(
                                c for c in subject if c.isalnum() or c in (" ", "_", "-")
                            ).strip()
                            if not safe_subject:
                                safe_subject = f"message_{idx}"
                            eml_name = f"{safe_subject}.eml"
        
                        resolved_eml = str(Path(_out_dir) / eml_name)
                        msg.save(resolved_eml, ae.SaveOptions.default_eml)
                        created_files.append(eml_name)
                    except Exception as inner_exc:
                        logger.error(
                            "Failed to extract/save message %s from PST: %s", getattr(msg_info, "subject", "unknown"), inner_exc
                        )
                        continue
        
                return {
                    "status": "success",
                    "message": f"Extracted {len(created_files)} message(s) from PST.",
                    "created_files": created_files,
                    "output_filename": output_base or "",
                }
        
            except Exception as exc:
                logger.exception("Error processing PST file %s", input_filename)
                return {"status": "error", "message": str(exc), "created_files": [], "output_filename": output_base or ""}

        @mcp.tool()
        async def email_read_mbox(
            input_filename: str,
            max_count: int | None = None,
        ) -> dict:
            """
            Read subjects from an MBOX file.
        
            IMPORTANT: All *_filename parameters accept ONLY the bare filename (e.g. 'archive.mbox') —
            no path, no directory, no drive letter, no slash.
            The file MUST already exist in the server's ASPOSE_INPUT_DIR folder.
            Do NOT ask the user to upload a file — files are pre-placed in that folder.
            Output files are written to the same folder; returned output_filename is the bare name only.
        
            Args:
                input_filename (str): Bare filename of the MBOX file to read. Must exist in ASPOSE_INPUT_DIR.
                max_count (int | None, optional): Maximum number of messages to read; if omitted all messages are read.
        
            Returns:
                dict: {
                    "status": "success" | "error",
                    "message": str,
                    "subjects": list[str]
                }
        
            Raises:
                FileNotFoundError: If the input file does not exist.
                Exception: For any other error while reading the MBOX.
        
            Example:
                >>> result = await email_read_mbox("archive.mbox", max_count=10)
                >>> result["subjects"]
            """
            import logging
            from pathlib import Path
            from mcp_server.path_utils import get_safe_path, temp_output_path  # temp_output_path imported per project standards
        
            # Sanitize and resolve the input filename safely
            input_filename = Path(input_filename.strip().replace('\x00', '')).name
            resolved_input = get_safe_path(input_filename)
            if not Path(resolved_input).is_file():
                raise FileNotFoundError(f"File not found: {input_filename}")
        
            # Import Aspose after the file existence check
            import aspose.email as ae
        
            logger = logging.getLogger(__name__)
        
            subjects: list[str] = []
            reader = None
            try:
                reader = ae.storage.mbox.MboxrdStorageReader(resolved_input, False)
                count = 0
                msg = reader.read_next_message()
                while msg is not None:
                    subjects.append(msg.subject or "")
                    count += 1
                    if max_count is not None and count >= max_count:
                        break
                    msg = reader.read_next_message()
                return {
                    "status": "success",
                    "message": f"Read {len(subjects)} message(s) from {input_filename}.",
                    "subjects": subjects,
                }
            except Exception as exc:  # pragma: no cover
                logger.exception("Error reading MBOX file")
                return {"status": "error", "message": str(exc), "subjects": []}
            finally:
                if reader is not None:
                    try:
                        reader.dispose()
                    except Exception as dispose_exc:  # pragma: no cover
                        logger.debug("Failed to dispose MboxrdStorageReader: %s", dispose_exc)

        @mcp.tool()
        async def email_detect_format(input_filename: str) -> dict:
            """
            Detect the file format of an email file located in the server's ASPOSE_INPUT_DIR.
        
            IMPORTANT:
            All *_filename parameters accept ONLY the bare filename (e.g. 'scan.jpg') — no path, no directory, no drive letter, no slash.
            The file MUST already exist in the server's ASPOSE_INPUT_DIR folder before calling this tool.
            Do NOT ask the user to upload a file — files are pre-placed in the server folder by the user.
            Output files are written to ASPOSE_OUTPUT_DIR (falls back to ASPOSE_INPUT_DIR if unset).
        
            Args:
                input_filename: Bare filename of the email file whose format is to be detected.
        
            Returns:
                dict: {"status": "success", "format": "<format_type>"} on success,
                      or {"status": "error", "message": "<error details>"} on failure.
        
            Raises:
                FileNotFoundError: If the input file cannot be located in ASPOSE_INPUT_DIR.
                Exception: For any unexpected errors raised by Aspose.
        
            Example:
                result = await email_detect_format("message.eml")
                # result => {"status": "success", "format": "Eml"}
            """
            import os
            from pathlib import Path
            import logging
        
            logger = logging.getLogger(__name__)
        
            # Sanitize and resolve the input filename
            input_filename = Path(input_filename.strip().replace('\x00', '')).name
            _input_dir = os.environ.get("ASPOSE_INPUT_DIR", "").strip()
            if not _input_dir:
                raise FileNotFoundError(
                    f"File not found: {input_filename} — ASPOSE_INPUT_DIR environment variable is not configured."
                )
            resolved_input = str(Path(_input_dir) / input_filename)
            if not Path(resolved_input).is_file():
                raise FileNotFoundError(
                    f"File not found: {input_filename} (ASPOSE_INPUT_DIR={_input_dir})"
                )
        
            try:
                # Lazy import of Aspose.Email
                from aspose.email.tools import FileFormatUtil
        
                info = FileFormatUtil.detect_file_format(resolved_input)
                format_type = str(info.file_format_type)
                logger.debug("Detected format %s for file %s", format_type, input_filename)
                return {"status": "success", "format": format_type}
            except Exception as exc:
                logger.exception("Failed to detect email format for %s", input_filename)
                return {"status": "error", "message": str(exc)}

        @mcp.tool()
        async def email_save_message(
            input_filename: str,
            output_filename: str | None,
            save_option: str,
        ) -> dict:
            """
            Convert and save an email message to a different format.
        
            IMPORTANT: All *_filename parameters accept ONLY the bare filename (e.g. 'scan.jpg') —
            no path, no directory, no drive letter, no slash.
            The file MUST already exist in the server's ASPOSE_INPUT_DIR folder.
            Do NOT ask the user to upload a file — files are pre‑placed in that folder.
            Output files are written to the same folder; returned output_filename is the bare name only.
        
            Args:
                input_filename: Bare filename of the source email (e.g. 'message.eml') — must already exist in ASPOSE_INPUT_DIR.
                output_filename: Optional bare filename for the converted email. If omitted, a name is generated from the input.
                save_option: One of "msg", "eml", "mhtml", "html" indicating the desired output format.
        
            Returns:
                dict: {
                    "status": "success" | "error",
                    "message": str,
                    "output_filename": str   # bare name of the written file (only on success)
                }
        
            Example:
                >>> result = await email_save_message(
                ...     input_filename="original.eml",
                ...     output_filename=None,
                ...     save_option="msg",
                ... )
                >>> result["status"]
                "success"
                >>> result["output_filename"]
                "original.msg"
        
            Raises:
                FileNotFoundError: If the input file cannot be located.
                ValueError: If an unsupported save_option is supplied.
                Exception: Any unexpected error from Aspose.Email.
            """
            import logging
            from pathlib import Path
            from mcp_server.path_utils import get_safe_path, temp_output_path
        
            logger = logging.getLogger(__name__)
        
            # ---------- Resolve and validate input ----------
            input_filename = Path(input_filename.strip().replace('\x00', '')).name
            resolved_input = get_safe_path(input_filename)
            if not Path(resolved_input).is_file():
                raise FileNotFoundError(f"File not found: {input_filename}")
        
            # ---------- Determine output filename ----------
            # Mapping of save_option to Aspose save options and file extension
            option_map = {
                "msg": ("default_msg_unicode", "msg"),
                "eml": ("default_eml", "eml"),
                "mhtml": ("default_mhtml", "mhtml"),
                "html": ("default_html", "html"),
            }
        
            if save_option not in option_map:
                raise ValueError(
                    f"Invalid save_option '{save_option}'. Must be one of: {', '.join(option_map)}"
                )
        
            save_opt_name, ext = option_map[save_option]
        
            if output_filename is not None:
                output_filename = Path(output_filename.strip().replace('\x00', '')).name
                output_basename = output_filename
                resolved_output = temp_output_path(Path(output_basename).stem, f".{ext}")
            else:
                output_basename = f"{Path(input_filename).stem}.{ext}"
                resolved_output = temp_output_path(Path(output_basename).stem, f".{ext}")
        
            # ---------- Import Aspose after validation ----------
            import aspose.email as ae
        
            # Retrieve the actual Aspose SaveOptions object
            save_opt_obj = getattr(ae.SaveOptions, save_opt_name)
        
            try:
                # Load the email
                msg = ae.MailMessage.load(resolved_input)
        
                # Save using the selected format
                msg.save(str(resolved_output), save_opt_obj)
        
                return {
                    "status": "success",
                    "message": f"Email saved as {save_option.upper()}.",
                    "output_filename": output_basename,
                }
            except Exception as exc:  # pragma: no cover
                logger.exception("Failed to save email")
                return {"status": "error", "message": str(exc)}

        @mcp.tool()
        async def email_folder_get_subfolders(
            input_filename: str,
            folder_name: str | None = None,
        ) -> dict:
            """
            Retrieve sub‑folders of a specified folder in a PST file.
        
            IMPORTANT:
            * All *_filename parameters accept ONLY the bare filename (e.g. 'archive.pst') — no path, no directory, no drive letter, no slash.
            * The file MUST already exist in the server's ASPOSE_INPUT_DIR folder before calling this tool.
            * Do NOT ask the user to upload a file — files are pre‑placed in the server folder by the user.
            * Output files are written to ASPOSE_OUTPUT_DIR (falls back to ASPOSE_INPUT_DIR if unset).
        
            Args:
                input_filename: Bare filename of the PST file to open, located in ASPOSE_INPUT_DIR.
                folder_name: Optional name of the folder whose sub‑folders are requested; if omitted the root folder is used.
        
            Returns:
                dict: {
                    "status": "success" | "error",
                    "message": str,
                    "subfolders": list[dict]  # each dict contains "display_name" and "content_count"
                }
        
            Raises:
                FileNotFoundError: If the PST file cannot be found in ASPOSE_INPUT_DIR.
                ValueError: If the requested folder does not exist in the PST.
                Exception: For any other unexpected errors from Aspose.
        
            Example:
                result = await email_folder_get_subfolders("archive.pst", "Inbox")
                # result["subfolders"] -> [{"display_name": "Sub1", "content_count": 10}, ...]
            """
            import os
            import logging
            from pathlib import Path
        
            logger = logging.getLogger(__name__)
        
            # ---------- Resolve input PST file ----------
            # Sanitize filename
            input_filename = Path(input_filename.strip().replace('\x00', '')).name
            _input_dir = os.environ.get("ASPOSE_INPUT_DIR", "").strip()
            if not _input_dir:
                raise FileNotFoundError(
                    f"File not found: {input_filename} — ASPOSE_INPUT_DIR environment variable is not configured."
                )
            resolved_input = str(Path(_input_dir) / input_filename)
            if not Path(resolved_input).is_file():
                raise FileNotFoundError(f"File not found: {input_filename} (ASPOSE_INPUT_DIR={_input_dir})")
        
            try:
                # ---------- Load PST ----------
                import aspose.email as ae
        
                pst = ae.storage.pst.PersonalStorage.from_file(resolved_input)
        
                # ---------- Locate target folder ----------
                if folder_name:
                    # Attempt to get the specified sub‑folder from the root
                    try:
                        target_folder = pst.root_folder.get_sub_folder(folder_name)
                    except Exception as exc:
                        raise ValueError(f"Folder '{folder_name}' not found in PST.") from exc
                else:
                    target_folder = pst.root_folder
        
                # ---------- Retrieve sub‑folders ----------
                subfolders = target_folder.get_sub_folders()
                result_list = [
                    {"display_name": sub.display_name, "content_count": sub.content_count}
                    for sub in subfolders
                ]
        
                logger.debug(
                    "Retrieved %d sub‑folders from %s (folder='%s')",
                    len(result_list),
                    input_filename,
                    folder_name or "<root>",
                )
        
                return {
                    "status": "success",
                    "message": f"Found {len(result_list)} sub‑folder(s).",
                    "subfolders": result_list,
                }
        
            except Exception as exc:
                logger.exception("Error retrieving sub‑folders from PST '%s': %s", input_filename, exc)
                return {"status": "error", "message": str(exc), "subfolders": []}

        @mcp.tool()
        async def email_pst_get_message_count(
            input_filename: str,
            folder_name: str | None = None,
        ) -> dict:
            """
            Count messages in a PST folder.
        
            IMPORTANT: All *_filename parameters accept ONLY the bare filename (e.g. 'archive.pst') —
            no path, no directory, no drive letter, no slash.
            The file MUST already exist in the server's ASPOSE_INPUT_DIR folder.
            Do NOT ask the user to upload a file — files are pre‑placed in that folder.
            Output files are written to the same folder; returned output_filename is the bare name only.
        
            Args:
                input_filename: Bare filename of the PST file to open.
                folder_name: Name of the sub‑folder inside the PST to count messages from; defaults to the root folder.
        
            Returns:
                dict: {
                    "status": "success" | "error",
                    "message": str,
                    "count": int   # present only when status is "success"
                }
        
            Raises:
                FileNotFoundError: If the PST file cannot be located.
                ValueError: If the requested folder does not exist.
                Exception: For any other Aspose‑Email errors.
        
            Example:
                >>> result = await email_pst_get_message_count("archive.pst", "Inbox")
                >>> result["count"]
                42
            """
            import os
            import logging
            from pathlib import Path
            from mcp_server.path_utils import get_safe_path, temp_output_path
        
            # Sanitize and resolve the input filename
            input_filename = Path(input_filename.strip().replace('\x00', '')).name
            resolved_input = get_safe_path(input_filename)
            if not Path(resolved_input).is_file():
                raise FileNotFoundError(f"File not found: {input_filename}")
        
            # Import Aspose after the existence check
            import aspose.email as ae
        
            try:
                pst = ae.storage.pst.PersonalStorage.from_file(resolved_input)
        
                # Determine which folder to inspect
                if folder_name:
                    try:
                        folder = pst.root_folder.get_sub_folder(folder_name)
                    except Exception as exc:
                        raise ValueError(f"Folder '{folder_name}' not found in PST.") from exc
                else:
                    folder = pst.root_folder
        
                # Count messages
                count = sum(1 for _ in folder.enumerate_messages())
        
                return {
                    "status": "success",
                    "message": f"Found {count} messages in folder '{folder_name or 'root'}'.",
                    "count": count,
                }
            except Exception as exc:
                logging.getLogger(__name__).error("Error counting PST messages: %s", exc)
                return {"status": "error", "message": str(exc)}

        @mcp.tool()
        async def email_pst_list_message_subjects(
            input_filename: str,
            folder_name: str | None = None,
        ) -> dict:
            """
            List the subjects of all messages in a PST folder.
        
            IMPORTANT: All *_filename parameters accept ONLY the bare filename (e.g. 'scan.jpg') —
            no path, no directory, no drive letter, no slash.
            The file MUST already exist in the server's ASPOSE_INPUT_DIR folder.
            Do NOT ask the user to upload a file — files are pre‑placed in that folder.
            Output files are written to the same folder; returned output_filename is the bare name only.
        
            Args:
                input_filename: Bare filename of the PST file to open, located in ASPOSE_INPUT_DIR.
                folder_name: Optional name of the sub‑folder inside the PST to list messages from.
                             If omitted, the root folder is used.
        
            Returns:
                dict: {
                    "status": "success" | "error",
                    "message": str,
                    "subjects": list[str]   # present only on success
                }
        
            Raises:
                FileNotFoundError: If the PST file cannot be found in ASPOSE_INPUT_DIR.
                ValueError: If the requested folder does not exist in the PST.
                Exception: Any other unexpected error from Aspose.Email.
        
            Example:
                >>> result = await email_pst_list_message_subjects("my_mail.pst", "Inbox")
                # result = {"status": "success", "message": "...", "subjects": ["Subject 1", ...]}
            """
            import logging
            from pathlib import Path
            from mcp_server.path_utils import get_safe_path
        
            logger = logging.getLogger(__name__)
        
            # Validate and resolve the input PST file safely
            input_filename = Path(input_filename.strip().replace('\x00', '')).name
            resolved_input = get_safe_path(input_filename)
            if not Path(resolved_input).is_file():
                raise FileNotFoundError(f"File not found: {input_filename}")
        
            try:
                # Lazy import of Aspose.Email after validation
                import aspose.email as ae
        
                # Open the PST storage
                pst = ae.storage.pst.PersonalStorage.from_file(resolved_input)
        
                # Select the requested folder
                if folder_name:
                    try:
                        folder = pst.root_folder.get_sub_folder(folder_name)
                    except Exception as exc:
                        raise ValueError(f"Folder '{folder_name}' not found in PST.") from exc
                else:
                    folder = pst.root_folder
        
                # Enumerate messages and collect subjects
                subjects = [msg_info.subject for msg_info in folder.enumerate_messages()]
        
                return {
                    "status": "success",
                    "message": f"Found {len(subjects)} message(s) in folder '{folder_name or 'root'}'.",
                    "subjects": subjects,
                }
        
            except Exception as exc:
                logger.exception("Error listing PST message subjects")
                return {"status": "error", "message": str(exc)}

        @mcp.tool()
        async def email_mbox_read_next_message(
            input_filename: str,
        ) -> dict:
            """
            Read the next email message from an MBOX file.
        
            IMPORTANT: All *_filename parameters accept ONLY the bare filename (e.g. 'mailbox.mbox') —
            no path, no directory, no drive letter, no slash.
            The file MUST already exist in the server's ASPOSE_INPUT_DIR folder.
            Do NOT ask the user to upload a file — files are pre‑placed in that folder.
            Output files are written to the same folder; returned output_filename is the bare name only.
        
            Args:
                input_filename: Bare filename of the MBOX file to read (e.g. "mailbox.mbox").
        
            Returns:
                dict: A result dictionary containing at minimum:
                    - "status": "success" if a message was read, otherwise "error".
                    - "message": The subject of the next message, or a description when no more messages are available.
                    - "subject": The raw subject string or None when there is no next message.
        
            Raises:
                FileNotFoundError: If the specified MBOX file does not exist in the allowed folder.
        
            Example:
                # result = await email_mbox_read_next_message("inbox.mbox")
                # result == {"status": "success", "message": "Subject line", "subject": "Subject line"}
            """
            import logging
            from pathlib import Path
            from mcp_server.path_utils import get_safe_path, temp_output_path  # temp_output_path kept for compliance
        
            # Sanitize and resolve the input filename safely before any Aspose import
            input_filename = Path(input_filename.strip().replace('\x00', '')).name
            resolved_input = get_safe_path(input_filename)
            if not Path(resolved_input).is_file():
                raise FileNotFoundError(f"File not found: {input_filename}")
        
            # Import Aspose after the file existence check
            import aspose.email as ae
        
            logger = logging.getLogger(__name__)
        
            reader = None
            try:
                # Initialise the MBOX reader (second argument = leaveOpen, we keep it False)
                reader = ae.storage.mbox.MboxrdStorageReader(resolved_input, False)
        
                # Read the next message
                msg = reader.read_next_message()
                if msg is None:
                    return {
                        "status": "success",
                        "message": "No more messages in the MBOX file.",
                        "subject": None,
                    }
        
                subject = msg.subject or ""
                return {
                    "status": "success",
                    "message": subject,
                    "subject": subject,
                }
        
            except Exception as exc:  # pragma: no cover
                logger.exception("Error reading next message from MBOX")
                return {"status": "error", "message": str(exc)}
        
            finally:
                # Ensure the reader is disposed to release the file handle
                if reader is not None:
                    try:
                        reader.dispose()
                    except Exception as dispose_exc:  # pragma: no cover
                        logger.warning("Failed to dispose MboxrdStorageReader: %s", dispose_exc)

        @mcp.tool()
        async def email_mbox_dispose(input_filename: str) -> dict:
            """
            Dispose an opened MboxrdStorageReader for the specified MBOX file.
        
            IMPORTANT:
            * All *_filename parameters accept ONLY the bare filename (e.g. 'scan.jpg') — no path, no directory, no drive letter, no slash.
            * The file MUST already exist in the server's ASPOSE_INPUT_DIR folder before calling this tool.
            * Do NOT ask the user to upload a file — files are pre-placed in the server folder by the user.
            * Output files are written to ASPOSE_OUTPUT_DIR (falls back to ASPOSE_INPUT_DIR if unset).
        
            Args:
                input_filename: Bare filename of the MBOX file that was previously opened with MboxrdStorageReader
                                (e.g. "archive.mbox"). The file must reside in ASPOSE_INPUT_DIR.
        
            Returns:
                dict: {
                    "status": "success" | "error",
                    "message": str   # description of the outcome
                }
        
            Raises:
                FileNotFoundError: If the input file cannot be located in ASPOSE_INPUT_DIR.
                Exception: For any unexpected errors raised by Aspose.Email.
        
            Example:
                >>> result = await email_mbox_dispose("archive.mbox")
                >>> # result => {"status": "success", "message": "Reader disposed successfully."}
            """
            import os
            from pathlib import Path
            import logging
        
            logger = logging.getLogger(__name__)
        
            # ---------- Input validation ----------
            # Sanitize filename and ensure it is a plain name
            input_filename = Path(input_filename.strip().replace('\x00', '')).name
        
            # Resolve the input directory from environment
            _input_dir = os.environ.get("ASPOSE_INPUT_DIR", "").strip()
            if not _input_dir:
                raise FileNotFoundError(
                    f"File not found: {input_filename} — ASPOSE_INPUT_DIR environment variable is not configured."
                )
        
            resolved_input = str(Path(_input_dir) / input_filename)
        
            if not Path(resolved_input).is_file():
                raise FileNotFoundError(
                    f"File not found: {input_filename} (ASPOSE_INPUT_DIR={_input_dir})"
                )
        
            # ---------- Aspose operation ----------
            try:
                import aspose.email as ae
        
                # Initialize the reader (the file is assumed to have been opened earlier in the workflow)
                reader = ae.storage.mbox.MboxrdStorageReader(resolved_input, False)
        
                # Dispose the reader to release the file handle
                reader.dispose()
                logger.debug("MboxrdStorageReader disposed for file %s", input_filename)
        
                return {"status": "success", "message": "Reader disposed successfully."}
            except Exception as exc:
                logger.error("Failed to dispose MboxrdStorageReader for %s: %s", input_filename, exc)
                return {"status": "error", "message": str(exc)}
