# Auto-generated by Aspose MCP Builder — do not edit manually.
# Product: Aspose.Finance for Python via .NET  Package: aspose-finance
from __future__ import annotations

import logging
import tempfile
from pathlib import Path

from mcp_server.plugin import AsposePlugin
from mcp_server.path_utils import get_safe_path, temp_output_path, apply_license_for, platform_hint

logger = logging.getLogger(__name__)


class FinancePlugin(AsposePlugin):
    product_name = "finance"
    pypi_package = "aspose-finance"
    min_version = "24.1.0"

    def health_check(self) -> bool:
        """Check that the Aspose FINANCE package is importable.

        Args:
            None

        Returns:
            True if the package imports without error, False otherwise.

        Raises:
            None. Import errors are caught and return False.

        Example:
            >>> plugin = FinancePlugin()
            >>> isinstance(plugin.health_check(), bool)
            True
        """
        try:
            import aspose.finance  # noqa: F401, PLC0415
            return True
        except Exception:
            return False

    def get_tool_manifest(self) -> list[dict[str, object]]:
        """Return metadata for all registered tools.

        Args:
            None

        Returns:
            List of dicts each with keys: name, description, params, returns.

        Raises:
            None.

        Example:
            >>> plugin = FinancePlugin()
            >>> manifest = plugin.get_tool_manifest()
            >>> len(manifest) >= 15
            True
        """
        return [
            {"name": 'finance_create_xbrl', "description": 'Creates a new empty XBRL document and saves it to the specified output file.', "params": [{"name": 'output_filename', "type": 'str', "required": True, "description": ""}], "returns": "dict"},
            {"name": 'finance_read_xbrl', "description": 'Loads an XBRL file and returns the number of XBRL instances it contains.', "params": [{"name": 'input_filename', "type": 'str', "required": True, "description": ""}], "returns": "dict"},
            {"name": 'finance_validate_xbrl', "description": 'Validates all XBRL instances in a document and returns a list of validation error messages.', "params": [{"name": 'input_filename', "type": 'str', "required": True, "description": ""}], "returns": "dict"},
            {"name": 'finance_xbrl_to_xlsx', "description": 'Converts an XBRL document to XLSX format using explicit SaveOptions.', "params": [{"name": 'input_filename', "type": 'str', "required": True, "description": ""}, {"name": 'output_filename', "type": 'str | None', "required": False, "description": ""}], "returns": "dict"},
            {"name": 'finance_xbrl_to_ixbrl', "description": 'Converts an XBRL document to iXBRL (HTML) format using explicit SaveOptions.', "params": [{"name": 'input_filename', "type": 'str', "required": True, "description": ""}, {"name": 'output_filename', "type": 'str | None', "required": False, "description": ""}], "returns": "dict"},
            {"name": 'finance_read_ixbrl', "description": 'Loads an iXBRL (HTML) document and returns basic document information.', "params": [{"name": 'input_filename', "type": 'str', "required": True, "description": ""}], "returns": "dict"},
            {"name": 'finance_validate_ixbrl', "description": 'Validates an iXBRL document and returns a list of validation error messages.', "params": [{"name": 'input_filename', "type": 'str', "required": True, "description": ""}], "returns": "dict"},
            {"name": 'finance_ixbrl_to_xlsx', "description": 'Converts an iXBRL HTML document to XLSX format using explicit SaveOptions.', "params": [{"name": 'input_filename', "type": 'str', "required": True, "description": ""}, {"name": 'output_filename', "type": 'str | None', "required": False, "description": ""}], "returns": "dict"},
            {"name": 'finance_ofx_request_to_v2', "description": 'Converts an OFX request file from version 1.x (SGML) to version 2.x (XML).', "params": [{"name": 'input_filename', "type": 'str', "required": True, "description": ""}, {"name": 'output_filename', "type": 'str | None', "required": False, "description": ""}], "returns": "dict"},
            {"name": 'finance_ofx_request_to_v1', "description": 'Converts an OFX request file from version 2.x (XML) to version 1.x (SGML).', "params": [{"name": 'input_filename', "type": 'str', "required": True, "description": ""}, {"name": 'output_filename', "type": 'str | None', "required": False, "description": ""}], "returns": "dict"},
            {"name": 'finance_ofx_response_to_v2', "description": 'Converts an OFX response file from version 1.x (SGML) to version 2.x (XML).', "params": [{"name": 'input_filename', "type": 'str', "required": True, "description": ""}, {"name": 'output_filename', "type": 'str | None', "required": False, "description": ""}], "returns": "dict"},
            {"name": 'finance_ofx_response_to_v1', "description": 'Converts an OFX response file from version 2.x (XML) to version 1.x (SGML).', "params": [{"name": 'input_filename', "type": 'str', "required": True, "description": ""}, {"name": 'output_filename', "type": 'str | None', "required": False, "description": ""}], "returns": "dict"},
            {"name": 'finance_add_xbrl_instance', "description": 'Adds a new XBRL instance to an existing XBRL document and returns its index.', "params": [], "returns": "dict"}
        ]

    def register_tools(self, mcp: "FastMCP") -> None:
        """Register all FINANCE tools with the FastMCP instance.

        Args:
            mcp: FastMCP server instance to register tools on.

        Returns:
            None.

        Raises:
            None.

        Example:
            >>> from mcp.server.fastmcp import FastMCP
            >>> mcp = FastMCP("test")
            >>> FinancePlugin().register_tools(mcp)
        """
        logger.debug("%s plugin registering tools. Platform: %s", "FINANCE", platform_hint())
        apply_license_for("aspose.finance")
        @mcp.tool()
        async def finance_create_xbrl(output_filename: str) -> dict:
            """
            Create an empty XBRL file.
        
            IMPORTANT:
            All *_filename parameters accept ONLY the bare filename (e.g. 'scan.jpg') — no path, no directory, no drive letter, no slash.
            The file MUST already exist in the server's ASPOSE_FILES_PATH folder before calling this tool.
            Do NOT ask the user to upload a file — files are pre‑placed in the server folder by the user.
            The output file is also written to the ASPOSE_FILES_PATH folder; the returned output_filename is the bare name only.
        
            Args:
                output_filename: Bare filename where the created XBRL file will be saved (e.g. 'report.xbrl').
        
            Returns:
                dict: Contains status, message, and output_filename.
        
            Raises:
                FileNotFoundError: If the output directory cannot be created.
                Exception: For any Aspose‑related errors.
        
            Example:
                result = await finance_create_xbrl('created.xbrl')
            """
            from pathlib import Path
            from mcp_server.path_utils import get_safe_path, temp_output_path
            import logging
        
            logger = logging.getLogger(__name__)
        
            # ----------------------------------------------------------------------
            # Sanitize and resolve the output filename (first operation before any Aspose import)
            # ----------------------------------------------------------------------
            output_filename = Path(output_filename.strip().replace('\x00', '')).name
            resolved_output = (
                get_safe_path(output_filename)
                if output_filename
                else str(temp_output_path("aspose_finance_result", ".xbrl"))
            )
            # Ensure the target directory exists
            Path(resolved_output).parent.mkdir(parents=True, exist_ok=True)
        
            try:
                # Lazy import of Aspose.Finance
                from aspose.finance.xbrl import XbrlDocument
        
                # Create an empty XBRL document and save it
                doc = XbrlDocument()
                doc.save(str(resolved_output))
            except Exception as exc:  # pragma: no cover
                logger.exception("Failed to create XBRL file")
                return {"status": "error", "message": str(exc), "output_filename": output_filename}
        
            return {
                "status": "success",
                "message": f"XBRL file created: {output_filename}",
                "output_filename": output_filename,
            }

        @mcp.tool()
        async def finance_read_xbrl(input_filename: str) -> dict:
            """
            Count XBRL instances in a pre‑uploaded XBRL document.
        
            IMPORTANT:
            * All *_filename parameters accept ONLY the bare filename (e.g. 'report.xbrl') — no path, no directory, no drive letter, no slash.
            * The file MUST already exist in the server's ASPOSE_FILES_PATH folder before calling this tool.
            * Do NOT ask the user to upload a file — files are pre‑placed in the server folder by the user.
            * The output file is also written to the ASPOSE_FILES_PATH folder; the returned output_filename is the bare name only.
        
            Args:
                input_filename: Bare filename of the XBRL file to read, e.g. 'financials.xbrl'.
                                 The file must already exist in ASPOSE_FILES_PATH.
        
            Returns:
                dict: {
                    "status": "success" | "error",
                    "message": description of the outcome,
                    "instance_count": int (present only on success)
                }
        
            Raises:
                FileNotFoundError: If the specified XBRL file does not exist.
                ValueError: If the file is not a valid XBRL document.
                Exception: For any other unexpected error.
        
            Example:
                >>> result = await finance_read_xbrl("sample.xbrl")
                >>> result["instance_count"]
                3
            """
            # ---------- Validate and resolve input ----------
            from pathlib import Path
            from mcp_server.path_utils import get_safe_path, temp_output_path
        
            # Sanitize filename (remove null bytes, whitespace, keep only name)
            input_filename = Path(input_filename.strip().replace('\x00', '')).name
            resolved_input = get_safe_path(input_filename)
        
            if not Path(resolved_input).is_file():
                raise FileNotFoundError(f"File not found: {input_filename}")
        
            # ---------- Lazy import of Aspose ----------
            import logging
            logger = logging.getLogger(__name__)
        
            try:
                from aspose.finance.xbrl import XbrlDocument
        
                # Load the XBRL document
                doc = XbrlDocument(str(resolved_input))
        
                # Retrieve the count of XBRL instances
                instance_count = doc.xbrl_instances.count
        
                logger.debug(
                    "Successfully read XBRL file '%s' (resolved: %s) – %d instance(s) found.",
                    input_filename,
                    resolved_input,
                    instance_count,
                )
        
                return {
                    "status": "success",
                    "message": "XBRL instances counted successfully.",
                    "instance_count": instance_count,
                }
        
            except FileNotFoundError:
                # Re‑raise to keep the original exception type
                raise
            except Exception as exc:
                logger.exception("Error processing XBRL file '%s': %s", input_filename, exc)
                return {"status": "error", "message": str(exc)}

        @mcp.tool()
        async def finance_validate_xbrl(input_filename: str) -> dict:
            """
            Validate an XBRL file using Aspose.Finance.
        
            IMPORTANT:
            All *_filename parameters accept ONLY the bare filename (e.g. 'report.xbrl') — no path, no directory, no drive letter, no slash.
            The file MUST already exist in the server's ASPOSE_FILES_PATH folder before calling this tool.
            Do NOT ask the user to upload a file — files are pre-placed in the server folder by the user.
            The output file is also written to the ASPOSE_FILES_PATH folder; the returned output_filename is the bare name only.
        
            Args:
                input_filename: bare filename only, e.g. 'report.xbrl' — must already exist in ASPOSE_FILES_PATH.
        
            Returns:
                dict: Contains at minimum the keys "status" (\"success\" or \"error\") and "message" (a descriptive string).
                      On success, also includes "errors" – a list of validation error strings – and "input_filename".
        
            Raises:
                FileNotFoundError: If the specified XBRL file does not exist.
                Exception: For any unexpected errors during validation.
        
            Example:
                result = await finance_validate_xbrl("sample.xbrl")
                # result => {"status": "success", "message": "Validation completed.", "errors": [], "input_filename": "sample.xbrl"}
            """
            # Resolve the input file safely
            from pathlib import Path
            from mcp_server.path_utils import get_safe_path, temp_output_path
            import logging
        
            logger = logging.getLogger(__name__)
        
            # Sanitize filename
            input_filename = Path(input_filename.strip().replace('\x00', '')).name
            resolved_input = get_safe_path(input_filename)
            if not Path(resolved_input).is_file():
                raise FileNotFoundError(f"File not found: {input_filename}")
        
            try:
                # Lazy import of Aspose.Finance
                from aspose.finance.xbrl import XbrlDocument
        
                doc = XbrlDocument(str(resolved_input))
                xbrl_instances = doc.xbrl_instances
                all_errors = []
        
                for i in range(xbrl_instances.count):
                    instance = xbrl_instances[i]
                    instance.validate()
                    all_errors.extend([str(e) for e in instance.validation_errors])
        
                return {
                    "status": "success",
                    "message": "Validation completed.",
                    "errors": all_errors,
                    "input_filename": input_filename,
                }
            except Exception as exc:
                logger.exception("Error validating XBRL file %s", input_filename)
                return {
                    "status": "error",
                    "message": str(exc),
                    "errors": [],
                    "input_filename": input_filename,
                }

        @mcp.tool()
        async def finance_xbrl_to_xlsx(
            input_filename: str,
            output_filename: str | None = None,
        ) -> dict:
            """
            Convert an XBRL file stored on the server to an XLSX spreadsheet.
        
            IMPORTANT:
            * All *_filename parameters accept ONLY the bare filename (e.g. 'report.xbrl') — no path, no directory, no drive letter, no slash.
            * The file MUST already exist in the server's ASPOSE_FILES_PATH folder before calling this tool.
            * Do NOT ask the user to upload a file — files are pre‑placed in the server folder by the user.
            * The output file is also written to the ASPOSE_FILES_PATH folder; the returned output_filename is the bare name only.
        
            Args:
                input_filename: Bare filename of the source XBRL file, e.g. "financials.xbrl".
                output_filename: Optional bare filename for the resulting XLSX file. If omitted,
                                 a temporary name is generated.
        
            Returns:
                dict: {
                    "status": "success" | "error",
                    "message": str,
                    "output_filename": str   # bare name of the written XLSX file
                }
        
            Raises:
                FileNotFoundError: If the input XBRL file does not exist.
                PermissionError: If the output location cannot be written.
                Exception: For any other errors raised by Aspose.
        
            Example:
                result = await finance_xbrl_to_xlsx("report.xbrl", "report.xlsx")
                # result => {"status":"success","message":"Conversion completed.","output_filename":"report.xlsx"}
            """
            # ---------- Validate and resolve input ----------
            from pathlib import Path
            from mcp_server.path_utils import get_safe_path, temp_output_path
            import logging
        
            logger = logging.getLogger(__name__)
        
            # sanitize input filename
            input_filename = Path(input_filename.strip().replace("\x00", "")).name
            resolved_input = get_safe_path(input_filename)
            if not Path(resolved_input).is_file():
                raise FileNotFoundError(f"File not found: {input_filename}")
        
            # ---------- Prepare output ----------
            if output_filename is not None:
                output_filename = Path(output_filename.strip().replace("\x00", "")).name
                resolved_output = get_safe_path(output_filename)
            else:
                # generate a temporary filename with .xlsx extension
                temp_path = temp_output_path("aspose_finance_result", ".xlsx")
                resolved_output = str(temp_path)  # Aspose expects a plain str
                output_filename = Path(resolved_output).name
        
            # ensure output directory exists
            Path(resolved_output).parent.mkdir(parents=True, exist_ok=True)
        
            # ---------- Perform conversion using Aspose ----------
            try:
                # lazy import of Aspose
                from aspose.finance.xbrl import XbrlDocument, SaveOptions, SaveFormat
        
                doc = XbrlDocument(str(resolved_input))
                opts = SaveOptions()
                opts.save_format = SaveFormat.XLSX
                doc.save(str(resolved_output), opts)
        
                logger.info(
                    "Converted XBRL '%s' to XLSX '%s'",
                    input_filename,
                    output_filename,
                )
                return {
                    "status": "success",
                    "message": "Conversion completed.",
                    "output_filename": output_filename,
                }
            except PermissionError as exc:
                logger.error("Permission error while writing output: %s", exc)
                return {"status": "error", "message": str(exc)}
            except Exception as exc:  # catch Aspose and any other unexpected errors
                logger.error("Error converting XBRL to XLSX: %s", exc)
                return {"status": "error", "message": str(exc)}

        @mcp.tool()
        async def finance_xbrl_to_ixbrl(
            input_filename: str,
            output_filename: str | None = None,
        ) -> dict:
            """
            Convert an XBRL document stored on the server to iXBRL (HTML) format.
        
            IMPORTANT:
            * All *_filename parameters accept ONLY the bare filename (e.g. 'report.xbrl') — no path, no directory, no drive letter, no slash.
            * The file MUST already exist in the server's ASPOSE_FILES_PATH folder before calling this tool.
            * Do NOT ask the user to upload a file — files are pre‑placed in the server folder by the user.
            * The output file is also written to the ASPOSE_FILES_PATH folder; the returned output_filename is the bare name only.
        
            Args:
                input_filename: Bare filename of the source XBRL file, e.g. "financials.xbrl". Must already exist in ASPOSE_FILES_PATH.
                output_filename: Optional bare filename for the resulting iXBRL HTML file. If omitted, a temporary name is generated.
        
            Returns:
                dict: {
                    "status": "success" | "error",
                    "message": description of the result,
                    "output_filename": bare name of the generated HTML file (present only on success)
                }
        
            Raises:
                FileNotFoundError: If the input XBRL file does not exist.
                Exception: Propagated as an error status if Aspose conversion fails.
        
            Example:
                result = await finance_xbrl_to_ixbrl("annual_report.xbrl", "annual_report.html")
                # result => {"status":"success","message":"Conversion completed","output_filename":"annual_report.html"}
            """
            # ----------------------------------------------------------------------
            # Resolve and validate input file
            # ----------------------------------------------------------------------
            from pathlib import Path
            from mcp_server.path_utils import get_safe_path, temp_output_path
            import logging
        
            logger = logging.getLogger(__name__)
        
            # sanitize input filename
            input_filename = Path(input_filename.strip().replace('\x00', '')).name
            resolved_input = get_safe_path(input_filename)
            if not Path(resolved_input).is_file():
                raise FileNotFoundError(f"File not found: {input_filename}")
        
            # ----------------------------------------------------------------------
            # Resolve output location
            # ----------------------------------------------------------------------
            if output_filename is not None:
                output_filename = Path(output_filename.strip().replace('\x00', '')).name
                resolved_output = get_safe_path(output_filename)
                output_name = output_filename
            else:
                # generate a temporary filename with .html extension
                resolved_output = str(temp_output_path("aspose_finance_result", ".html"))
                output_name = Path(resolved_output).name
        
            # ensure output directory exists
            Path(resolved_output).parent.mkdir(parents=True, exist_ok=True)
        
            # ----------------------------------------------------------------------
            # Perform conversion using Aspose.Finance
            # ----------------------------------------------------------------------
            try:
                # Lazy import of Aspose.Finance
                from aspose.finance.xbrl import XbrlDocument, SaveOptions, SaveFormat
        
                doc = XbrlDocument(resolved_input)
                opts = SaveOptions()
                opts.save_format = SaveFormat.IXBRL
                doc.save(resolved_output, opts)
        
                logger.info("XBRL to iXBRL conversion succeeded: %s -> %s", input_filename, output_name)
                return {
                    "status": "success",
                    "message": "Conversion completed",
                    "output_filename": output_name,
                }
            except Exception as exc:  # pragma: no cover
                logger.error("XBRL to iXBRL conversion failed: %s", exc)
                return {
                    "status": "error",
                    "message": str(exc),
                }

        @mcp.tool()
        async def finance_read_ixbrl(input_filename: str) -> dict:
            """
            Load an iXBRL HTML document that already resides in the server's ASPOSE_FILES_PATH folder.
        
            IMPORTANT:
            * All *_filename parameters accept ONLY the bare filename (e.g. 'report.html') — no path, no directory, no drive letter, no slash.
            * The file MUST already exist in the server's ASPOSE_FILES_PATH folder before calling this tool.
            * Do NOT ask the user to upload a file — files are pre‑placed in the server folder by the user.
            * The output file is also written to the ASPOSE_FILES_PATH folder; the returned output_filename is the bare name only.
        
            Args:
                input_filename: bare filename only, e.g. 'report.html' — must already exist in ASPOSE_FILES_PATH.
        
            Returns:
                dict: A dictionary containing at minimum:
                    - "status": "success" or "error"
                    - "message": description of the result or error
                    - "filename": the provided input filename (bare name)
                    - "document_type": a simple identifier for the loaded document (e.g., "iXBRL") on success.
        
            Raises:
                FileNotFoundError: If the specified file does not exist in ASPOSE_FILES_PATH.
                Exception: Any unexpected error while loading the document is caught and reported in the return dict.
        
            Example:
                result = await finance_read_ixbrl("annual_report.html")
                # result -> {"status":"success","message":"iXBRL document loaded successfully.",...}
            """
            # -------------------------------------------------------------------------
            # Resolve and validate the input filename (must happen before any Aspose import)
            # -------------------------------------------------------------------------
            from pathlib import Path
            from mcp_server.path_utils import get_safe_path
        
            input_filename = Path(input_filename.strip().replace('\x00', '')).name
            resolved_input = get_safe_path(input_filename)
            if not Path(resolved_input).is_file():
                raise FileNotFoundError(f"File not found: {input_filename}")
        
            # -------------------------------------------------------------------------
            # Aspose processing
            # -------------------------------------------------------------------------
            import logging
            logger = logging.getLogger(__name__)
        
            try:
                from aspose.finance.xbrl import InlineXbrlDocument
        
                # Instantiate the document using the resolved absolute path
                doc = InlineXbrlDocument(resolved_input)
        
                # Minimal metadata about the loaded document
                return {
                    "status": "success",
                    "message": "iXBRL document loaded successfully.",
                    "filename": input_filename,
                    "document_type": "iXBRL"
                }
            except Exception as exc:  # pragma: no cover
                logger.exception("Failed to read iXBRL document")
                return {"status": "error", "message": str(exc)}

        @mcp.tool()
        async def finance_validate_ixbrl(input_filename: str) -> dict:
            """
            Validate an iXBRL document using Aspose.Finance.
        
            IMPORTANT:
            * All *_filename parameters accept ONLY the bare filename (e.g. 'report.html') — no path, no directory, no drive letter, no slash.
            * The file MUST already exist in the server's ASPOSE_FILES_PATH folder before calling this tool.
            * Do NOT ask the user to upload a file — files are pre‑placed in the server folder by the user.
            * The output file is also written to the ASPOSE_FILES_PATH folder; the returned output_filename is the bare name only.
        
            Args:
                input_filename: Bare filename of the iXBRL file to validate (must exist in ASPOSE_FILES_PATH).
        
            Returns:
                dict: A dictionary containing at minimum:
                    - "status": "success" if validation ran, otherwise "error".
                    - "message": Human‑readable description.
                    - "errors": List of validation error strings (empty list if none).
                    - "input_filename": The bare input filename provided.
        
            Raises:
                FileNotFoundError: If the specified input file does not exist.
                Exception: Any unexpected error raised by Aspose.Finance during validation.
        
            Example:
                >>> result = await finance_validate_ixbrl("sample_report.html")
                >>> result["status"]
                'success'
                >>> result["errors"]
                []
            """
            # ----------------------------------------------------------------------
            # Resolve and validate input file (must be done before any Aspose import)
            # ----------------------------------------------------------------------
            import logging
            from pathlib import Path
            from mcp_server.path_utils import get_safe_path, temp_output_path
        
            logger = logging.getLogger(__name__)
        
            # Sanitize filename
            input_filename = Path(input_filename.strip().replace('\x00', '')).name
            resolved_input = get_safe_path(input_filename)
            if not Path(resolved_input).is_file():
                raise FileNotFoundError(f"File not found: {input_filename}")
        
            # ----------------------------------------------------------------------
            # Aspose import (after input validation)
            # ----------------------------------------------------------------------
            try:
                from aspose.finance.xbrl import InlineXbrlDocument
        
                # Load document and run validation
                doc = InlineXbrlDocument(str(resolved_input))
                doc.validate()
                errors = list(doc.validation_errors)  # Ensure a plain Python list
        
                logger.info(
                    "iXBRL validation completed for %s with %d error(s).",
                    input_filename,
                    len(errors),
                )
                return {
                    "status": "success",
                    "message": "Validation completed.",
                    "errors": errors,
                    "input_filename": input_filename,
                }
        
            except Exception as exc:  # Catch any Aspose‑related or unexpected errors
                logger.exception("Error during iXBRL validation for %s", input_filename)
                return {
                    "status": "error",
                    "message": str(exc),
                    "errors": [],
                    "input_filename": input_filename,
                }

        @mcp.tool()
        async def finance_ixbrl_to_xlsx(
            input_filename: str,
            output_filename: str | None = None,
        ) -> dict:
            """
            Convert an iXBRL HTML document stored on the server to an XLSX workbook.
        
            IMPORTANT:
            * All *_filename parameters accept ONLY the bare filename (e.g. 'report.html') — no path, no directory, no drive letter, no slash.
            * The file MUST already exist in the server's ASPOSE_FILES_PATH folder before calling this tool.
            * Do NOT ask the user to upload a file — files are pre‑placed in the server folder by the user.
            * The output file is also written to the ASPOSE_FILES_PATH folder; the returned output_filename is the bare name only.
        
            Args:
                input_filename: Bare filename of the source iXBRL HTML file, e.g. 'report.html'.
                output_filename: Optional bare filename for the resulting XLSX file. If omitted,
                                 a temporary name is generated.
        
            Returns:
                dict: {
                    "status": "success" | "error",
                    "message": description of the outcome,
                    "output_filename": bare name of the generated XLSX file (present only on success)
                }
        
            Raises:
                FileNotFoundError: If the input file does not exist in ASPOSE_FILES_PATH.
                Exception: Propagates any unexpected error from the Aspose conversion process.
        
            Example:
                result = await finance_ixbrl_to_xlsx("financial_report.html", "report.xlsx")
                # result => {"status":"success","message":"Conversion completed","output_filename":"report.xlsx"}
            """
            # ----------------------------------------------------------------------
            # Validate and resolve input file
            # ----------------------------------------------------------------------
            from pathlib import Path
            from mcp_server.path_utils import get_safe_path, temp_output_path
            import logging
        
            logger = logging.getLogger(__name__)
        
            # sanitize input filename
            input_filename = Path(input_filename.strip().replace("\x00", "")).name
            resolved_input = get_safe_path(input_filename)
            if not Path(resolved_input).is_file():
                raise FileNotFoundError(f"File not found: {input_filename}")
        
            # ----------------------------------------------------------------------
            # Prepare output location
            # ----------------------------------------------------------------------
            if output_filename is not None:
                output_filename = Path(output_filename.strip().replace("\x00", "")).name
                resolved_output = get_safe_path(output_filename)
            else:
                # generate a temporary filename with .xlsx extension
                temp_path = temp_output_path("aspose_finance_result", ".xlsx")
                resolved_output = str(temp_path)  # Aspose expects a plain str
                output_filename = Path(resolved_output).name
        
            # ensure output directory exists
            Path(resolved_output).parent.mkdir(parents=True, exist_ok=True)
        
            # ----------------------------------------------------------------------
            # Perform conversion using Aspose.Finance
            # ----------------------------------------------------------------------
            try:
                # Lazy import of Aspose inside the function
                from aspose.finance.xbrl import InlineXbrlDocument, SaveOptions, SaveFormat
        
                doc = InlineXbrlDocument(str(resolved_input))
                opts = SaveOptions()
                opts.save_format = SaveFormat.XLSX
                doc.save(str(resolved_output), opts)
        
                logger.info(
                    "Converted iXBRL '%s' to XLSX '%s'",
                    input_filename,
                    output_filename,
                )
                return {
                    "status": "success",
                    "message": "Conversion completed successfully.",
                    "output_filename": output_filename,
                }
        
            except Exception as exc:  # pragma: no cover
                logger.error("Failed to convert iXBRL to XLSX: %s", exc)
                return {
                    "status": "error",
                    "message": str(exc),
                }

        @mcp.tool()
        async def finance_ofx_request_to_v2(
            input_filename: str,
            output_filename: str | None = None,
        ) -> dict:
            """
            Convert an OFX request SGML file (version 1.x) to OFX 2.x XML.
        
            IMPORTANT:
            * All *_filename parameters accept ONLY the bare filename (e.g. 'request.sgml') — no path, no directory, no drive letter, no slash.
            * The file MUST already exist in the server's ASPOSE_FILES_PATH folder before calling this tool.
            * Do NOT ask the user to upload a file — files are pre‑placed in the server folder by the user.
            * The output file is also written to the ASPOSE_FILES_PATH folder; the returned output_filename is the bare name only.
        
            Args:
                input_filename: Bare filename of the SGML OFX request file, e.g. "request.sgml".
                output_filename: Optional bare filename for the resulting XML file. If omitted, a temporary name is generated.
        
            Returns:
                dict: {
                    "status": "success" | "error",
                    "message": description of the result,
                    "output_filename": bare name of the written XML file (present only on success)
                }
        
            Raises:
                FileNotFoundError: If the input file does not exist in ASPOSE_FILES_PATH.
                Exception: Propagates any unexpected error from the Aspose conversion.
        
            Example:
                >>> result = await finance_ofx_request_to_v2("request.sgml", "request_v2.xml")
                >>> result["status"]
                "success"
            """
            # ------------------------------------------------------------------
            # Resolve and validate input file
            # ------------------------------------------------------------------
            from pathlib import Path
            from mcp_server.path_utils import get_safe_path, temp_output_path
            import logging
        
            logger = logging.getLogger(__name__)
        
            # sanitize input filename
            input_filename = Path(input_filename.strip().replace("\x00", "")).name
            resolved_input = get_safe_path(input_filename)
            if not Path(resolved_input).is_file():
                raise FileNotFoundError(f"File not found: {input_filename}")
        
            # ------------------------------------------------------------------
            # Resolve output location
            # ------------------------------------------------------------------
            if output_filename is not None:
                output_filename = Path(output_filename.strip().replace("\x00", "")).name
                resolved_output = get_safe_path(output_filename)
            else:
                # generate a temporary filename with .xml extension
                resolved_output = str(temp_output_path("aspose_finance_ofx_result", ".xml"))
                output_filename = Path(resolved_output).name
        
            # ensure output directory exists
            Path(resolved_output).parent.mkdir(parents=True, exist_ok=True)
        
            # ------------------------------------------------------------------
            # Perform conversion using Aspose.Finance
            # ------------------------------------------------------------------
            try:
                # lazy import as required by policy
                from aspose.finance.ofx import OfxRequestDocument, OfxVersionEnum
        
                doc = OfxRequestDocument(str(resolved_input))
                doc.save(str(resolved_output), OfxVersionEnum.V2X)
        
                return {
                    "status": "success",
                    "message": f"Converted '{input_filename}' to OFX 2.x XML.",
                    "output_filename": output_filename,
                }
            except Exception as exc:  # pragma: no cover
                logger.exception("OFX conversion failed")
                return {
                    "status": "error",
                    "message": str(exc),
                }

        @mcp.tool()
        async def finance_ofx_request_to_v1(
            input_filename: str,
            output_filename: str | None = None,
        ) -> dict:
            """
            Convert an OFX request XML file stored on the server to OFX 1.x SGML format.
        
            IMPORTANT:
            * All *_filename parameters accept ONLY the bare filename (e.g. 'request.xml') — no path, no directory,
              no drive letter, no slash.
            * The file MUST already exist in the server's ASPOSE_FILES_PATH folder before calling this tool.
            * Do NOT ask the user to upload a file — files are pre‑placed in the server folder by the user.
            * The output file is also written to the ASPOSE_FILES_PATH folder; the returned output_filename is the
              bare name only.
        
            Args:
                input_filename: Bare filename of the OFX request XML file (must exist in ASPOSE_FILES_PATH).
                output_filename: Optional bare filename for the resulting SGML file. If omitted,
                                 a temporary name is generated.
        
            Returns:
                dict: {
                    "status": "success" | "error",
                    "message": str,
                    "output_filename": str   # bare name of the SGML file (only on success)
                }
        
            Raises:
                FileNotFoundError: If the input file does not exist.
                Exception: Propagated as an error status if conversion fails.
        
            Example:
                result = await finance_ofx_request_to_v1("request.xml", "request.sgml")
                # result => {"status":"success","message":"Converted successfully","output_filename":"request.sgml"}
            """
            # ----------------------------------------------------------------------
            # Resolve and validate input file (must be a safe filename inside ASPOSE_FILES_PATH)
            # ----------------------------------------------------------------------
            from pathlib import Path
            from mcp_server.path_utils import get_safe_path, temp_output_path
            import logging
        
            logger = logging.getLogger(__name__)
        
            # sanitize input filename
            input_filename = Path(input_filename.strip().replace("\x00", "")).name
            resolved_input = get_safe_path(input_filename)
            if not Path(resolved_input).is_file():
                raise FileNotFoundError(f"File not found: {input_filename}")
        
            # ----------------------------------------------------------------------
            # Resolve output location
            # ----------------------------------------------------------------------
            if output_filename is not None:
                output_filename = Path(output_filename.strip().replace("\x00", "")).name
                resolved_output = get_safe_path(output_filename)
            else:
                # generate a temporary filename with .sgml extension
                temp_path = temp_output_path("aspose_finance_result", ".sgml")
                resolved_output = str(temp_path)  # Aspose expects a plain string
                output_filename = Path(resolved_output).name
        
            # ensure output directory exists
            Path(resolved_output).parent.mkdir(parents=True, exist_ok=True)
        
            # ----------------------------------------------------------------------
            # Perform conversion using Aspose.Finance
            # ----------------------------------------------------------------------
            try:
                # Lazy import of Aspose
                from aspose.finance.ofx import OfxRequestDocument, OfxVersionEnum
        
                logger.debug(
                    "Converting OFX request '%s' to SGML version 1.x, output='%s'",
                    resolved_input,
                    resolved_output,
                )
                doc = OfxRequestDocument(resolved_input)
                doc.save(resolved_output, OfxVersionEnum.V1X)
        
                return {
                    "status": "success",
                    "message": "OFX request successfully converted to SGML (v1.x).",
                    "output_filename": output_filename,
                }
        
            except Exception as exc:  # pragma: no cover
                logger.exception("Failed to convert OFX request: %s", exc)
                return {
                    "status": "error",
                    "message": str(exc),
                }

        @mcp.tool()
        async def finance_ofx_response_to_v2(
            input_filename: str,
            output_filename: str | None = None,
        ) -> dict:
            """
            Convert an OFX response file (SGML, version 1.x) to OFX 2.x XML.
        
            IMPORTANT:
            - All *_filename parameters accept ONLY the bare filename (e.g. 'response.sgml') — no path, no directory, no drive letter, no slash.
            - The file MUST already exist in the server's ASPOSE_FILES_PATH folder before calling this tool.
            - Do NOT ask the user to upload a file — files are pre‑placed in the server folder by the user.
            - The output file is also written to the ASPOSE_FILES_PATH folder; the returned output_filename is the bare name only.
        
            Args:
                input_filename: Bare filename of the SGML OFX response file, e.g. 'response.sgml'.
                output_filename: Optional bare filename for the resulting XML file. If omitted, a temporary
                                 name is generated.
        
            Returns:
                dict: {
                    "status": "success" | "error",
                    "message": str,
                    "output_filename": str   # bare name of the written XML file (present only on success)
                }
        
            Raises:
                FileNotFoundError: If the input file does not exist in ASPOSE_FILES_PATH.
                Exception: Propagated as an error status if conversion fails.
        
            Example:
                result = await finance_ofx_response_to_v2("response.sgml", "response_v2.xml")
                # result => {"status": "success", "message": "Conversion completed.", "output_filename": "response_v2.xml"}
            """
            # ----------------------------------------------------------------------
            # Resolve and validate input file
            # ----------------------------------------------------------------------
            from pathlib import Path
            from mcp_server.path_utils import get_safe_path, temp_output_path
            import logging
        
            logger = logging.getLogger(__name__)
        
            # sanitize input filename (strip nulls, whitespace, keep only name)
            input_filename = Path(input_filename.strip().replace("\x00", "")).name
            resolved_input = get_safe_path(input_filename)
            if not Path(resolved_input).is_file():
                raise FileNotFoundError(f"File not found: {input_filename}")
        
            # ----------------------------------------------------------------------
            # Resolve output file location
            # ----------------------------------------------------------------------
            if output_filename is not None:
                output_filename = Path(output_filename.strip().replace("\x00", "")).name
                resolved_output = get_safe_path(output_filename)
            else:
                # generate a temporary filename with .xml extension
                temp_path = temp_output_path("aspose_finance_ofx_v2", ".xml")
                resolved_output = str(temp_path)  # Aspose expects a plain string
                output_filename = Path(resolved_output).name
        
            # Ensure output directory exists
            Path(resolved_output).parent.mkdir(parents=True, exist_ok=True)
        
            # ----------------------------------------------------------------------
            # Perform conversion using Aspose.Finance
            # ----------------------------------------------------------------------
            try:
                # Lazy import of Aspose after validation
                from aspose.finance.ofx import OfxResponseDocument, OfxVersionEnum
        
                # Load the SGML OFX response
                doc = OfxResponseDocument(str(resolved_input))
        
                # Save as OFX 2.x XML
                doc.save(str(resolved_output), OfxVersionEnum.V2X)
        
                logger.info(
                    "Converted OFX SGML '%s' to OFX 2.x XML '%s'.",
                    input_filename,
                    output_filename,
                )
                return {
                    "status": "success",
                    "message": "Conversion completed.",
                    "output_filename": output_filename,
                }
        
            except Exception as exc:  # pragma: no cover
                logger.error(
                    "Failed to convert OFX SGML '%s' to XML: %s", input_filename, str(exc)
                )
                return {
                    "status": "error",
                    "message": str(exc),
                }

        @mcp.tool()
        async def finance_ofx_response_to_v1(
            input_filename: str,
            output_filename: str | None = None,
        ) -> dict:
            """
            Convert an OFX response XML file stored on the server to OFX 1.x SGML format.
        
            IMPORTANT:
            - All *_filename parameters accept ONLY the bare filename (e.g. 'response.xml') — no path, no directory, no drive letter, no slash.
            - The file MUST already exist in the server's ASPOSE_FILES_PATH folder before calling this tool.
            - Do NOT ask the user to upload a file — files are pre‑placed in the server folder by the user.
            - The output file is also written to the ASPOSE_FILES_PATH folder; the returned output_filename is the bare name only.
        
            Args:
                input_filename: Bare filename of the OFX response XML file (must exist in ASPOSE_FILES_PATH).
                output_filename: Optional bare filename for the resulting SGML file. If omitted, a temporary name is generated.
        
            Returns:
                dict: {
                    "status": "success" | "error",
                    "message": str,
                    "output_filename": str   # bare name of the SGML file (only on success)
                }
        
            Raises:
                FileNotFoundError: If the input file does not exist.
                Exception: Propagated as an error status with message.
        
            Example:
                result = await finance_ofx_response_to_v1("response.xml", "response_v1.sgml")
                # result => {"status":"success","message":"Converted successfully","output_filename":"response_v1.sgml"}
            """
            # ---------- Resolve and validate input ----------
            from pathlib import Path
            from mcp_server.path_utils import get_safe_path, temp_output_path
            import logging
        
            logger = logging.getLogger(__name__)
        
            # sanitize input filename
            input_filename = Path(input_filename.strip().replace("\x00", "")).name
            resolved_input = get_safe_path(input_filename)
            if not Path(resolved_input).is_file():
                raise FileNotFoundError(f"File not found: {input_filename}")
        
            # ---------- Resolve output ----------
            if output_filename is not None:
                output_filename = Path(output_filename.strip().replace("\x00", "")).name
                resolved_output = get_safe_path(output_filename)
            else:
                # generate a temporary SGML filename
                temp_path = temp_output_path("aspose_finance_result", ".sgml")
                resolved_output = str(temp_path)  # Aspose expects a plain str
                output_filename = Path(resolved_output).name
        
            # ensure output directory exists
            Path(resolved_output).parent.mkdir(parents=True, exist_ok=True)
        
            # ---------- Perform conversion ----------
            try:
                # lazy import of Aspose.Finance
                from aspose.finance.ofx import OfxResponseDocument, OfxVersionEnum
        
                # load the OFX response and save as V1.x SGML
                doc = OfxResponseDocument(str(resolved_input))
                doc.save(str(resolved_output), OfxVersionEnum.V1X)
        
                return {
                    "status": "success",
                    "message": "Conversion completed successfully.",
                    "output_filename": output_filename,
                }
            except Exception as exc:  # pragma: no cover
                logger.exception("Failed to convert OFX response to V1.x SGML")
                return {
                    "status": "error",
                    "message": str(exc),
                }

        @mcp.tool()
        async def finance_add_xbrl_instance() -> dict:
            """
            Add a new XBRL instance to a fresh XBRL document.
        
            IMPORTANT:
            * All *_filename parameters accept ONLY the bare filename (e.g. 'scan.jpg') — no path, no directory, no drive letter, no slash.
            * The file MUST already exist in the server's ASPOSE_FILES_PATH folder before calling this tool.
            * Do NOT ask the user to upload a file — files are pre‑placed in the server folder by the user.
            * The output file is also written to the ASPOSE_FILES_PATH folder; the returned output_filename is the bare name only.
        
            Args:
                (none)
        
            Returns:
                dict: {
                    "status": "success" | "error",
                    "message": str,
                    "index": int | None   # index of the newly added XBRL instance when successful
                }
        
            Raises:
                FileNotFoundError: Not applicable (no file inputs).
                Exception: Propagates any unexpected Aspose errors.
        
            Example:
                result = await finance_add_xbrl_instance()
                # result -> {"status":"success","message":"XBRL instance added","index":0}
            """
            # Imports are deliberately placed inside the function (lazy import)
            import logging
            from aspose.finance.xbrl import XbrlDocument
        
            logger = logging.getLogger(__name__)
        
            try:
                # Create a new XBRL document and add an instance
                doc = XbrlDocument()
                idx = doc.xbrl_instances.add()
                logger.debug("Added XBRL instance with index %s", idx)
        
                return {
                    "status": "success",
                    "message": "XBRL instance added",
                    "index": idx,
                }
            except Exception as exc:  # Catch any Aspose‑related errors (e.g., max instances reached)
                logger.error("Failed to add XBRL instance: %s", exc)
                return {
                    "status": "error",
                    "message": str(exc),
                    "index": None,
                }
