# Auto-generated by Aspose MCP Builder — do not edit manually.
# Product: Aspose.PSD for Python via .NET  Package: aspose-psd
from __future__ import annotations

import logging
import tempfile
from pathlib import Path

from mcp_server.plugin import AsposePlugin
from mcp_server.path_utils import get_safe_path, temp_output_path, apply_license_for, platform_hint

logger = logging.getLogger(__name__)


class PsdPlugin(AsposePlugin):
    product_name = "psd"
    pypi_package = "aspose-psd"
    min_version = "24.1.0"

    def health_check(self) -> bool:
        """Check that the Aspose PSD package is importable.

        Args:
            None

        Returns:
            True if the package imports without error, False otherwise.

        Raises:
            None. Import errors are caught and return False.

        Example:
            >>> plugin = PsdPlugin()
            >>> isinstance(plugin.health_check(), bool)
            True
        """
        try:
            from aspose.psd import Image  # noqa: F401, PLC0415
            return True
        except Exception:
            return False

    def get_tool_manifest(self) -> list[dict[str, object]]:
        """Return metadata for all registered tools.

        Args:
            None

        Returns:
            List of dicts each with keys: name, description, params, returns.

        Raises:
            None.

        Example:
            >>> plugin = PsdPlugin()
            >>> manifest = plugin.get_tool_manifest()
            >>> len(manifest) >= 15
            True
        """
        return [
            {"name": 'psd_convert_to_png', "description": 'Export a PSD/PSB file to PNG with full transparency support.', "params": [{"name": 'input_filename', "type": 'str', "required": True, "description": ""}, {"name": 'output_filename', "type": 'str | None', "required": False, "description": ""}], "returns": "dict"},
            {"name": 'psd_convert_to_jpeg', "description": 'Export a PSD/PSB file to JPEG with configurable quality.', "params": [{"name": 'input_filename', "type": 'str', "required": True, "description": ""}, {"name": 'output_filename', "type": 'str | None', "required": False, "description": ""}, {"name": 'quality', "type": 'int', "required": False, "description": ""}], "returns": "dict"},
            {"name": 'psd_convert_to_tiff', "description": 'Export a PSD/PSB file to TIFF format.', "params": [{"name": 'input_filename', "type": 'str', "required": True, "description": ""}, {"name": 'output_filename', "type": 'str | None', "required": False, "description": ""}], "returns": "dict"},
            {"name": 'psd_convert_to_bmp', "description": 'Export a PSD/PSB file to BMP format.', "params": [{"name": 'input_filename', "type": 'str', "required": True, "description": ""}, {"name": 'output_filename', "type": 'str | None', "required": False, "description": ""}], "returns": "dict"},
            {"name": 'psd_convert_to_gif', "description": 'Export a PSD/PSB file to GIF format.', "params": [{"name": 'input_filename', "type": 'str', "required": True, "description": ""}, {"name": 'output_filename', "type": 'str | None', "required": False, "description": ""}], "returns": "dict"},
            {"name": 'psd_convert_to_pdf', "description": 'Export a PSD/PSB file to PDF format.', "params": [{"name": 'input_filename', "type": 'str', "required": True, "description": ""}, {"name": 'output_filename', "type": 'str | None', "required": False, "description": ""}], "returns": "dict"},
            {"name": 'psd_get_document_info', "description": 'Get PSD document dimensions, layer count, color mode, and bit depth.', "params": [{"name": 'input_filename', "type": 'str', "required": True, "description": ""}], "returns": "dict"},
            {"name": 'psd_list_layers', "description": 'List all layers in a PSD file with their names, types, visibility, and dimensions.', "params": [{"name": 'input_filename', "type": 'str', "required": True, "description": ""}], "returns": "dict"},
            {"name": 'psd_update_text_layer', "description": 'Update the text content of a text layer in a PSD file identified by name or index.', "params": [{"name": 'input_filename', "type": 'str', "required": True, "description": ""}, {"name": 'new_text', "type": 'str', "required": True, "description": ""}, {"name": 'layer_name', "type": 'str | None', "required": False, "description": ""}, {"name": 'layer_index', "type": 'int | None', "required": False, "description": ""}, {"name": 'output_filename', "type": 'str | None', "required": False, "description": ""}], "returns": "dict"},
            {"name": 'psd_flatten_image', "description": 'Flatten all layers in a PSD file into a single raster layer and export as PNG.', "params": [{"name": 'input_filename', "type": 'str', "required": True, "description": ""}, {"name": 'output_filename', "type": 'str | None', "required": False, "description": ""}], "returns": "dict"},
            {"name": 'psd_resize', "description": 'Resize a PSD canvas to the specified dimensions using Lanczos resampling.', "params": [{"name": 'input_filename', "type": 'str', "required": True, "description": ""}, {"name": 'width', "type": 'int', "required": True, "description": ""}, {"name": 'height', "type": 'int', "required": True, "description": ""}, {"name": 'output_filename', "type": 'str | None', "required": False, "description": ""}], "returns": "dict"},
            {"name": 'psd_crop', "description": 'Crop a PSD canvas to the specified rectangular region.', "params": [{"name": 'input_filename', "type": 'str', "required": True, "description": ""}, {"name": 'x', "type": 'int', "required": True, "description": ""}, {"name": 'y', "type": 'int', "required": True, "description": ""}, {"name": 'width', "type": 'int', "required": True, "description": ""}, {"name": 'height', "type": 'int', "required": True, "description": ""}, {"name": 'output_filename', "type": 'str | None', "required": False, "description": ""}], "returns": "dict"},
            {"name": 'psd_rotate', "description": 'Rotate a PSD image by 90, 180, or 270 degrees.', "params": [{"name": 'input_filename', "type": 'str', "required": True, "description": ""}, {"name": 'degrees', "type": 'int', "required": True, "description": ""}, {"name": 'output_filename', "type": 'str | None', "required": False, "description": ""}], "returns": "dict"},
            {"name": 'psd_add_text_watermark', "description": 'Add a semi-transparent text watermark to a PSD image using the Graphics API.', "params": [{"name": 'input_filename', "type": 'str', "required": True, "description": ""}, {"name": 'text', "type": 'str', "required": True, "description": ""}, {"name": 'opacity', "type": 'float | None', "required": False, "description": ""}, {"name": 'output_filename', "type": 'str | None', "required": False, "description": ""}], "returns": "dict"}
        ]

    def register_tools(self, mcp: "FastMCP") -> None:
        """Register all PSD tools with the FastMCP instance.

        Args:
            mcp: FastMCP server instance to register tools on.

        Returns:
            None.

        Raises:
            None.

        Example:
            >>> from mcp.server.fastmcp import FastMCP
            >>> mcp = FastMCP("test")
            >>> PsdPlugin().register_tools(mcp)
        """
        logger.debug("%s plugin registering tools. Platform: %s", "PSD", platform_hint())
        apply_license_for("aspose.psd")
        @mcp.tool()
        async def psd_convert_to_png(
            input_filename: str,
            output_filename: str | None = None,
        ) -> dict:
            """
            Convert a PSD/PSB image already stored on the server to PNG format.
        
            IMPORTANT:
            All *_filename parameters accept ONLY the bare filename (e.g. 'scan.jpg') — no path, no directory, no drive letter, no slash.
            The file MUST already exist in the server's ASPOSE_FILES_PATH folder before calling this tool.
            Do NOT ask the user to upload a file — files are pre‑placed in the server folder by the user.
            The output file is also written to the ASPOSE_FILES_PATH folder; the returned output_filename is the bare name only.
        
            Args:
                input_filename: bare filename of the PSD/PSB file to convert, e.g. 'design.psd'.
                output_filename: optional bare filename for the resulting PNG. If None, a temporary name is generated.
        
            Returns:
                dict: {
                    "status": "success" or "error",
                    "message": description of the result,
                    "output_filename": bare name of the written PNG file,
                    "output_path": absolute path to the written PNG file (as a string)
                }
        
            Raises:
                FileNotFoundError: if the input file does not exist in ASPOSE_FILES_PATH.
                Exception: any unexpected error raised by the Aspose.PSD library.
        
            Example:
                result = await psd_convert_to_png("logo.psd", "logo.png")
                # result["output_path"] contains the full path to the created PNG file.
            """
            # ----------------------------------------------------------------------
            # Resolve and validate input parameters (must be done before any Aspose import)
            # ----------------------------------------------------------------------
            from pathlib import Path
            from mcp_server.path_utils import get_safe_path, temp_output_path
            import logging
        
            logger = logging.getLogger(__name__)
        
            # Sanitize input filename (strip nulls, keep only the name part)
            input_filename = Path(input_filename.strip().replace("\x00", "")).name
            resolved_input = get_safe_path(input_filename)
            if not Path(resolved_input).is_file():
                raise FileNotFoundError(f"File not found: {input_filename}")
        
            # Sanitize optional output filename
            if output_filename is not None:
                output_filename = Path(output_filename.strip().replace("\x00", "")).name
                resolved_output = get_safe_path(output_filename)
            else:
                # Generate a temporary output file with .png extension
                resolved_output = str(temp_output_path("aspose_psd_result", ".png"))
                output_filename = Path(resolved_output).name
        
            # Ensure the output directory exists
            Path(resolved_output).parent.mkdir(parents=True, exist_ok=True)
        
            # ----------------------------------------------------------------------
            # Aspose.PSD processing
            # ----------------------------------------------------------------------
            try:
                # Lazy imports as required by the rules
                from aspose.psd import Image
                from aspose.psd.fileformats.psd import PsdImage
                from aspose.psd.imageoptions import PngOptions
                from aspose.psd.fileformats.png import PngColorType
                from aspose.pycore import cast
        
                with Image.load(str(resolved_input)) as image:
                    psd_image = cast(PsdImage, image)
                    opts = PngOptions()
                    opts.color_type = PngColorType.TRUECOLOR_WITH_ALPHA
                    psd_image.save(str(resolved_output), opts)
        
                logger.info(
                    "Converted PSD '%s' to PNG '%s'",
                    input_filename,
                    output_filename,
                )
                return {
                    "status": "success",
                    "message": f"File converted successfully to {output_filename}",
                    "output_filename": output_filename,
                    "output_path": resolved_output,
                }
        
            except Exception as exc:  # Catch any Aspose or IO errors
                logger.error("Error converting PSD to PNG: %s", exc)
                return {
                    "status": "error",
                    "message": str(exc),
                    "output_filename": output_filename,
                    "output_path": resolved_output,
                }

        @mcp.tool()
        async def psd_convert_to_jpeg(
            input_filename: str,
            output_filename: str | None = None,
            quality: int = 90,
        ) -> dict:
            """
            Convert a PSD/PSB file stored on the server to a JPEG image.
        
            IMPORTANT:
            * All *_filename parameters accept ONLY the bare filename (e.g. 'scan.jpg') — no path, no directory, no drive letter, no slash.
            * The file MUST already exist in the server's ASPOSE_FILES_PATH folder before calling this tool.
            * Do NOT ask the user to upload a file — files are pre‑placed in the server folder by the user.
            * The output file is also written to the ASPOSE_FILES_PATH folder; the returned output_filename is the bare name only.
        
            Args:
                input_filename: Bare filename of the PSD/PSB file to convert. Must exist in ASPOSE_FILES_PATH.
                output_filename: Optional bare filename for the resulting JPEG. If omitted, a temporary name is generated.
                quality: JPEG quality from 1 to 100. Defaults to 90.
        
            Returns:
                dict: {
                    "status": "success" | "error",
                    "message": str,
                    "output_filename": str   # bare name of the created JPEG (present only on success)
                }
        
            Raises:
                FileNotFoundError: If the input file does not exist.
                ValueError: If `quality` is outside the 1‑100 range.
        
            Example:
                result = await psd_convert_to_jpeg("example.psd", "example.jpg", quality=80)
                # result["output_filename"] == "example.jpg"
            """
            # ----------------------------------------------------------------------
            # Resolve and validate input filename
            # ----------------------------------------------------------------------
            from pathlib import Path
            from mcp_server.path_utils import get_safe_path, temp_output_path
            import logging
        
            logger = logging.getLogger(__name__)
        
            # sanitize input filename (strip nulls, whitespace, keep only the name)
            input_filename = Path(input_filename.strip().replace("\x00", "")).name
            resolved_input = get_safe_path(input_filename)
            if not Path(resolved_input).is_file():
                raise FileNotFoundError(f"File not found: {input_filename}")
        
            # ----------------------------------------------------------------------
            # Resolve output filename / path
            # ----------------------------------------------------------------------
            if output_filename is not None:
                output_filename = Path(output_filename.strip().replace("\x00", "")).name
                resolved_output = get_safe_path(output_filename)
            else:
                # generate a temporary filename with .jpg extension
                resolved_output = str(temp_output_path("aspose_psd_result", ".jpg"))
                output_filename = Path(resolved_output).name
        
            # ensure the output directory exists
            Path(resolved_output).parent.mkdir(parents=True, exist_ok=True)
        
            # ----------------------------------------------------------------------
            # Validate quality
            # ----------------------------------------------------------------------
            if not (1 <= quality <= 100):
                raise ValueError("quality must be between 1 and 100")
        
            try:
                # Lazy import of Aspose.PSD
                from aspose.psd import Image
                from aspose.psd.fileformats.psd import PsdImage
                from aspose.psd.imageoptions import JpegOptions
                from aspose.pycore import cast
        
                logger.debug(
                    "Converting PSD '%s' to JPEG '%s' with quality=%s",
                    input_filename,
                    output_filename,
                    quality,
                )
        
                with Image.load(str(resolved_input)) as image:
                    psd_image = cast(PsdImage, image)
                    opts = JpegOptions()
                    opts.quality = quality
                    psd_image.save(str(resolved_output), opts)
        
                return {
                    "status": "success",
                    "message": f"Converted '{input_filename}' to JPEG.",
                    "output_filename": output_filename,
                }
        
            except Exception as exc:  # pragma: no cover
                logger.exception("Failed to convert PSD to JPEG")
                return {"status": "error", "message": str(exc)}

        @mcp.tool()
        async def psd_convert_to_tiff(
            input_filename: str,
            output_filename: str | None = None,
        ) -> dict:
            """
            Convert a PSD/PSB image stored on the server to a TIFF file.
        
            IMPORTANT:
            * All *_filename parameters accept ONLY the bare filename (e.g. 'scan.jpg') — no path, no directory, no drive letter, no slash.
            * The file MUST already exist in the server's ASPOSE_FILES_PATH folder before calling this tool.
            * Do NOT ask the user to upload a file — files are pre‑placed in the server folder by the user.
            * The output file is also written to the ASPOSE_FILES_PATH folder; the returned output_filename is the bare name only.
        
            Args:
                input_filename: Bare filename of the PSD/PSB file to convert, e.g. "design.psd".
                output_filename: Optional bare filename for the resulting TIFF. If omitted, a name is generated
                                 from the input (e.g. "design.tiff").
        
            Returns:
                dict: {
                    "status": "success" | "error",
                    "message": str,
                    "output_filename": str,   # bare name of the written TIFF
                    "output_path": str        # absolute path to the written TIFF
                }
        
            Raises:
                FileNotFoundError: If the input file does not exist in ASPOSE_FILES_PATH.
                Exception: Any unexpected error raised by Aspose.PSD.
        
            Example:
                result = await psd_convert_to_tiff("logo.psd")
                # result["output_filename"] -> "logo.tiff"
            """
            # ----------------------------------------------------------------------
            # Resolve and validate input file
            # ----------------------------------------------------------------------
            from pathlib import Path
            from mcp_server.path_utils import get_safe_path, temp_output_path
            import logging
        
            logger = logging.getLogger(__name__)
        
            # sanitize the supplied filename (strip nulls, whitespace, keep only the name)
            input_filename = Path(input_filename.strip().replace("\x00", "")).name
            resolved_input = get_safe_path(input_filename)
            if not Path(resolved_input).is_file():
                raise FileNotFoundError(f"File not found: {input_filename}")
        
            # ----------------------------------------------------------------------
            # Determine output filename and resolve its path
            # ----------------------------------------------------------------------
            if output_filename is not None:
                output_filename = Path(output_filename.strip().replace("\x00", "")).name
            else:
                # auto‑generate from input stem
                output_filename = f"{Path(input_filename).stem}.tiff"
        
            resolved_output = get_safe_path(output_filename)
            Path(resolved_output).parent.mkdir(parents=True, exist_ok=True)
        
            # ----------------------------------------------------------------------
            # Perform conversion using Aspose.PSD
            # ----------------------------------------------------------------------
            try:
                # Lazy import of Aspose modules
                from aspose.psd import Image
                from aspose.psd.fileformats.psd import PsdImage
                from aspose.psd.imageoptions import TiffOptions
                from aspose.psd.fileformats.tiff.enums import TiffExpectedFormat
                from aspose.pycore import cast
        
                with Image.load(str(resolved_input)) as img:
                    psd_image = cast(PsdImage, img)
                    psd_image.save(str(resolved_output), TiffOptions(TiffExpectedFormat.DEFAULT))
        
                logger.info(
                    "Converted PSD '%s' to TIFF '%s'.",
                    input_filename,
                    output_filename,
                )
                return {
                    "status": "success",
                    "message": "Conversion completed successfully.",
                    "output_filename": output_filename,
                    "output_path": resolved_output,
                }
        
            except Exception as exc:  # pragma: no cover
                logger.error("Error converting PSD to TIFF: %s", exc)
                return {
                    "status": "error",
                    "message": str(exc),
                }

        @mcp.tool()
        async def psd_convert_to_bmp(
            input_filename: str,
            output_filename: str | None = None,
        ) -> dict:
            """
            Convert a PSD/PSB file stored on the server to BMP format.
        
            IMPORTANT:
            - All *_filename parameters accept ONLY the bare filename (e.g. 'scan.jpg') — no path, no directory, no drive letter, no slash.
            - The file MUST already exist in the server's ASPOSE_FILES_PATH folder before calling this tool.
            - Do NOT ask the user to upload a file — files are pre‑placed in the server folder by the user.
            - The output file is also written to the ASPOSE_FILES_PATH folder; the returned output_filename is the bare name only.
        
            Args:
                input_filename: Bare filename of the PSD/PSB file to convert, e.g. 'example.psd'.
                output_filename: Optional bare filename for the resulting BMP file. If omitted,
                                 a temporary name is generated.
        
            Returns:
                dict: {
                    "status": "success" or "error",
                    "message": description of the result,
                    "output_filename": bare name of the BMP file (present only on success)
                }
        
            Raises:
                FileNotFoundError: If the input file does not exist in ASPOSE_FILES_PATH.
                Exception: Any unexpected error raised by Aspose.PSD.
        
            Example:
                result = await psd_convert_to_bmp("my_image.psd", "my_image.bmp")
                # result -> {"status":"success","message":"Conversion completed","output_filename":"my_image.bmp"}
            """
            # ----------------------------------------------------------------------
            # Resolve and validate input file
            # ----------------------------------------------------------------------
            from pathlib import Path
            from mcp_server.path_utils import get_safe_path, temp_output_path
            import logging
        
            logger = logging.getLogger(__name__)
        
            # sanitize input filename (strip nulls, keep only the name)
            input_filename = Path(input_filename.strip().replace("\x00", "")).name
            resolved_input = get_safe_path(input_filename)
            if not Path(resolved_input).is_file():
                raise FileNotFoundError(f"File not found: {input_filename}")
        
            # ----------------------------------------------------------------------
            # Resolve output file
            # ----------------------------------------------------------------------
            if output_filename is not None:
                output_filename = Path(output_filename.strip().replace("\x00", "")).name
                resolved_output = get_safe_path(output_filename)
            else:
                # generate a temporary filename with .bmp suffix
                temp_path = temp_output_path("aspose_psd_result", ".bmp")
                resolved_output = str(temp_path)  # Aspose expects a plain string
                output_filename = Path(resolved_output).name
        
            # ensure output directory exists
            Path(resolved_output).parent.mkdir(parents=True, exist_ok=True)
        
            # ----------------------------------------------------------------------
            # Perform conversion using Aspose.PSD
            # ----------------------------------------------------------------------
            try:
                # Lazy import of Aspose modules
                from aspose.psd import Image
                from aspose.psd.fileformats.psd import PsdImage
                from aspose.psd.imageoptions import BmpOptions
                from aspose.pycore import cast
        
                with Image.load(str(resolved_input)) as img:
                    psd_image = cast(PsdImage, img)
                    psd_image.save(str(resolved_output), BmpOptions())
        
                logger.info(
                    "Converted PSD '%s' to BMP '%s'.",
                    input_filename,
                    output_filename,
                )
                return {
                    "status": "success",
                    "message": "Conversion completed successfully.",
                    "output_filename": output_filename,
                }
        
            except Exception as exc:  # pragma: no cover
                logger.error("Error converting PSD to BMP: %s", exc)
                return {"status": "error", "message": str(exc)}

        @mcp.tool()
        async def psd_convert_to_gif(
            input_filename: str,
            output_filename: str | None = None,
        ) -> dict:
            """
            Convert a PSD/PSB file stored on the server to an animated GIF.
        
            IMPORTANT:
            * All *_filename parameters accept ONLY the bare filename (e.g. 'scan.jpg') — no path, no directory, no drive letter, no slash.
            * The file MUST already exist in the server's ASPOSE_FILES_PATH folder before calling this tool.
            * Do NOT ask the user to upload a file — files are pre‑placed in the server folder by the user.
            * The output file is also written to the ASPOSE_FILES_PATH folder; the returned output_filename is the bare name only.
        
            Args:
                input_filename: Bare filename of the source PSD/PSB file, e.g. "design.psd".
                output_filename: Optional bare filename for the resulting GIF. If omitted, a temporary
                                 filename with a ".gif" extension will be generated.
        
            Returns:
                dict: {
                    "status": "success" | "error",
                    "message": str,
                    "output_filename": str   # bare name of the created GIF (present only on success)
                }
        
            Raises:
                FileNotFoundError: If the specified input file does not exist in ASPOSE_FILES_PATH.
                Exception: Any unexpected error raised by the Aspose.PSD library.
        
            Example:
                result = await psd_convert_to_gif("logo.psd", "logo.gif")
                # result -> {"status":"success","message":"Converted PSD to GIF.","output_filename":"logo.gif"}
            """
            # ----------------------------------------------------------------------
            # Resolve and validate input file
            # ----------------------------------------------------------------------
            from pathlib import Path
            from mcp_server.path_utils import get_safe_path, temp_output_path
            import logging
        
            logger = logging.getLogger(__name__)
        
            # sanitize input filename (strip nulls, keep only the name part)
            input_filename = Path(input_filename.strip().replace("\x00", "")).name
            resolved_input = get_safe_path(input_filename)
            if not Path(resolved_input).is_file():
                raise FileNotFoundError(f"File not found: {input_filename}")
        
            # ----------------------------------------------------------------------
            # Resolve output location
            # ----------------------------------------------------------------------
            if output_filename is not None:
                output_filename = Path(output_filename.strip().replace("\x00", "")).name
                resolved_output = get_safe_path(output_filename)
            else:
                # generate a temporary filename with .gif suffix
                temp_path = temp_output_path("aspose_psd_result", ".gif")
                resolved_output = str(temp_path)  # Aspose expects a plain str
                output_filename = Path(resolved_output).name
        
            # ensure the target directory exists
            Path(resolved_output).parent.mkdir(parents=True, exist_ok=True)
        
            # ----------------------------------------------------------------------
            # Perform conversion using Aspose.PSD
            # ----------------------------------------------------------------------
            try:
                # lazy import of Aspose modules
                from aspose.psd import Image
                from aspose.psd.fileformats.psd import PsdImage
                from aspose.psd.imageoptions import GifOptions
                from aspose.pycore import cast
        
                with Image.load(str(resolved_input)) as image:
                    psd_image = cast(PsdImage, image)
                    psd_image.save(str(resolved_output), GifOptions())
        
                return {
                    "status": "success",
                    "message": "Converted PSD to GIF.",
                    "output_filename": output_filename,
                }
        
            except Exception as exc:  # pragma: no cover
                logger.exception("Error converting PSD to GIF")
                return {"status": "error", "message": str(exc)}

        @mcp.tool()
        async def psd_convert_to_pdf(
            input_filename: str,
            output_filename: str | None = None,
        ) -> dict:
            """
            Convert a PSD/PSB file stored on the server to a PDF document.
        
            IMPORTANT:
            * All *_filename parameters accept ONLY the bare filename (e.g. 'scan.jpg') — no path, no directory, no drive letter, no slash.
            * The file MUST already exist in the server's ASPOSE_FILES_PATH folder before calling this tool.
            * Do NOT ask the user to upload a file — files are pre‑placed in the server folder by the user.
            * The output file is also written to the ASPOSE_FILES_PATH folder; the returned output_filename is the bare name only.
        
            Args:
                input_filename: Bare filename of the source PSD/PSB file, e.g. "design.psd".
                output_filename: Optional bare filename for the resulting PDF. If omitted, a name is derived from the input.
        
            Returns:
                dict: {
                    "status": "success" or "error",
                    "message": description of the result,
                    "output_filename": bare name of the created PDF (or empty string on error),
                    "output_path": absolute path to the created PDF (or empty string on error)
                }
        
            Raises:
                FileNotFoundError: If the specified input file does not exist in ASPOSE_FILES_PATH.
                Exception: Any unexpected error raised by the Aspose.PSD library.
        
            Example:
                >>> result = await psd_convert_to_pdf("example.psd")
                >>> result["status"]
                "success"
                >>> result["output_filename"]
                "example.pdf"
            """
            import logging
            from pathlib import Path
            from mcp_server.path_utils import get_safe_path, temp_output_path
        
            logger = logging.getLogger(__name__)
        
            # ---- Validate and resolve input file ----
            input_filename = Path(input_filename.strip().replace("\x00", "")).name
            resolved_input = get_safe_path(input_filename)
            if not Path(resolved_input).is_file():
                raise FileNotFoundError(f"File not found: {input_filename}")
        
            # ---- Prepare output filename and path ----
            if output_filename is not None:
                output_filename = Path(output_filename.strip().replace("\x00", "")).name
            else:
                output_filename = f"{Path(input_filename).stem}.pdf"
        
            resolved_output = (
                get_safe_path(output_filename)
                if output_filename
                else str(temp_output_path("aspose_psd_result", ".pdf"))
            )
            Path(resolved_output).parent.mkdir(parents=True, exist_ok=True)
        
            # ---- Aspose.PSD conversion ----
            try:
                from aspose.psd import Image
                from aspose.psd.fileformats.psd import PsdImage
                from aspose.psd.imageoptions import PdfOptions
                from aspose.pycore import cast
        
                with Image.load(str(resolved_input)) as image:
                    psd_image = cast(PsdImage, image)
                    psd_image.save(str(resolved_output), PdfOptions())
        
                logger.debug(
                    "Converted PSD '%s' to PDF '%s'",
                    input_filename,
                    output_filename,
                )
                return {
                    "status": "success",
                    "message": f"File converted successfully to {output_filename}.",
                    "output_filename": output_filename,
                    "output_path": resolved_output,
                }
            except Exception as exc:  # pragma: no cover
                logger.error("Error converting PSD to PDF: %s", exc)
                return {
                    "status": "error",
                    "message": str(exc),
                    "output_filename": "",
                    "output_path": "",
                }

        @mcp.tool()
        async def psd_get_document_info(input_filename: str) -> dict:
            """
            Retrieve basic document information from a PSD/PSB file stored on the server.
        
            IMPORTANT:
            All *_filename parameters accept ONLY the bare filename (e.g. 'scan.jpg') — no path, no directory, no drive letter, no slash.
            The file MUST already exist in the server's ASPOSE_FILES_PATH folder before calling this tool.
            Do NOT ask the user to upload a file — files are pre‑placed in the server folder by the user.
            The output file is also written to the ASPOSE_FILES_PATH folder; the returned output_filename is the bare name only.
        
            Args:
                input_filename: bare filename only, e.g. 'example.psd' — must already exist in ASPOSE_FILES_PATH.
        
            Returns:
                dict: {
                    "status": "success" | "error",
                    "message": str,
                    "width": int,
                    "height": int,
                    "layer_count": int,
                    "color_mode": str,
                    "bits_per_channel": int
                }
        
            Raises:
                FileNotFoundError: If the specified file does not exist in ASPOSE_FILES_PATH.
                Exception: Any unexpected error from Aspose.PSD.
        
            Example:
                result = await psd_get_document_info("sample.psd")
            """
            from pathlib import Path
            from mcp_server.path_utils import get_safe_path
            import logging
        
            logger = logging.getLogger(__name__)
        
            # Sanitize and resolve the input filename
            input_filename = Path(input_filename.strip().replace('\x00', '')).name
            resolved_input = get_safe_path(input_filename)
            if not Path(resolved_input).is_file():
                raise FileNotFoundError(f"File not found: {input_filename}")
        
            try:
                # Lazy import Aspose.PSD after validation
                from aspose.psd import Image
                from aspose.psd.fileformats.psd import PsdImage
                from aspose.pycore import cast
        
                with Image.load(str(resolved_input)) as img:
                    psd_image = cast(PsdImage, img)
                    width = psd_image.width
                    height = psd_image.height
                    layer_count = len(psd_image.layers)
                    color_mode = str(psd_image.color_mode)
                    bits_per_channel = psd_image.bits_per_channel
        
                return {
                    "status": "success",
                    "message": f"Retrieved document info for '{input_filename}'.",
                    "width": width,
                    "height": height,
                    "layer_count": layer_count,
                    "color_mode": color_mode,
                    "bits_per_channel": bits_per_channel,
                }
            except Exception as exc:
                logger.exception("Error retrieving PSD document info")
                return {"status": "error", "message": str(exc)}

        @mcp.tool()
        async def psd_list_layers(input_filename: str) -> dict:
            """
            List layers of a PSD/PSB file stored on the server.
        
            IMPORTANT:
            * All *_filename parameters accept ONLY the bare filename (e.g. 'scan.jpg') — no path, no directory, no drive letter, no slash.
            * The file MUST already exist in the server's ASPOSE_FILES_PATH folder before calling this tool.
            * Do NOT ask the user to upload a file — files are pre‑placed in the server folder by the user.
            * The output file is also written to the ASPOSE_FILES_PATH folder; the returned output_filename is the bare name only.
        
            Args:
                input_filename: bare filename only, e.g. 'design.psd' — must already exist in ASPOSE_FILES_PATH.
        
            Returns:
                dict: {
                    "status": "success" | "error",
                    "message": str,
                    "layers": list[dict]   # each dict contains index, name, type, visible, width, height, and optional text
                }
        
            Raises:
                FileNotFoundError: If the specified input file does not exist.
                Exception: For any unexpected errors raised by Aspose.
        
            Example:
                >>> result = await psd_list_layers("sample.psd")
                >>> if result["status"] == "success":
                ...     for layer in result["layers"]:
                ...            """
            # ------------------------------------------------------------------
            # Validate and resolve the input filename (must be a bare name)
            # ------------------------------------------------------------------
            from pathlib import Path
            from mcp_server.path_utils import get_safe_path, temp_output_path  # temp_output_path not used here but imported per pattern
            input_filename = Path(input_filename.strip().replace('\x00', '')).name
            resolved_input = get_safe_path(input_filename)
            if not Path(resolved_input).is_file():
                raise FileNotFoundError(f"File not found: {input_filename}")
        
            # ------------------------------------------------------------------
            # Lazy import of Aspose.PSD libraries
            # ------------------------------------------------------------------
            from aspose.psd import Image
            from aspose.psd.fileformats.psd import PsdImage
            from aspose.psd.fileformats.psd.layers import TextLayer
            from aspose.pycore import cast
            import logging
        
            logger = logging.getLogger(__name__)
        
            try:
                with Image.load(str(resolved_input)) as img:
                    psd_image = cast(PsdImage, img)
                    layer_info = []
                    for i, layer in enumerate(psd_image.layers):
                        info = {
                            "index": i,
                            "name": layer.name,
                            "type": type(layer).__name__,
                            "visible": layer.is_visible,
                            "width": layer.width,
                            "height": layer.height,
                        }
                        if isinstance(layer, TextLayer):
                            text_layer = cast(TextLayer, layer)
                            info["text"] = text_layer.text
                        layer_info.append(info)
        
                return {
                    "status": "success",
                    "message": f"Found {len(layer_info)} layer(s) in '{input_filename}'.",
                    "layers": layer_info,
                }
        
            except Exception as exc:  # Catch any Aspose or runtime errors
                logger.exception("Error listing PSD layers for %s", input_filename)
                return {"status": "error", "message": str(exc)}

        @mcp.tool()
        async def psd_update_text_layer(
            input_filename: str,
            new_text: str,
            layer_name: str | None = None,
            layer_index: int | None = None,
            output_filename: str | None = None,
        ) -> dict:
            """
            Update the text of a specific text layer inside a PSD/PSB file.
        
            IMPORTANT:
            * All *_filename parameters accept ONLY the bare filename (e.g. 'scan.psd') — no path, no directory, no drive letter, no slash.
            * The file MUST already exist in the server's ASPOSE_FILES_PATH folder before calling this tool.
            * Do NOT ask the user to upload a file — files are pre‑placed in the server folder by the user.
            * The output file is also written to the ASPOSE_FILES_PATH folder; the returned output_filename is the bare name only.
        
            Args:
                input_filename: Bare filename of the source PSD/PSB file, e.g. "design.psd".
                new_text: New text content that will replace the existing layer text.
                layer_name: Optional name of the text layer to update. The first layer whose name matches is used.
                layer_index: Optional zero‑based index of the layer to update. Used only when layer_name is None.
                output_filename: Optional bare filename for the resulting PSD/PSB. If omitted, a name is generated automatically.
        
            Returns:
                dict: {
                    "status": "success" | "error",
                    "message": str,
                    "output_filename": str,          # bare name of the written file (or empty on error)
                    "output_path": str,              # absolute path where the file was written (or empty on error)
                    "updated_layer": str | None      # name of the layer that was modified (or None)
                }
        
            Raises:
                FileNotFoundError: If the input file does not exist in ASPOSE_FILES_PATH.
                ValueError: If no matching text layer is found.
                Exception: Any unexpected error from the Aspose.PSD library.
        
            Example:
                result = await psd_update_text_layer(
                    input_filename="logo.psd",
                    new_text="New Company Name",
                    layer_name="CompanyName",
                    output_filename="logo_updated.psd"
                )
            """
            # ----------------------------------------------------------------------
            # Resolve and validate input / output filenames (no Aspose imports yet)
            # ----------------------------------------------------------------------
            from pathlib import Path
            from mcp_server.path_utils import get_safe_path, temp_output_path
            import logging
        
            logger = logging.getLogger(__name__)
        
            # sanitize input filename
            input_filename = Path(input_filename.strip().replace("\x00", "")).name
            resolved_input = get_safe_path(input_filename)
            if not Path(resolved_input).is_file():
                raise FileNotFoundError(f"File not found: {input_filename}")
        
            # sanitize optional output filename
            if output_filename is not None:
                output_filename = Path(output_filename.strip().replace("\x00", "")).name
                resolved_output = get_safe_path(output_filename)
            else:
                # generate a temporary output file inside ASPOSE_FILES_PATH
                resolved_output = str(temp_output_path("aspose_psd_result", ".psd"))
                output_filename = Path(resolved_output).name
        
            # ensure output directory exists
            Path(resolved_output).parent.mkdir(parents=True, exist_ok=True)
        
            # ----------------------------------------------------------------------
            # Aspose.PSD processing
            # ----------------------------------------------------------------------
            try:
                # Lazy Aspose imports
                from aspose.psd import Image
                from aspose.psd.fileformats.psd import PsdImage
                from aspose.psd.fileformats.psd.layers import TextLayer
                from aspose.psd.imageoptions import PsdOptions
                from aspose.pycore import cast
        
                updated_layer_name: str | None = None
        
                with Image.load(str(resolved_input)) as image:
                    psd_image = cast(PsdImage, image)
        
                    for i, layer in enumerate(psd_image.layers):
                        if not isinstance(layer, TextLayer):
                            continue
        
                        # layer name filter
                        if layer_name is not None and layer.name != layer_name:
                            continue
        
                        # layer index filter (only when name not supplied)
                        if layer_name is None and layer_index is not None and i != layer_index:
                            continue
        
                        text_layer = cast(TextLayer, layer)
                        text_layer.update_text(new_text)
                        updated_layer_name = layer.name
                        break
        
                    if updated_layer_name is None:
                        raise ValueError("No matching text layer found for the given criteria.")
        
                    psd_image.save(str(resolved_output), PsdOptions())
        
                return {
                    "status": "success",
                    "message": f"Text layer updated successfully; saved to '{output_filename}'.",
                    "output_filename": output_filename,
                    "output_path": resolved_output,
                    "updated_layer": updated_layer_name,
                }
        
            except Exception as exc:  # pragma: no cover
                logger.exception("Failed to update PSD text layer")
                return {
                    "status": "error",
                    "message": str(exc),
                    "output_filename": "",
                    "output_path": "",
                    "updated_layer": None,
                }

        @mcp.tool()
        async def psd_flatten_image(
            input_filename: str,
            output_filename: str | None = None,
        ) -> dict:
            """
            Flatten a PSD/PSB image and save it as a PNG.
        
            IMPORTANT:
            * All *_filename parameters accept ONLY the bare filename (e.g. 'scan.jpg') — no path, no directory, no drive letter, no slash.
            * The file MUST already exist in the server's ASPOSE_FILES_PATH folder before calling this tool.
            * Do NOT ask the user to upload a file — files are pre‑placed in the server folder by the user.
            * The output file is also written to the ASPOSE_FILES_PATH folder; the returned output_filename is the bare name only.
        
            Args:
                input_filename: Bare filename of the PSD/PSB file to process, e.g. "example.psd".
                output_filename: Optional bare filename for the resulting PNG. If None, a name is auto‑generated.
        
            Returns:
                dict: {
                    "status": "success" or "error",
                    "message": description of the result,
                    "output_filename": bare name of the written PNG (present only on success)
                }
        
            Raises:
                FileNotFoundError: If the input file does not exist in ASPOSE_FILES_PATH.
                Exception: Any unexpected error raised by the Aspose.PSD library.
        
            Example:
                result = await psd_flatten_image("design.psd")
                # result -> {"status":"success","message":"Image flattened","output_filename":"design_flat.png"}
            """
            import logging
            from pathlib import Path
            from mcp_server.path_utils import get_safe_path, temp_output_path
        
            logger = logging.getLogger(__name__)
        
            # ---- Validate and resolve input file ----
            input_filename = Path(input_filename.strip().replace('\x00', '')).name
            resolved_input = get_safe_path(input_filename)
            if not Path(resolved_input).is_file():
                raise FileNotFoundError(f"File not found: {input_filename}")
        
            # ---- Determine output filename and path ----
            if output_filename is not None:
                output_filename = Path(output_filename.strip().replace('\x00', '')).name
                resolved_output = get_safe_path(output_filename)
            else:
                # generate temporary output filename with .png suffix
                temp_path = temp_output_path("aspose_psd_result", ".png")
                resolved_output = str(temp_path)  # Aspose expects a plain string
                output_filename = Path(resolved_output).name
        
            # Ensure output directory exists
            Path(resolved_output).parent.mkdir(parents=True, exist_ok=True)
        
            try:
                # Lazy import of Aspose after all validation
                from aspose.psd import Image
                from aspose.psd.fileformats.psd import PsdImage
                from aspose.psd.imageoptions import PngOptions
                from aspose.pycore import cast
        
                # Load, flatten, and save
                with Image.load(str(resolved_input)) as img:
                    psd_image = cast(PsdImage, img)
                    psd_image.flatten_image()
                    psd_image.save(str(resolved_output), PngOptions())
        
                logger.info("Flattened PSD '%s' to PNG '%s'.", input_filename, output_filename)
                return {
                    "status": "success",
                    "message": f"Image '{input_filename}' flattened and saved as PNG.",
                    "output_filename": output_filename,
                }
        
            except Exception as exc:  # pragma: no cover
                logger.exception("Failed to flatten PSD '%s': %s", input_filename, exc)
                return {"status": "error", "message": str(exc)}

        @mcp.tool()
        async def psd_resize(
            input_filename: str,
            width: int,
            height: int,
            output_filename: str | None = None,
        ) -> dict:
            """
            Resize a PSD/PSB image to the specified dimensions.
        
            IMPORTANT:
            - All *_filename parameters accept ONLY the bare filename (e.g. 'scan.jpg') — no path, no directory, no drive letter, no slash.
            - The file MUST already exist in the server's ASPOSE_FILES_PATH folder before calling this tool.
            - Do NOT ask the user to upload a file — files are pre‑placed in the server folder by the user.
            - The output file is also written to the ASPOSE_FILES_PATH folder; the returned output_filename is the bare name only.
        
            Args:
                input_filename: PSD/PSB filename only, located in ASPOSE_FILES_PATH.
                width: Target width in pixels (must be > 0).
                height: Target height in pixels (must be > 0).
                output_filename: Optional output filename. If None, a name is auto‑generated.
        
            Returns:
                dict: {
                    "status": "success" | "error",
                    "message": str,
                    "output_filename": str,   # bare name of the written file
                    "output_path": str,       # absolute path on the server
                    "new_width": int,
                    "new_height": int
                }
        
            Raises:
                FileNotFoundError: If the input file does not exist.
                ValueError: If width or height are not positive integers.
                Exception: Propagated as an error status in the return dict.
        
            Example:
                result = await psd_resize("example.psd", 800, 600, "example_resized.psd")
            """
            # -------------------------------------------------------------------------
            # Imports that are NOT Aspose – must appear before any Aspose import
            # -------------------------------------------------------------------------
            import logging
            from pathlib import Path
            from mcp_server.path_utils import get_safe_path, temp_output_path
        
            logger = logging.getLogger(__name__)
        
            # -------------------------------------------------------------------------
            # Validate and resolve input filename
            # -------------------------------------------------------------------------
            input_filename = Path(input_filename.strip().replace("\x00", "")).name
            resolved_input = get_safe_path(input_filename)
            if not Path(resolved_input).is_file():
                raise FileNotFoundError(f"File not found: {input_filename}")
        
            # -------------------------------------------------------------------------
            # Validate dimensions
            # -------------------------------------------------------------------------
            if width <= 0 or height <= 0:
                raise ValueError("Width and height must be positive integers.")
        
            # -------------------------------------------------------------------------
            # Resolve output filename / path
            # -------------------------------------------------------------------------
            if output_filename is not None:
                output_filename = Path(output_filename.strip().replace("\x00", "")).name
        
            if output_filename:
                resolved_output = get_safe_path(output_filename)
            else:
                resolved_output = str(temp_output_path("aspose_psd_result", ".psd"))
                output_filename = Path(resolved_output).name
        
            Path(resolved_output).parent.mkdir(parents=True, exist_ok=True)
        
            # -------------------------------------------------------------------------
            # Aspose imports – lazy, inside the function
            # -------------------------------------------------------------------------
            from aspose.psd import Image, ResizeType
            from aspose.psd.fileformats.psd import PsdImage
            from aspose.psd.imageoptions import PsdOptions
            from aspose.pycore import cast
        
            # -------------------------------------------------------------------------
            # Perform resize
            # -------------------------------------------------------------------------
            try:
                with Image.load(str(resolved_input)) as img:
                    psd_image = cast(PsdImage, img)
                    psd_image.resize(width, height, ResizeType.LANCZOS_RESAMPLE)
                    psd_image.save(str(resolved_output), PsdOptions())
            except Exception as exc:  # pragma: no cover
                logger.exception("Failed to resize PSD image.")
                return {"status": "error", "message": str(exc)}
        
            return {
                "status": "success",
                "message": f"Resized PSD saved as {output_filename}",
                "output_filename": output_filename,
                "output_path": resolved_output,
                "new_width": width,
                "new_height": height,
            }

        @mcp.tool()
        async def psd_crop(
            input_filename: str,
            x: int,
            y: int,
            width: int,
            height: int,
            output_filename: str | None = None,
        ) -> dict:
            """
            Crop a region from a PSD/PSB file and save it as PNG.
        
            IMPORTANT:
            - All *_filename parameters accept ONLY the bare filename (e.g. 'scan.jpg') — no path,
              no directory, no drive letter, no slash.
            - The file MUST already exist in the server's ASPOSE_FILES_PATH folder before calling this tool.
            - Do NOT ask the user to upload a file — files are pre‑placed in the server folder by the user.
            - The output file is also written to the ASPOSE_FILES_PATH folder; the returned output_filename
              is the bare name only.
        
            Args:
                input_filename: Bare filename of the PSD/PSB to crop, e.g. "design.psd".
                x: Left offset of the crop region in pixels.
                y: Top offset of the crop region in pixels.
                width: Width of the crop region in pixels.
                height: Height of the crop region in pixels.
                output_filename: Optional bare filename for the cropped PNG.
                                 If None, a name like "<input>_cropped.png" is generated.
        
            Returns:
                dict: {
                    "status": "success" | "error",
                    "message": str,
                    "output_filename": str   # bare name of the written PNG (present only on success)
                }
        
            Raises:
                FileNotFoundError: If the input file does not exist.
                ValueError: If the crop rectangle is outside the image bounds.
                Exception: Any unexpected error from the Aspose library.
        
            Example:
                result = await psd_crop(
                    input_filename="logo.psd",
                    x=10,
                    y=20,
                    width=200,
                    height=100,
                    output_filename="logo_cropped.png"
                )
            """
            # ----------------------------------------------------------------------
            # Resolve and validate input file
            # ----------------------------------------------------------------------
            from pathlib import Path
            from mcp_server.path_utils import get_safe_path, temp_output_path
            import logging
        
            logger = logging.getLogger(__name__)
        
            # sanitize input filename (strip nulls, keep only name)
            input_filename = Path(input_filename.strip().replace("\x00", "")).name
            resolved_input = get_safe_path(input_filename)
            if not Path(resolved_input).is_file():
                raise FileNotFoundError(f"File not found: {input_filename}")
        
            # ----------------------------------------------------------------------
            # Resolve output filename / path
            # ----------------------------------------------------------------------
            if output_filename is not None:
                output_filename = Path(output_filename.strip().replace("\x00", "")).name
            else:
                output_filename = f"{Path(input_filename).stem}_cropped.png"
        
            resolved_output = get_safe_path(output_filename)
            Path(resolved_output).parent.mkdir(parents=True, exist_ok=True)
        
            # ----------------------------------------------------------------------
            # Perform cropping using Aspose.PSD
            # ----------------------------------------------------------------------
            try:
                # Lazy import of Aspose modules
                from aspose.psd import Image, Rectangle
                from aspose.psd.fileformats.psd import PsdImage
                from aspose.psd.imageoptions import PngOptions
                from aspose.pycore import cast
        
                with Image.load(str(resolved_input)) as img:
                    psd_image = cast(PsdImage, img)
        
                    # Validate crop rectangle against image dimensions
                    img_width = getattr(psd_image, "width", None)
                    img_height = getattr(psd_image, "height", None)
                    if img_width is not None and img_height is not None:
                        if x < 0 or y < 0 or width <= 0 or height <= 0:
                            raise ValueError("Crop dimensions must be positive and offsets non‑negative.")
                        if x + width > img_width or y + height > img_height:
                            raise ValueError(
                                f"Crop rectangle ({x},{y},{width},{height}) exceeds image bounds "
                                f"({img_width}x{img_height})."
                            )
        
                    psd_image.crop(Rectangle(x, y, width, height))
                    psd_image.save(str(resolved_output), PngOptions())
        
                return {
                    "status": "success",
                    "message": "PSD cropped and saved as PNG.",
                    "output_filename": output_filename,
                }
        
            except Exception as exc:  # catch Aspose and any other errors
                logger.exception("Error cropping PSD file")
                return {"status": "error", "message": str(exc)}

        @mcp.tool()
        async def psd_rotate(
            input_filename: str,
            degrees: int,
            output_filename: str | None = None,
        ) -> dict:
            """
            Rotate a PSD/PSB image and save as PNG.
        
            IMPORTANT:
            - All *_filename parameters accept ONLY the bare filename (e.g. 'scan.jpg') — no path, no directory, no drive letter, no slash.
            - The file MUST already exist in the server's ASPOSE_FILES_PATH folder before calling this tool.
            - Do NOT ask the user to upload a file — files are pre‑placed in the server folder by the user.
            - The output file is also written to the ASPOSE_FILES_PATH folder; the returned output_filename is the bare name only.
        
            Args:
                input_filename (str): PSD/PSB filename only, e.g. 'design.psd'.
                degrees (int): Rotation angle; must be 90, 180, or 270.
                output_filename (str | None, optional): Desired output filename. If None, a name is generated automatically with a .png extension.
        
            Returns:
                dict: {
                    "status": "success" | "error",
                    "message": str,
                    "output_filename": str,
                    "output_path": str
                }
        
            Raises:
                FileNotFoundError: If the input file does not exist.
                ValueError: If `degrees` is not one of the allowed values.
        
            Example:
                await psd_rotate("logo.psd", 90)
            """
            # ----------------------------------------------------------------------
            # Validate and resolve input file
            # ----------------------------------------------------------------------
            from pathlib import Path
            from mcp_server.path_utils import get_safe_path, temp_output_path
            import logging
        
            logger = logging.getLogger(__name__)
        
            # sanitize input filename (bare name only)
            input_filename = Path(input_filename.strip().replace("\x00", "")).name
            resolved_input = get_safe_path(input_filename)
            if not Path(resolved_input).is_file():
                raise FileNotFoundError(f"File not found: {input_filename}")
        
            # ----------------------------------------------------------------------
            # Prepare output filename and path
            # ----------------------------------------------------------------------
            if output_filename is not None:
                output_filename = Path(output_filename.strip().replace("\x00", "")).name
            else:
                output_filename = f"{Path(input_filename).stem}_rot{degrees}.png"
        
            resolved_output = get_safe_path(output_filename)
            # ensure the directory exists
            Path(resolved_output).parent.mkdir(parents=True, exist_ok=True)
        
            # ----------------------------------------------------------------------
            # Aspose imports (lazy)
            # ----------------------------------------------------------------------
            from aspose.psd import Image, RotateFlipType
            from aspose.psd.fileformats.psd import PsdImage
            from aspose.psd.imageoptions import PngOptions
            from aspose.pycore import cast
        
            # ----------------------------------------------------------------------
            # Validate rotation angle
            # ----------------------------------------------------------------------
            _rotate_map = {
                90: RotateFlipType.ROTATE90_FLIP_NONE,
                180: RotateFlipType.ROTATE180_FLIP_NONE,
                270: RotateFlipType.ROTATE270_FLIP_NONE,
            }
            if degrees not in _rotate_map:
                raise ValueError(f"degrees must be 90, 180, or 270 — got {degrees}")
        
            # ----------------------------------------------------------------------
            # Perform rotation
            # ----------------------------------------------------------------------
            try:
                with Image.load(str(resolved_input)) as img:
                    psd_image = cast(PsdImage, img)
                    psd_image.rotate_flip(_rotate_map[degrees])
                    psd_image.save(str(resolved_output), PngOptions())
            except Exception as exc:  # pragma: no cover
                logger.exception("Failed to rotate PSD image")
                return {"status": "error", "message": str(exc), "output_filename": "", "output_path": ""}
        
            # ----------------------------------------------------------------------
            # Return result
            # ----------------------------------------------------------------------
            return {
                "status": "success",
                "message": f"Image rotated {degrees}° and saved as PNG.",
                "output_filename": output_filename,
                "output_path": resolved_output,
            }

        @mcp.tool()
        async def psd_add_text_watermark(
            input_filename: str,
            text: str,
            opacity: float | None = None,
            output_filename: str | None = None,
        ) -> dict:
            """
            Add a semi‑transparent text watermark to a PSD/PSB image and save as PNG.
        
            IMPORTANT:
            All *_filename parameters accept ONLY the bare filename (e.g. 'scan.jpg') — no path, no directory, no drive letter, no slash.
            The file MUST already exist in the server's ASPOSE_FILES_PATH folder before calling this tool.
            Do NOT ask the user to upload a file — files are pre‑placed in the server folder by the user.
            The output file is also written to the ASPOSE_FILES_PATH folder; the returned output_filename is the bare name only.
        
            Args:
                input_filename: Bare filename of the PSD/PSB file to watermark. Must exist in ASPOSE_FILES_PATH.
                text: Watermark text to draw on the image.
                opacity: Optional opacity between 0.0 and 1.0. Defaults to 0.5 if omitted.
                output_filename: Optional bare filename for the resulting PNG. If omitted, a name is auto‑generated.
        
            Returns:
                dict: {
                    "status": "success" | "error",
                    "message": str,
                    "output_filename": str   # bare name of the written file (present only on success)
                }
        
            Raises:
                FileNotFoundError: If the input file does not exist.
                Exception: Any unexpected error from Aspose.PSD processing.
        
            Example:
                result = await psd_add_text_watermark(
                    input_filename="example.psd",
                    text="CONFIDENTIAL",
                    opacity=0.3,
                    output_filename="example_watermarked.png"
                )
            """
            import logging
            from pathlib import Path
            from mcp_server.path_utils import get_safe_path, temp_output_path
        
            logger = logging.getLogger(__name__)
        
            # ---- Validate and resolve input file ----
            input_filename = Path(input_filename.strip().replace('\x00', '')).name
            resolved_input = get_safe_path(input_filename)
            if not Path(resolved_input).is_file():
                raise FileNotFoundError(f"File not found: {input_filename}")
        
            # ---- Prepare output file ----
            if output_filename is not None:
                output_filename = Path(output_filename.strip().replace('\x00', '')).name
                resolved_output = get_safe_path(output_filename)
            else:
                # generate a temporary PNG filename
                resolved_output = str(temp_output_path("aspose_psd_result", ".png"))
                output_filename = Path(resolved_output).name
        
            # Ensure output directory exists
            Path(resolved_output).parent.mkdir(parents=True, exist_ok=True)
        
            # ---- Lazy Aspose imports (after path handling) ----
            from aspose.psd import Image, Graphics, Font, SolidBrush, Color, PointF
            from aspose.psd.fileformats.psd import PsdImage
            from aspose.psd.imageoptions import PngOptions
            from aspose.pycore import cast
        
            try:
                # Compute alpha channel from opacity (default 0.5)
                alpha = int((opacity if opacity is not None else 0.5) * 255)
        
                with Image.load(str(resolved_input)) as img:
                    psd_image = cast(PsdImage, img)
                    graphics = Graphics(psd_image)
        
                    # Simple font and brush setup
                    font = Font('Arial', 36)
                    brush = SolidBrush(Color.from_argb(alpha, 255, 0, 0))
        
                    # Position watermark roughly at centre‑left
                    x_pos = psd_image.width / 4
                    y_pos = psd_image.height / 2
        
                    graphics.draw_string(text, font, brush, PointF(x_pos, y_pos))
        
                    # Save as PNG
                    psd_image.save(str(resolved_output), PngOptions())
        
                return {
                    "status": "success",
                    "message": f"Watermark added and saved to {output_filename}",
                    "output_filename": output_filename,
                }
        
            except Exception as exc:  # pragma: no cover
                logger.exception("Failed to add watermark to PSD")
                return {
                    "status": "error",
                    "message": str(exc),
                }
