# Auto-generated by Aspose MCP Builder — do not edit manually.
# Product: Aspose.Slides for Python via .NET  Package: aspose-slides
from __future__ import annotations

import logging
from pathlib import Path

from mcp_server.plugin import AsposePlugin
from mcp_server.path_utils import (
    apply_license_for,
    get_safe_path,
    platform_hint,
    temp_output_path,
)

logger = logging.getLogger(__name__)

_FILENAME_IMPORT_NOTE = (
    "IMPORTANT: All *_filename parameters accept ONLY the bare filename "
    "(e.g. 'report.pptx') — no path, no directory, no drive letter, no slash. "
    "The file MUST already exist in the server's ASPOSE_FILES_PATH folder. "
    "Do NOT ask the user to upload a file — files are pre-placed in the server folder. "
    "Output files are also written to ASPOSE_FILES_PATH; returned output_filename is the bare name only."
)


class SlidesPlugin(AsposePlugin):
    product_name = "slides"
    pypi_package = "aspose-slides"
    min_version = "24.1.0"

    def health_check(self) -> bool:
        """Check that the Aspose Slides package is importable.

        Args:
            None

        Returns:
            True if the package imports without error, False otherwise.

        Raises:
            None. Import errors are caught and return False.

        Example:
            >>> plugin = SlidesPlugin()
            >>> isinstance(plugin.health_check(), bool)
            True
        """
        try:
            import aspose.slides as slides  # noqa: F401, PLC0415
            return True
        except Exception:
            return False

    def get_tool_manifest(self) -> list[dict[str, object]]:
        """Return metadata for all registered tools.

        Args:
            None

        Returns:
            List of dicts each with keys: name, description, params, returns.

        Raises:
            None.

        Example:
            >>> plugin = SlidesPlugin()
            >>> len(plugin.get_tool_manifest()) >= 22
            True
        """
        return [
            {"name": "slides_list_files", "description": "Lists all files in the ASPOSE_FILES_PATH directory, optionally filtering by file extension.", "params": [{"name": "extension_filter", "type": "str | None", "required": False, "description": ""}], "returns": "dict"},
            {"name": "slides_create_presentation", "description": "Creates a new PPTX presentation with an optional title and subtitle on the first slide.", "params": [{"name": "output_filename", "type": "str", "required": True, "description": ""}, {"name": "title", "type": "str | None", "required": False, "description": ""}, {"name": "subtitle", "type": "str | None", "required": False, "description": ""}], "returns": "dict"},
            {"name": "slides_convert_to_pdf", "description": "Converts a presentation to PDF format.", "params": [{"name": "input_filename", "type": "str", "required": True, "description": ""}, {"name": "output_filename", "type": "str | None", "required": False, "description": ""}], "returns": "dict"},
            {"name": "slides_convert_to_pptx", "description": "Converts a presentation (PPT, ODP, PPSX, etc.) to PPTX format.", "params": [{"name": "input_filename", "type": "str", "required": True, "description": ""}, {"name": "output_filename", "type": "str | None", "required": False, "description": ""}], "returns": "dict"},
            {"name": "slides_convert_to_html", "description": "Converts a presentation to HTML format.", "params": [{"name": "input_filename", "type": "str", "required": True, "description": ""}, {"name": "output_filename", "type": "str | None", "required": False, "description": ""}], "returns": "dict"},
            {"name": "slides_get_presentation_info", "description": "Returns slide count, title, author and slide dimensions from a presentation.", "params": [{"name": "input_filename", "type": "str", "required": True, "description": ""}], "returns": "dict"},
            {"name": "slides_extract_text", "description": "Extracts all text content from all slides in a presentation.", "params": [{"name": "input_filename", "type": "str", "required": True, "description": ""}], "returns": "dict"},
            {"name": "slides_export_slides_as_images", "description": "Exports every slide as a separate JPEG or PNG image file.", "params": [{"name": "input_filename", "type": "str", "required": True, "description": ""}, {"name": "image_format", "type": "str | None", "required": False, "description": ""}, {"name": "output_filename_prefix", "type": "str | None", "required": False, "description": ""}], "returns": "dict"},
            {"name": "slides_export_slide_as_image", "description": "Exports a single slide (0-based index) as a JPEG or PNG image.", "params": [{"name": "input_filename", "type": "str", "required": True, "description": ""}, {"name": "slide_index", "type": "int", "required": True, "description": ""}, {"name": "image_format", "type": "str | None", "required": False, "description": ""}, {"name": "output_filename", "type": "str | None", "required": False, "description": ""}], "returns": "dict"},
            {"name": "slides_export_slide_as_svg", "description": "Exports a single slide (0-based index) as an SVG file.", "params": [{"name": "input_filename", "type": "str", "required": True, "description": ""}, {"name": "slide_index", "type": "int", "required": True, "description": ""}, {"name": "output_filename", "type": "str | None", "required": False, "description": ""}], "returns": "dict"},
            {"name": "slides_add_slide", "description": "Appends a new blank slide to the end of a presentation.", "params": [{"name": "input_filename", "type": "str", "required": True, "description": ""}, {"name": "output_filename", "type": "str | None", "required": False, "description": ""}], "returns": "dict"},
            {"name": "slides_remove_slide", "description": "Removes a slide at the specified 0-based index.", "params": [{"name": "input_filename", "type": "str", "required": True, "description": ""}, {"name": "slide_index", "type": "int", "required": True, "description": ""}, {"name": "output_filename", "type": "str | None", "required": False, "description": ""}], "returns": "dict"},
            {"name": "slides_clone_slide", "description": "Clones an existing slide (0-based index) and appends the copy to the end.", "params": [{"name": "input_filename", "type": "str", "required": True, "description": ""}, {"name": "slide_index", "type": "int", "required": True, "description": ""}, {"name": "output_filename", "type": "str | None", "required": False, "description": ""}], "returns": "dict"},
            {"name": "slides_add_text_shape", "description": "Adds a text box (rectangle auto-shape) to a slide.", "params": [{"name": "input_filename", "type": "str", "required": True, "description": ""}, {"name": "slide_index", "type": "int", "required": True, "description": ""}, {"name": "text", "type": "str", "required": True, "description": ""}, {"name": "x", "type": "float | None", "required": False, "description": ""}, {"name": "y", "type": "float | None", "required": False, "description": ""}, {"name": "width", "type": "float | None", "required": False, "description": ""}, {"name": "height", "type": "float | None", "required": False, "description": ""}, {"name": "output_filename", "type": "str | None", "required": False, "description": ""}], "returns": "dict"},
            {"name": "slides_add_image_to_slide", "description": "Inserts an image file onto a slide as a picture frame.", "params": [{"name": "input_filename", "type": "str", "required": True, "description": ""}, {"name": "image_filename", "type": "str", "required": True, "description": ""}, {"name": "slide_index", "type": "int", "required": True, "description": ""}, {"name": "x", "type": "float | None", "required": False, "description": ""}, {"name": "y", "type": "float | None", "required": False, "description": ""}, {"name": "width", "type": "float | None", "required": False, "description": ""}, {"name": "height", "type": "float | None", "required": False, "description": ""}, {"name": "output_filename", "type": "str | None", "required": False, "description": ""}], "returns": "dict"},
            {"name": "slides_add_table_to_slide", "description": "Inserts a table onto a slide with the specified number of rows and columns.", "params": [{"name": "input_filename", "type": "str", "required": True, "description": ""}, {"name": "slide_index", "type": "int", "required": True, "description": ""}, {"name": "rows", "type": "int", "required": True, "description": ""}, {"name": "columns", "type": "int", "required": True, "description": ""}, {"name": "x", "type": "float | None", "required": False, "description": ""}, {"name": "y", "type": "float | None", "required": False, "description": ""}, {"name": "output_filename", "type": "str | None", "required": False, "description": ""}], "returns": "dict"},
            {"name": "slides_add_chart_to_slide", "description": "Inserts a chart onto a slide with an optional title.", "params": [{"name": "input_filename", "type": "str", "required": True, "description": ""}, {"name": "slide_index", "type": "int", "required": True, "description": ""}, {"name": "chart_type", "type": "str | None", "required": False, "description": ""}, {"name": "title", "type": "str | None", "required": False, "description": ""}, {"name": "x", "type": "float | None", "required": False, "description": ""}, {"name": "y", "type": "float | None", "required": False, "description": ""}, {"name": "output_filename", "type": "str | None", "required": False, "description": ""}], "returns": "dict"},
            {"name": "slides_set_slide_transition", "description": "Sets a transition effect on a slide (e.g. FADE, PUSH, WIPE, ZOOM, NONE).", "params": [{"name": "input_filename", "type": "str", "required": True, "description": ""}, {"name": "slide_index", "type": "int", "required": True, "description": ""}, {"name": "transition_type", "type": "str", "required": True, "description": ""}, {"name": "output_filename", "type": "str | None", "required": False, "description": ""}], "returns": "dict"},
            {"name": "slides_merge_presentations", "description": "Merges a second presentation into a base presentation by cloning all its slides.", "params": [{"name": "base_filename", "type": "str", "required": True, "description": ""}, {"name": "merge_filename", "type": "str", "required": True, "description": ""}, {"name": "output_filename", "type": "str | None", "required": False, "description": ""}], "returns": "dict"},
            {"name": "slides_protect_presentation", "description": "Sets an open password on a presentation.", "params": [{"name": "input_filename", "type": "str", "required": True, "description": ""}, {"name": "password", "type": "str", "required": True, "description": ""}, {"name": "output_filename", "type": "str | None", "required": False, "description": ""}], "returns": "dict"},
            {"name": "slides_unprotect_presentation", "description": "Removes the open password from a password-protected presentation.", "params": [{"name": "input_filename", "type": "str", "required": True, "description": ""}, {"name": "password", "type": "str", "required": True, "description": ""}, {"name": "output_filename", "type": "str | None", "required": False, "description": ""}], "returns": "dict"},
            {"name": "slides_find_and_replace_text", "description": "Replaces all occurrences of a text string across all slides.", "params": [{"name": "input_filename", "type": "str", "required": True, "description": ""}, {"name": "find_text", "type": "str", "required": True, "description": ""}, {"name": "replace_text", "type": "str", "required": True, "description": ""}, {"name": "output_filename", "type": "str | None", "required": False, "description": ""}], "returns": "dict"},
            {"name": "slides_reorder_slide", "description": "Moves a slide from one position to another (both indices are 0-based).", "params": [{"name": "input_filename", "type": "str", "required": True, "description": ""}, {"name": "from_index", "type": "int", "required": True, "description": ""}, {"name": "to_index", "type": "int", "required": True, "description": ""}, {"name": "output_filename", "type": "str | None", "required": False, "description": ""}], "returns": "dict"},
        ]

    def register_tools(self, mcp: "FastMCP") -> None:  # type: ignore[name-defined]
        """Register all SLIDES tools with the FastMCP instance.

        Args:
            mcp: FastMCP server instance to register tools on.

        Returns:
            None.

        Raises:
            None.

        Example:
            >>> from mcp.server.fastmcp import FastMCP
            >>> mcp = FastMCP("test")
            >>> SlidesPlugin().register_tools(mcp)
        """
        logger.debug("%s plugin registering tools. Platform: %s", "SLIDES", platform_hint())
        apply_license_for("aspose.slides")

        @mcp.tool()
        async def slides_list_files(extension_filter: str | None = None) -> dict:
            """List files already present in the server's ASPOSE_FILES_PATH folder.

            Call this first to discover available files — do NOT ask the user to upload.

            Args:
                extension_filter: Optional file extension to filter by, e.g. 'pptx'. None lists all files.

            Returns:
                dict: {"status": "success"|"error", "files": list[str], "folder_path": str, "message": str}

            Raises:
                None. Errors are returned as {"status": "error", "message": str}.

            Example:
                result = await slides_list_files("pptx")
            """
            import mcp_server.path_utils as _pu  # noqa: PLC0415

            resolved_folder = _pu.FILES_BASE_PATH
            if not resolved_folder or not Path(resolved_folder).is_dir():
                return {"status": "error", "message": "ASPOSE_FILES_PATH folder not found."}

            try:
                files: list[str] = []
                for entry in Path(resolved_folder).iterdir():
                    if not entry.is_file():
                        continue
                    if extension_filter:
                        normalized_ext = f".{extension_filter.lower().lstrip('.')}"
                        if entry.suffix.lower() != normalized_ext:
                            continue
                    files.append(entry.name)
                return {
                    "status": "success",
                    "message": f"Listed {len(files)} file(s).",
                    "files": sorted(files),
                    "folder_path": resolved_folder,
                }
            except Exception as exc:
                logger.exception("Error listing files.")
                return {"status": "error", "message": str(exc)}

        @mcp.tool()
        async def slides_create_presentation(
            output_filename: str,
            title: str | None = None,
            subtitle: str | None = None,
        ) -> dict:
            """Create a new PPTX presentation with an optional title and subtitle.

            IMPORTANT: All *_filename parameters accept ONLY the bare filename (e.g. 'deck.pptx').

            Args:
                output_filename: Bare filename for the new presentation, e.g. 'new_deck.pptx'.
                title: Optional title text for the first slide.
                subtitle: Optional subtitle text for the first slide.

            Returns:
                dict: {"status": "success"|"error", "message": str, "output_filename": str, "output_path": str}

            Raises:
                Exception: Any unexpected error from Aspose.Slides.

            Example:
                result = await slides_create_presentation("deck.pptx", title="Q1 Review")
            """
            output_filename = Path(output_filename.strip().replace("\x00", "")).name
            resolved_output = get_safe_path(output_filename)
            Path(resolved_output).parent.mkdir(parents=True, exist_ok=True)

            try:
                import aspose.slides as slides  # noqa: PLC0415

                with slides.Presentation() as pres:
                    slide = pres.slides[0]
                    if title:
                        shape = slide.shapes.add_auto_shape(
                            slides.ShapeType.RECTANGLE, 50, 80, 620, 120
                        )
                        shape.text_frame.text = title
                    if subtitle:
                        shape2 = slide.shapes.add_auto_shape(
                            slides.ShapeType.RECTANGLE, 50, 220, 620, 80
                        )
                        shape2.text_frame.text = subtitle
                    pres.save(str(resolved_output), slides.export.SaveFormat.PPTX)

                return {
                    "status": "success",
                    "message": f"Created presentation: {output_filename}",
                    "output_filename": output_filename,
                    "output_path": str(resolved_output),
                }
            except Exception as exc:
                logger.exception("Failed to create presentation")
                return {"status": "error", "message": str(exc), "output_filename": output_filename}

        @mcp.tool()
        async def slides_convert_to_pdf(
            input_filename: str,
            output_filename: str | None = None,
        ) -> dict:
            """Convert a presentation to PDF format.

            IMPORTANT: All *_filename parameters accept ONLY the bare filename (e.g. 'deck.pptx').

            Args:
                input_filename: Bare filename of the source presentation.
                output_filename: Bare filename for the resulting PDF. Auto-generated if omitted.

            Returns:
                dict: {"status": "success"|"error", "message": str, "output_filename": str, "output_path": str}

            Raises:
                FileNotFoundError: If the input file does not exist in ASPOSE_FILES_PATH.

            Example:
                result = await slides_convert_to_pdf("deck.pptx", "deck.pdf")
            """
            input_filename = Path(input_filename.strip().replace("\x00", "")).name
            resolved_input = get_safe_path(input_filename)
            if not Path(resolved_input).is_file():
                raise FileNotFoundError(
                    f"File not found: {input_filename!r}. "
                    f"Check ASPOSE_FILES_PATH ({platform_hint()})."
                )

            if output_filename is not None:
                output_filename = Path(output_filename.strip().replace("\x00", "")).name
            else:
                output_filename = Path(input_filename).stem + ".pdf"
            resolved_output = get_safe_path(output_filename)
            Path(resolved_output).parent.mkdir(parents=True, exist_ok=True)

            try:
                import aspose.slides as slides  # noqa: PLC0415

                with slides.Presentation(str(resolved_input)) as pres:
                    pres.save(str(resolved_output), slides.export.SaveFormat.PDF)

                return {
                    "status": "success",
                    "message": f"Converted {input_filename} → {output_filename}",
                    "output_filename": output_filename,
                    "output_path": str(resolved_output),
                }
            except Exception as exc:
                logger.exception("Failed to convert to PDF")
                return {"status": "error", "message": str(exc), "output_filename": output_filename}

        @mcp.tool()
        async def slides_convert_to_pptx(
            input_filename: str,
            output_filename: str | None = None,
        ) -> dict:
            """Convert a presentation (PPT, ODP, PPSX, etc.) to PPTX format.

            IMPORTANT: All *_filename parameters accept ONLY the bare filename.

            Args:
                input_filename: Bare filename of the source presentation.
                output_filename: Bare filename for the resulting PPTX. Auto-generated if omitted.

            Returns:
                dict: {"status": "success"|"error", "message": str, "output_filename": str, "output_path": str}

            Raises:
                FileNotFoundError: If the input file does not exist in ASPOSE_FILES_PATH.

            Example:
                result = await slides_convert_to_pptx("old.ppt", "modern.pptx")
            """
            input_filename = Path(input_filename.strip().replace("\x00", "")).name
            resolved_input = get_safe_path(input_filename)
            if not Path(resolved_input).is_file():
                raise FileNotFoundError(
                    f"File not found: {input_filename!r}. "
                    f"Check ASPOSE_FILES_PATH ({platform_hint()})."
                )

            if output_filename is not None:
                output_filename = Path(output_filename.strip().replace("\x00", "")).name
            else:
                output_filename = Path(input_filename).stem + ".pptx"
            resolved_output = get_safe_path(output_filename)
            Path(resolved_output).parent.mkdir(parents=True, exist_ok=True)

            try:
                import aspose.slides as slides  # noqa: PLC0415

                with slides.Presentation(str(resolved_input)) as pres:
                    pres.save(str(resolved_output), slides.export.SaveFormat.PPTX)

                return {
                    "status": "success",
                    "message": f"Converted {input_filename} → {output_filename}",
                    "output_filename": output_filename,
                    "output_path": str(resolved_output),
                }
            except Exception as exc:
                logger.exception("Failed to convert to PPTX")
                return {"status": "error", "message": str(exc), "output_filename": output_filename}

        @mcp.tool()
        async def slides_convert_to_html(
            input_filename: str,
            output_filename: str | None = None,
        ) -> dict:
            """Convert a presentation to HTML format.

            IMPORTANT: All *_filename parameters accept ONLY the bare filename.

            Args:
                input_filename: Bare filename of the source presentation.
                output_filename: Bare filename for the resulting HTML. Auto-generated if omitted.

            Returns:
                dict: {"status": "success"|"error", "message": str, "output_filename": str, "output_path": str}

            Raises:
                FileNotFoundError: If the input file does not exist in ASPOSE_FILES_PATH.

            Example:
                result = await slides_convert_to_html("deck.pptx", "deck.html")
            """
            input_filename = Path(input_filename.strip().replace("\x00", "")).name
            resolved_input = get_safe_path(input_filename)
            if not Path(resolved_input).is_file():
                raise FileNotFoundError(
                    f"File not found: {input_filename!r}. "
                    f"Check ASPOSE_FILES_PATH ({platform_hint()})."
                )

            if output_filename is not None:
                output_filename = Path(output_filename.strip().replace("\x00", "")).name
            else:
                output_filename = Path(input_filename).stem + ".html"
            resolved_output = get_safe_path(output_filename)
            Path(resolved_output).parent.mkdir(parents=True, exist_ok=True)

            try:
                import aspose.slides as slides  # noqa: PLC0415

                with slides.Presentation(str(resolved_input)) as pres:
                    pres.save(str(resolved_output), slides.export.SaveFormat.HTML)

                return {
                    "status": "success",
                    "message": f"Converted {input_filename} → {output_filename}",
                    "output_filename": output_filename,
                    "output_path": str(resolved_output),
                }
            except Exception as exc:
                logger.exception("Failed to convert to HTML")
                return {"status": "error", "message": str(exc), "output_filename": output_filename}

        @mcp.tool()
        async def slides_get_presentation_info(input_filename: str) -> dict:
            """Return slide count, title, author, and slide dimensions from a presentation.

            IMPORTANT: All *_filename parameters accept ONLY the bare filename.

            Args:
                input_filename: Bare filename of the presentation to inspect.

            Returns:
                dict: {"status": "success"|"error", "slide_count": int, "title": str,
                       "author": str, "slide_width": float, "slide_height": float, "message": str}

            Raises:
                FileNotFoundError: If the input file does not exist in ASPOSE_FILES_PATH.

            Example:
                result = await slides_get_presentation_info("deck.pptx")
                # result["slide_count"] is an integer
            """
            input_filename = Path(input_filename.strip().replace("\x00", "")).name
            resolved_input = get_safe_path(input_filename)
            if not Path(resolved_input).is_file():
                raise FileNotFoundError(
                    f"File not found: {input_filename!r}. "
                    f"Check ASPOSE_FILES_PATH ({platform_hint()})."
                )

            try:
                import aspose.slides as slides  # noqa: PLC0415

                with slides.Presentation(str(resolved_input)) as pres:
                    slide_count = len(pres.slides)
                    props = pres.document_properties
                    title = props.title or ""
                    author = props.author or ""
                    size = pres.slide_size.size
                    slide_width = float(size.width)
                    slide_height = float(size.height)

                return {
                    "status": "success",
                    "message": f"Info for {input_filename}",
                    "slide_count": slide_count,
                    "title": title,
                    "author": author,
                    "slide_width": slide_width,
                    "slide_height": slide_height,
                }
            except Exception as exc:
                logger.exception("Failed to get presentation info")
                return {"status": "error", "message": str(exc)}

        @mcp.tool()
        async def slides_extract_text(input_filename: str) -> dict:
            """Extract all text content from all slides in a presentation.

            Uses SlideUtil.get_all_text_frames for comprehensive extraction.

            IMPORTANT: All *_filename parameters accept ONLY the bare filename.

            Args:
                input_filename: Bare filename of the presentation.

            Returns:
                dict: {"status": "success"|"error", "text": str, "slide_count": int, "message": str}

            Raises:
                FileNotFoundError: If the input file does not exist in ASPOSE_FILES_PATH.

            Example:
                result = await slides_extract_text("deck.pptx")
                # result["text"] contains all extracted text
            """
            input_filename = Path(input_filename.strip().replace("\x00", "")).name
            resolved_input = get_safe_path(input_filename)
            if not Path(resolved_input).is_file():
                raise FileNotFoundError(
                    f"File not found: {input_filename!r}. "
                    f"Check ASPOSE_FILES_PATH ({platform_hint()})."
                )

            try:
                import aspose.slides as slides  # noqa: PLC0415
                import aspose.slides.util as util  # noqa: PLC0415

                with slides.Presentation(str(resolved_input)) as pres:
                    slide_count = len(pres.slides)
                    text_frames = util.SlideUtil.get_all_text_frames(pres, True)
                    parts: list[str] = []
                    for tf in text_frames:
                        for para in tf.paragraphs:
                            if para.text.strip():
                                parts.append(para.text)
                    extracted = "\n".join(parts)

                return {
                    "status": "success",
                    "message": f"Extracted text from {slide_count} slide(s).",
                    "slide_count": slide_count,
                    "text": extracted,
                }
            except Exception as exc:
                logger.exception("Failed to extract text")
                return {"status": "error", "message": str(exc)}

        @mcp.tool()
        async def slides_export_slides_as_images(
            input_filename: str,
            image_format: str | None = None,
            output_filename_prefix: str | None = None,
        ) -> dict:
            """Export every slide as a separate image file (JPEG or PNG).

            Each slide is exported via slide.get_thumbnail(1, 1).
            Slide indices are 0-based in code; file names are 1-based for readability.

            IMPORTANT: All *_filename parameters accept ONLY the bare filename.

            Args:
                input_filename: Bare filename of the source presentation.
                image_format: 'jpeg' or 'png' (default: 'jpeg').
                output_filename_prefix: Prefix for output files (default: stem of input).

            Returns:
                dict: {"status": "success"|"error", "output_files": list[str],
                       "output_paths": list[str], "slide_count": int, "message": str}

            Raises:
                FileNotFoundError: If the input file does not exist in ASPOSE_FILES_PATH.

            Example:
                result = await slides_export_slides_as_images("deck.pptx", image_format="jpeg")
            """
            input_filename = Path(input_filename.strip().replace("\x00", "")).name
            resolved_input = get_safe_path(input_filename)
            if not Path(resolved_input).is_file():
                raise FileNotFoundError(
                    f"File not found: {input_filename!r}. "
                    f"Check ASPOSE_FILES_PATH ({platform_hint()})."
                )

            fmt = (image_format or "jpeg").lower().strip()
            if fmt not in ("jpeg", "jpg", "png"):
                fmt = "jpeg"
            ext = "jpg" if fmt in ("jpeg", "jpg") else "png"
            prefix = output_filename_prefix or Path(input_filename).stem

            try:
                import aspose.slides as slides  # noqa: PLC0415
                import aspose.pydrawing as drawing  # noqa: PLC0415
                import os as _os  # noqa: PLC0415
                from PIL import Image as _PILImage  # noqa: PLC0415

                pil_format = "JPEG" if ext == "jpg" else "PNG"
                output_files: list[str] = []
                output_paths: list[str] = []

                with slides.Presentation(str(resolved_input)) as pres:
                    slide_count = len(pres.slides)
                    for i, sl in enumerate(pres.slides):
                        out_name = f"{prefix}_slide_{i + 1}.{ext}"
                        out_path = get_safe_path(out_name)
                        img = sl.get_image(drawing.Size(960, 720))
                        tmp_png = str(out_path) + ".tmp.png"
                        img.save(tmp_png)
                        pil_img = _PILImage.open(tmp_png).convert("RGB")
                        pil_img.save(str(out_path), pil_format)
                        _os.remove(tmp_png)
                        output_files.append(out_name)
                        output_paths.append(str(out_path))

                return {
                    "status": "success",
                    "message": f"Exported {slide_count} slide(s) as {ext.upper()} images.",
                    "slide_count": slide_count,
                    "output_files": output_files,
                    "output_paths": output_paths,
                }
            except Exception as exc:
                logger.exception("Failed to export slides as images")
                return {"status": "error", "message": str(exc)}

        @mcp.tool()
        async def slides_export_slide_as_image(
            input_filename: str,
            slide_index: int,
            image_format: str | None = None,
            output_filename: str | None = None,
        ) -> dict:
            """Export a single slide (0-based index) as a JPEG or PNG image.

            Uses slide.get_thumbnail(1, 1) for rendering.
            Slide indexing is 0-based: slide_index=0 is the first slide.

            IMPORTANT: All *_filename parameters accept ONLY the bare filename.

            Args:
                input_filename: Bare filename of the source presentation.
                slide_index: 0-based index of the slide to export.
                image_format: 'jpeg' or 'png' (default: 'jpeg').
                output_filename: Bare output filename. Auto-generated if omitted.

            Returns:
                dict: {"status": "success"|"error", "message": str, "output_filename": str, "output_path": str}

            Raises:
                FileNotFoundError: If the input file does not exist in ASPOSE_FILES_PATH.
                IndexError: If slide_index is out of range.

            Example:
                result = await slides_export_slide_as_image("deck.pptx", 0, "jpeg", "slide_1.jpg")
            """
            input_filename = Path(input_filename.strip().replace("\x00", "")).name
            resolved_input = get_safe_path(input_filename)
            if not Path(resolved_input).is_file():
                raise FileNotFoundError(
                    f"File not found: {input_filename!r}. "
                    f"Check ASPOSE_FILES_PATH ({platform_hint()})."
                )

            fmt = (image_format or "jpeg").lower().strip()
            ext = "jpg" if fmt in ("jpeg", "jpg") else "png"

            if output_filename is not None:
                output_filename = Path(output_filename.strip().replace("\x00", "")).name
            else:
                output_filename = f"{Path(input_filename).stem}_slide_{slide_index + 1}.{ext}"
            resolved_output = get_safe_path(output_filename)

            try:
                import aspose.slides as slides  # noqa: PLC0415
                import aspose.pydrawing as drawing  # noqa: PLC0415
                import io as _io  # noqa: PLC0415
                from PIL import Image as _PILImage  # noqa: PLC0415

                with slides.Presentation(str(resolved_input)) as pres:
                    if slide_index < 0 or slide_index >= len(pres.slides):
                        raise IndexError(
                            f"slide_index {slide_index} out of range for "
                            f"{len(pres.slides)} slide(s)."
                        )
                    img = pres.slides[slide_index].get_image(drawing.Size(960, 720))
                    # Save as PNG bytes first (the only natively supported format)
                    tmp_path = str(resolved_output) + ".tmp.png"
                    img.save(tmp_path)
                    # Convert to requested format using Pillow
                    pil_img = _PILImage.open(tmp_path).convert("RGB")
                    pil_format = "JPEG" if ext == "jpg" else "PNG"
                    pil_img.save(str(resolved_output), pil_format)
                    import os as _os  # noqa: PLC0415
                    _os.remove(tmp_path)

                return {
                    "status": "success",
                    "message": f"Exported slide {slide_index} → {output_filename}",
                    "output_filename": output_filename,
                    "output_path": str(resolved_output),
                }
            except (FileNotFoundError, IndexError):
                raise
            except Exception as exc:
                logger.exception("Failed to export slide as image")
                return {"status": "error", "message": str(exc), "output_filename": output_filename}

        @mcp.tool()
        async def slides_export_slide_as_svg(
            input_filename: str,
            slide_index: int,
            output_filename: str | None = None,
        ) -> dict:
            """Export a single slide (0-based index) as an SVG file.

            Uses slide.write_as_svg(file_object). SVG export is per-slide only.
            Slide indexing is 0-based: slide_index=0 is the first slide.

            IMPORTANT: All *_filename parameters accept ONLY the bare filename.

            Args:
                input_filename: Bare filename of the source presentation.
                slide_index: 0-based index of the slide to export.
                output_filename: Bare output SVG filename. Auto-generated if omitted.

            Returns:
                dict: {"status": "success"|"error", "message": str, "output_filename": str, "output_path": str}

            Raises:
                FileNotFoundError: If the input file does not exist in ASPOSE_FILES_PATH.

            Example:
                result = await slides_export_slide_as_svg("deck.pptx", 0, "slide_1.svg")
            """
            input_filename = Path(input_filename.strip().replace("\x00", "")).name
            resolved_input = get_safe_path(input_filename)
            if not Path(resolved_input).is_file():
                raise FileNotFoundError(
                    f"File not found: {input_filename!r}. "
                    f"Check ASPOSE_FILES_PATH ({platform_hint()})."
                )

            if output_filename is not None:
                output_filename = Path(output_filename.strip().replace("\x00", "")).name
            else:
                output_filename = f"{Path(input_filename).stem}_slide_{slide_index + 1}.svg"
            resolved_output = get_safe_path(output_filename)

            try:
                import aspose.slides as slides  # noqa: PLC0415

                with slides.Presentation(str(resolved_input)) as pres:
                    if slide_index < 0 or slide_index >= len(pres.slides):
                        raise IndexError(
                            f"slide_index {slide_index} out of range for "
                            f"{len(pres.slides)} slide(s)."
                        )
                    with open(str(resolved_output), "wb") as f:
                        pres.slides[slide_index].write_as_svg(f)

                return {
                    "status": "success",
                    "message": f"Exported slide {slide_index} → {output_filename}",
                    "output_filename": output_filename,
                    "output_path": str(resolved_output),
                }
            except (FileNotFoundError, IndexError):
                raise
            except Exception as exc:
                logger.exception("Failed to export slide as SVG")
                return {"status": "error", "message": str(exc), "output_filename": output_filename}

        @mcp.tool()
        async def slides_add_slide(
            input_filename: str,
            output_filename: str | None = None,
        ) -> dict:
            """Append a new blank slide to the end of a presentation.

            IMPORTANT: All *_filename parameters accept ONLY the bare filename.

            Args:
                input_filename: Bare filename of the source presentation.
                output_filename: Bare output filename. Auto-generated if omitted.

            Returns:
                dict: {"status": "success"|"error", "message": str, "output_filename": str,
                       "output_path": str, "new_slide_count": int}

            Raises:
                FileNotFoundError: If the input file does not exist in ASPOSE_FILES_PATH.

            Example:
                result = await slides_add_slide("deck.pptx", "deck_updated.pptx")
            """
            input_filename = Path(input_filename.strip().replace("\x00", "")).name
            resolved_input = get_safe_path(input_filename)
            if not Path(resolved_input).is_file():
                raise FileNotFoundError(
                    f"File not found: {input_filename!r}. "
                    f"Check ASPOSE_FILES_PATH ({platform_hint()})."
                )

            if output_filename is not None:
                output_filename = Path(output_filename.strip().replace("\x00", "")).name
            else:
                stem = Path(input_filename).stem
                output_filename = f"{stem}_with_slide{Path(input_filename).suffix}"
            resolved_output = get_safe_path(output_filename)
            Path(resolved_output).parent.mkdir(parents=True, exist_ok=True)

            try:
                import aspose.slides as slides  # noqa: PLC0415

                with slides.Presentation(str(resolved_input)) as pres:
                    layout = pres.layout_slides.get_by_type(slides.SlideLayoutType.BLANK)
                    pres.slides.add_empty_slide(layout)
                    new_count = len(pres.slides)
                    pres.save(str(resolved_output), slides.export.SaveFormat.PPTX)

                return {
                    "status": "success",
                    "message": f"Added blank slide. Total slides: {new_count}.",
                    "output_filename": output_filename,
                    "output_path": str(resolved_output),
                    "new_slide_count": new_count,
                }
            except Exception as exc:
                logger.exception("Failed to add slide")
                return {"status": "error", "message": str(exc), "output_filename": output_filename}

        @mcp.tool()
        async def slides_remove_slide(
            input_filename: str,
            slide_index: int,
            output_filename: str | None = None,
        ) -> dict:
            """Remove a slide at the specified 0-based index.

            Slide indexing is 0-based: slide_index=0 removes the first slide.

            IMPORTANT: All *_filename parameters accept ONLY the bare filename.

            Args:
                input_filename: Bare filename of the source presentation.
                slide_index: 0-based index of the slide to remove.
                output_filename: Bare output filename. Auto-generated if omitted.

            Returns:
                dict: {"status": "success"|"error", "message": str, "output_filename": str,
                       "output_path": str, "new_slide_count": int}

            Raises:
                FileNotFoundError: If the input file does not exist in ASPOSE_FILES_PATH.

            Example:
                result = await slides_remove_slide("deck.pptx", 1, "deck_trimmed.pptx")
            """
            input_filename = Path(input_filename.strip().replace("\x00", "")).name
            resolved_input = get_safe_path(input_filename)
            if not Path(resolved_input).is_file():
                raise FileNotFoundError(
                    f"File not found: {input_filename!r}. "
                    f"Check ASPOSE_FILES_PATH ({platform_hint()})."
                )

            if output_filename is not None:
                output_filename = Path(output_filename.strip().replace("\x00", "")).name
            else:
                stem = Path(input_filename).stem
                output_filename = f"{stem}_removed{Path(input_filename).suffix}"
            resolved_output = get_safe_path(output_filename)
            Path(resolved_output).parent.mkdir(parents=True, exist_ok=True)

            try:
                import aspose.slides as slides  # noqa: PLC0415

                with slides.Presentation(str(resolved_input)) as pres:
                    if slide_index < 0 or slide_index >= len(pres.slides):
                        raise IndexError(
                            f"slide_index {slide_index} out of range for "
                            f"{len(pres.slides)} slide(s)."
                        )
                    pres.slides.remove_at(slide_index)
                    new_count = len(pres.slides)
                    pres.save(str(resolved_output), slides.export.SaveFormat.PPTX)

                return {
                    "status": "success",
                    "message": f"Removed slide {slide_index}. Remaining slides: {new_count}.",
                    "output_filename": output_filename,
                    "output_path": str(resolved_output),
                    "new_slide_count": new_count,
                }
            except (FileNotFoundError, IndexError):
                raise
            except Exception as exc:
                logger.exception("Failed to remove slide")
                return {"status": "error", "message": str(exc), "output_filename": output_filename}

        @mcp.tool()
        async def slides_clone_slide(
            input_filename: str,
            slide_index: int,
            output_filename: str | None = None,
        ) -> dict:
            """Clone a slide (0-based index) and append the copy to the end.

            Uses pres.slides.add_clone(source_slide).
            Slide indexing is 0-based: slide_index=0 clones the first slide.

            IMPORTANT: All *_filename parameters accept ONLY the bare filename.

            Args:
                input_filename: Bare filename of the source presentation.
                slide_index: 0-based index of the slide to clone.
                output_filename: Bare output filename. Auto-generated if omitted.

            Returns:
                dict: {"status": "success"|"error", "message": str, "output_filename": str,
                       "output_path": str, "new_slide_count": int}

            Raises:
                FileNotFoundError: If the input file does not exist in ASPOSE_FILES_PATH.

            Example:
                result = await slides_clone_slide("deck.pptx", 0, "deck_with_clone.pptx")
            """
            input_filename = Path(input_filename.strip().replace("\x00", "")).name
            resolved_input = get_safe_path(input_filename)
            if not Path(resolved_input).is_file():
                raise FileNotFoundError(
                    f"File not found: {input_filename!r}. "
                    f"Check ASPOSE_FILES_PATH ({platform_hint()})."
                )

            if output_filename is not None:
                output_filename = Path(output_filename.strip().replace("\x00", "")).name
            else:
                stem = Path(input_filename).stem
                output_filename = f"{stem}_cloned{Path(input_filename).suffix}"
            resolved_output = get_safe_path(output_filename)
            Path(resolved_output).parent.mkdir(parents=True, exist_ok=True)

            try:
                import aspose.slides as slides  # noqa: PLC0415

                with slides.Presentation(str(resolved_input)) as pres:
                    if slide_index < 0 or slide_index >= len(pres.slides):
                        raise IndexError(
                            f"slide_index {slide_index} out of range for "
                            f"{len(pres.slides)} slide(s)."
                        )
                    pres.slides.add_clone(pres.slides[slide_index])
                    new_count = len(pres.slides)
                    pres.save(str(resolved_output), slides.export.SaveFormat.PPTX)

                return {
                    "status": "success",
                    "message": f"Cloned slide {slide_index}. Total slides: {new_count}.",
                    "output_filename": output_filename,
                    "output_path": str(resolved_output),
                    "new_slide_count": new_count,
                }
            except (FileNotFoundError, IndexError):
                raise
            except Exception as exc:
                logger.exception("Failed to clone slide")
                return {"status": "error", "message": str(exc), "output_filename": output_filename}

        @mcp.tool()
        async def slides_add_text_shape(
            input_filename: str,
            slide_index: int,
            text: str,
            x: float | None = None,
            y: float | None = None,
            width: float | None = None,
            height: float | None = None,
            output_filename: str | None = None,
        ) -> dict:
            """Add a text box (rectangle auto-shape) to a slide.

            Slide indexing is 0-based. Position/size in points (1 pt ≈ 1/72 inch).
            Default position: x=50, y=50, width=400, height=100.

            IMPORTANT: All *_filename parameters accept ONLY the bare filename.

            Args:
                input_filename: Bare filename of the source presentation.
                slide_index: 0-based index of the target slide.
                text: Text content for the shape.
                x: Left position in points (default: 50).
                y: Top position in points (default: 50).
                width: Shape width in points (default: 400).
                height: Shape height in points (default: 100).
                output_filename: Bare output filename. Auto-generated if omitted.

            Returns:
                dict: {"status": "success"|"error", "message": str, "output_filename": str, "output_path": str}

            Raises:
                FileNotFoundError: If the input file does not exist in ASPOSE_FILES_PATH.

            Example:
                result = await slides_add_text_shape("deck.pptx", 0, "Hello World")
            """
            input_filename = Path(input_filename.strip().replace("\x00", "")).name
            resolved_input = get_safe_path(input_filename)
            if not Path(resolved_input).is_file():
                raise FileNotFoundError(
                    f"File not found: {input_filename!r}. "
                    f"Check ASPOSE_FILES_PATH ({platform_hint()})."
                )

            if output_filename is not None:
                output_filename = Path(output_filename.strip().replace("\x00", "")).name
            else:
                stem = Path(input_filename).stem
                output_filename = f"{stem}_text{Path(input_filename).suffix}"
            resolved_output = get_safe_path(output_filename)
            Path(resolved_output).parent.mkdir(parents=True, exist_ok=True)

            try:
                import aspose.slides as slides  # noqa: PLC0415

                pos_x = float(x if x is not None else 50)
                pos_y = float(y if y is not None else 50)
                pos_w = float(width if width is not None else 400)
                pos_h = float(height if height is not None else 100)

                with slides.Presentation(str(resolved_input)) as pres:
                    if slide_index < 0 or slide_index >= len(pres.slides):
                        raise IndexError(
                            f"slide_index {slide_index} out of range for "
                            f"{len(pres.slides)} slide(s)."
                        )
                    slide = pres.slides[slide_index]
                    shape = slide.shapes.add_auto_shape(
                        slides.ShapeType.RECTANGLE, pos_x, pos_y, pos_w, pos_h
                    )
                    shape.text_frame.text = text
                    pres.save(str(resolved_output), slides.export.SaveFormat.PPTX)

                return {
                    "status": "success",
                    "message": f"Added text shape to slide {slide_index}.",
                    "output_filename": output_filename,
                    "output_path": str(resolved_output),
                }
            except (FileNotFoundError, IndexError):
                raise
            except Exception as exc:
                logger.exception("Failed to add text shape")
                return {"status": "error", "message": str(exc), "output_filename": output_filename}

        @mcp.tool()
        async def slides_add_image_to_slide(
            input_filename: str,
            image_filename: str,
            slide_index: int,
            x: float | None = None,
            y: float | None = None,
            width: float | None = None,
            height: float | None = None,
            output_filename: str | None = None,
        ) -> dict:
            """Insert an image file onto a slide as a picture frame.

            Image is first registered with pres.images.add_image(bytes), then
            added via slide.shapes.add_picture_frame(). File path is NOT passed
            directly to add_picture_frame.

            IMPORTANT: All *_filename parameters accept ONLY the bare filename.

            Args:
                input_filename: Bare filename of the source presentation.
                image_filename: Bare filename of the image to insert (from ASPOSE_FILES_PATH).
                slide_index: 0-based index of the target slide.
                x: Left position in points (default: 50).
                y: Top position in points (default: 50).
                width: Frame width in points (default: 300).
                height: Frame height in points (default: 200).
                output_filename: Bare output filename. Auto-generated if omitted.

            Returns:
                dict: {"status": "success"|"error", "message": str, "output_filename": str, "output_path": str}

            Raises:
                FileNotFoundError: If the input or image file does not exist in ASPOSE_FILES_PATH.

            Example:
                result = await slides_add_image_to_slide("deck.pptx", "photo.jpg", 0)
            """
            input_filename = Path(input_filename.strip().replace("\x00", "")).name
            resolved_input = get_safe_path(input_filename)
            if not Path(resolved_input).is_file():
                raise FileNotFoundError(
                    f"File not found: {input_filename!r}. "
                    f"Check ASPOSE_FILES_PATH ({platform_hint()})."
                )

            image_filename = Path(image_filename.strip().replace("\x00", "")).name
            resolved_image = get_safe_path(image_filename)
            if not Path(resolved_image).is_file():
                raise FileNotFoundError(
                    f"Image file not found: {image_filename!r}. "
                    f"Check ASPOSE_FILES_PATH ({platform_hint()})."
                )

            if output_filename is not None:
                output_filename = Path(output_filename.strip().replace("\x00", "")).name
            else:
                stem = Path(input_filename).stem
                output_filename = f"{stem}_with_image{Path(input_filename).suffix}"
            resolved_output = get_safe_path(output_filename)
            Path(resolved_output).parent.mkdir(parents=True, exist_ok=True)

            try:
                import aspose.slides as slides  # noqa: PLC0415

                pos_x = float(x if x is not None else 50)
                pos_y = float(y if y is not None else 50)
                pos_w = float(width if width is not None else 300)
                pos_h = float(height if height is not None else 200)

                with slides.Presentation(str(resolved_input)) as pres:
                    if slide_index < 0 or slide_index >= len(pres.slides):
                        raise IndexError(
                            f"slide_index {slide_index} out of range for "
                            f"{len(pres.slides)} slide(s)."
                        )
                    with open(str(resolved_image), "rb") as img_file:
                        img_data = img_file.read()
                    image = pres.images.add_image(img_data)
                    slide = pres.slides[slide_index]
                    slide.shapes.add_picture_frame(
                        slides.ShapeType.RECTANGLE, pos_x, pos_y, pos_w, pos_h, image
                    )
                    pres.save(str(resolved_output), slides.export.SaveFormat.PPTX)

                return {
                    "status": "success",
                    "message": f"Inserted {image_filename} onto slide {slide_index}.",
                    "output_filename": output_filename,
                    "output_path": str(resolved_output),
                }
            except (FileNotFoundError, IndexError):
                raise
            except Exception as exc:
                logger.exception("Failed to add image to slide")
                return {"status": "error", "message": str(exc), "output_filename": output_filename}

        @mcp.tool()
        async def slides_add_table_to_slide(
            input_filename: str,
            slide_index: int,
            rows: int,
            columns: int,
            x: float | None = None,
            y: float | None = None,
            output_filename: str | None = None,
        ) -> dict:
            """Insert a table onto a slide with the specified number of rows and columns.

            IMPORTANT: All *_filename parameters accept ONLY the bare filename.

            Args:
                input_filename: Bare filename of the source presentation.
                slide_index: 0-based index of the target slide.
                rows: Number of table rows.
                columns: Number of table columns.
                x: Left position in points (default: 50).
                y: Top position in points (default: 50).
                output_filename: Bare output filename. Auto-generated if omitted.

            Returns:
                dict: {"status": "success"|"error", "message": str, "output_filename": str, "output_path": str}

            Raises:
                FileNotFoundError: If the input file does not exist in ASPOSE_FILES_PATH.

            Example:
                result = await slides_add_table_to_slide("deck.pptx", 0, 3, 4)
            """
            input_filename = Path(input_filename.strip().replace("\x00", "")).name
            resolved_input = get_safe_path(input_filename)
            if not Path(resolved_input).is_file():
                raise FileNotFoundError(
                    f"File not found: {input_filename!r}. "
                    f"Check ASPOSE_FILES_PATH ({platform_hint()})."
                )

            if output_filename is not None:
                output_filename = Path(output_filename.strip().replace("\x00", "")).name
            else:
                stem = Path(input_filename).stem
                output_filename = f"{stem}_table{Path(input_filename).suffix}"
            resolved_output = get_safe_path(output_filename)
            Path(resolved_output).parent.mkdir(parents=True, exist_ok=True)

            try:
                import aspose.slides as slides  # noqa: PLC0415

                pos_x = float(x if x is not None else 50)
                pos_y = float(y if y is not None else 50)
                col_width = 120.0
                row_height = 40.0
                col_widths = [col_width] * max(1, columns)
                row_heights = [row_height] * max(1, rows)

                with slides.Presentation(str(resolved_input)) as pres:
                    if slide_index < 0 or slide_index >= len(pres.slides):
                        raise IndexError(
                            f"slide_index {slide_index} out of range for "
                            f"{len(pres.slides)} slide(s)."
                        )
                    slide = pres.slides[slide_index]
                    slide.shapes.add_table(pos_x, pos_y, col_widths, row_heights)
                    pres.save(str(resolved_output), slides.export.SaveFormat.PPTX)

                return {
                    "status": "success",
                    "message": f"Added {rows}×{columns} table to slide {slide_index}.",
                    "output_filename": output_filename,
                    "output_path": str(resolved_output),
                }
            except (FileNotFoundError, IndexError):
                raise
            except Exception as exc:
                logger.exception("Failed to add table to slide")
                return {"status": "error", "message": str(exc), "output_filename": output_filename}

        @mcp.tool()
        async def slides_add_chart_to_slide(
            input_filename: str,
            slide_index: int,
            chart_type: str | None = None,
            title: str | None = None,
            x: float | None = None,
            y: float | None = None,
            output_filename: str | None = None,
        ) -> dict:
            """Insert a chart onto a slide with an optional title.

            Supported chart_type values: CLUSTERED_COLUMN (default), PIE, LINE,
            BAR, AREA, SCATTER, DOUGHNUT, BUBBLE, RADAR.

            IMPORTANT: All *_filename parameters accept ONLY the bare filename.

            Args:
                input_filename: Bare filename of the source presentation.
                slide_index: 0-based index of the target slide.
                chart_type: Chart type string (default: 'CLUSTERED_COLUMN').
                title: Optional chart title text.
                x: Left position in points (default: 50).
                y: Top position in points (default: 50).
                output_filename: Bare output filename. Auto-generated if omitted.

            Returns:
                dict: {"status": "success"|"error", "message": str, "output_filename": str, "output_path": str}

            Raises:
                FileNotFoundError: If the input file does not exist in ASPOSE_FILES_PATH.

            Example:
                result = await slides_add_chart_to_slide("deck.pptx", 0, "PIE", "Sales by Region")
            """
            input_filename = Path(input_filename.strip().replace("\x00", "")).name
            resolved_input = get_safe_path(input_filename)
            if not Path(resolved_input).is_file():
                raise FileNotFoundError(
                    f"File not found: {input_filename!r}. "
                    f"Check ASPOSE_FILES_PATH ({platform_hint()})."
                )

            if output_filename is not None:
                output_filename = Path(output_filename.strip().replace("\x00", "")).name
            else:
                stem = Path(input_filename).stem
                output_filename = f"{stem}_chart{Path(input_filename).suffix}"
            resolved_output = get_safe_path(output_filename)
            Path(resolved_output).parent.mkdir(parents=True, exist_ok=True)

            try:
                import aspose.slides as slides  # noqa: PLC0415
                import aspose.slides.charts as charts  # noqa: PLC0415

                _chart_type_map: dict[str, object] = {
                    "CLUSTERED_COLUMN": charts.ChartType.CLUSTERED_COLUMN,
                    "PIE": charts.ChartType.PIE,
                    "LINE": charts.ChartType.LINE,
                    "BAR": charts.ChartType.CLUSTERED_BAR,
                    "AREA": charts.ChartType.AREA,
                    "SCATTER": charts.ChartType.SCATTER_WITH_MARKERS,
                    "DOUGHNUT": charts.ChartType.DOUGHNUT,
                    "BUBBLE": charts.ChartType.BUBBLE,
                    "RADAR": charts.ChartType.RADAR,
                }
                ct_key = (chart_type or "CLUSTERED_COLUMN").upper().strip()
                ct = _chart_type_map.get(ct_key, charts.ChartType.CLUSTERED_COLUMN)

                pos_x = float(x if x is not None else 50)
                pos_y = float(y if y is not None else 50)

                with slides.Presentation(str(resolved_input)) as pres:
                    if slide_index < 0 or slide_index >= len(pres.slides):
                        raise IndexError(
                            f"slide_index {slide_index} out of range for "
                            f"{len(pres.slides)} slide(s)."
                        )
                    slide = pres.slides[slide_index]
                    chart = slide.shapes.add_chart(ct, pos_x, pos_y, 500, 300)
                    if title:
                        chart.has_title = True
                        chart.chart_title.add_text_frame_for_overriding(title)
                    pres.save(str(resolved_output), slides.export.SaveFormat.PPTX)

                return {
                    "status": "success",
                    "message": f"Added {ct_key} chart to slide {slide_index}.",
                    "output_filename": output_filename,
                    "output_path": str(resolved_output),
                }
            except (FileNotFoundError, IndexError):
                raise
            except Exception as exc:
                logger.exception("Failed to add chart to slide")
                return {"status": "error", "message": str(exc), "output_filename": output_filename}

        @mcp.tool()
        async def slides_set_slide_transition(
            input_filename: str,
            slide_index: int,
            transition_type: str,
            output_filename: str | None = None,
        ) -> dict:
            """Set a transition effect on a slide.

            Supported transition_type values: NONE, FADE, PUSH, WIPE, ZOOM,
            CIRCLE, COMB, COVER, CUT, FLIP, FLY, GLITTER, RANDOM.
            Slide indexing is 0-based.

            IMPORTANT: All *_filename parameters accept ONLY the bare filename.

            Args:
                input_filename: Bare filename of the source presentation.
                slide_index: 0-based index of the target slide.
                transition_type: Transition name string (e.g. 'FADE', 'PUSH', 'WIPE').
                output_filename: Bare output filename. Auto-generated if omitted.

            Returns:
                dict: {"status": "success"|"error", "message": str, "output_filename": str, "output_path": str}

            Raises:
                FileNotFoundError: If the input file does not exist in ASPOSE_FILES_PATH.

            Example:
                result = await slides_set_slide_transition("deck.pptx", 0, "FADE")
            """
            input_filename = Path(input_filename.strip().replace("\x00", "")).name
            resolved_input = get_safe_path(input_filename)
            if not Path(resolved_input).is_file():
                raise FileNotFoundError(
                    f"File not found: {input_filename!r}. "
                    f"Check ASPOSE_FILES_PATH ({platform_hint()})."
                )

            if output_filename is not None:
                output_filename = Path(output_filename.strip().replace("\x00", "")).name
            else:
                stem = Path(input_filename).stem
                output_filename = f"{stem}_transition{Path(input_filename).suffix}"
            resolved_output = get_safe_path(output_filename)
            Path(resolved_output).parent.mkdir(parents=True, exist_ok=True)

            try:
                import aspose.slides as slides  # noqa: PLC0415
                import aspose.slides.slideshow as slideshow  # noqa: PLC0415

                _transition_map: dict[str, object] = {
                    "BLINDS": slideshow.TransitionType.BLINDS,
                    "CHECKER": slideshow.TransitionType.CHECKER,
                    "COMB": slideshow.TransitionType.COMB,
                    "DISSOLVE": slideshow.TransitionType.DISSOLVE,
                    "FADE": slideshow.TransitionType.DISSOLVE,
                    "SPLIT": slideshow.TransitionType.SPLIT,
                    "WINDOW": slideshow.TransitionType.WINDOW,
                }
                tt_key = transition_type.upper().strip()
                tt = _transition_map.get(tt_key, slideshow.TransitionType.DISSOLVE)

                with slides.Presentation(str(resolved_input)) as pres:
                    if slide_index < 0 or slide_index >= len(pres.slides):
                        raise IndexError(
                            f"slide_index {slide_index} out of range for "
                            f"{len(pres.slides)} slide(s)."
                        )
                    pres.slides[slide_index].slide_show_transition.type = tt
                    pres.save(str(resolved_output), slides.export.SaveFormat.PPTX)

                return {
                    "status": "success",
                    "message": f"Set {tt_key} transition on slide {slide_index}.",
                    "output_filename": output_filename,
                    "output_path": str(resolved_output),
                }
            except (FileNotFoundError, IndexError):
                raise
            except Exception as exc:
                logger.exception("Failed to set slide transition")
                return {"status": "error", "message": str(exc), "output_filename": output_filename}

        @mcp.tool()
        async def slides_merge_presentations(
            base_filename: str,
            merge_filename: str,
            output_filename: str | None = None,
        ) -> dict:
            """Merge a second presentation into a base by cloning all its slides.

            Iterates merge_filename's slides and calls pres1.slides.add_clone(slide).
            There is no single merge() method in the API.

            IMPORTANT: All *_filename parameters accept ONLY the bare filename.

            Args:
                base_filename: Bare filename of the base presentation.
                merge_filename: Bare filename of the presentation whose slides to merge in.
                output_filename: Bare output filename. Auto-generated if omitted.

            Returns:
                dict: {"status": "success"|"error", "message": str, "output_filename": str,
                       "output_path": str, "total_slides": int}

            Raises:
                FileNotFoundError: If either input file does not exist in ASPOSE_FILES_PATH.

            Example:
                result = await slides_merge_presentations("base.pptx", "extra.pptx", "merged.pptx")
            """
            base_filename = Path(base_filename.strip().replace("\x00", "")).name
            resolved_base = get_safe_path(base_filename)
            if not Path(resolved_base).is_file():
                raise FileNotFoundError(
                    f"Base file not found: {base_filename!r}. "
                    f"Check ASPOSE_FILES_PATH ({platform_hint()})."
                )

            merge_filename = Path(merge_filename.strip().replace("\x00", "")).name
            resolved_merge = get_safe_path(merge_filename)
            if not Path(resolved_merge).is_file():
                raise FileNotFoundError(
                    f"Merge file not found: {merge_filename!r}. "
                    f"Check ASPOSE_FILES_PATH ({platform_hint()})."
                )

            if output_filename is not None:
                output_filename = Path(output_filename.strip().replace("\x00", "")).name
            else:
                stem = Path(base_filename).stem
                output_filename = f"{stem}_merged{Path(base_filename).suffix}"
            resolved_output = get_safe_path(output_filename)
            Path(resolved_output).parent.mkdir(parents=True, exist_ok=True)

            try:
                import aspose.slides as slides  # noqa: PLC0415

                with slides.Presentation(str(resolved_base)) as pres1:
                    with slides.Presentation(str(resolved_merge)) as pres2:
                        for slide in pres2.slides:
                            pres1.slides.add_clone(slide)
                    total = len(pres1.slides)
                    pres1.save(str(resolved_output), slides.export.SaveFormat.PPTX)

                return {
                    "status": "success",
                    "message": f"Merged {merge_filename} into {base_filename}. Total slides: {total}.",
                    "output_filename": output_filename,
                    "output_path": str(resolved_output),
                    "total_slides": total,
                }
            except FileNotFoundError:
                raise
            except Exception as exc:
                logger.exception("Failed to merge presentations")
                return {"status": "error", "message": str(exc), "output_filename": output_filename}

        @mcp.tool()
        async def slides_protect_presentation(
            input_filename: str,
            password: str,
            output_filename: str | None = None,
        ) -> dict:
            """Set an open password on a presentation.

            IMPORTANT: All *_filename parameters accept ONLY the bare filename.

            Args:
                input_filename: Bare filename of the source presentation.
                password: Password to set for opening the presentation.
                output_filename: Bare output filename. Auto-generated if omitted.

            Returns:
                dict: {"status": "success"|"error", "message": str, "output_filename": str, "output_path": str}

            Raises:
                FileNotFoundError: If the input file does not exist in ASPOSE_FILES_PATH.

            Example:
                result = await slides_protect_presentation("deck.pptx", "secret", "deck_protected.pptx")
            """
            input_filename = Path(input_filename.strip().replace("\x00", "")).name
            resolved_input = get_safe_path(input_filename)
            if not Path(resolved_input).is_file():
                raise FileNotFoundError(
                    f"File not found: {input_filename!r}. "
                    f"Check ASPOSE_FILES_PATH ({platform_hint()})."
                )

            if output_filename is not None:
                output_filename = Path(output_filename.strip().replace("\x00", "")).name
            else:
                stem = Path(input_filename).stem
                output_filename = f"{stem}_protected{Path(input_filename).suffix}"
            resolved_output = get_safe_path(output_filename)
            Path(resolved_output).parent.mkdir(parents=True, exist_ok=True)

            try:
                import aspose.slides as slides  # noqa: PLC0415

                with slides.Presentation(str(resolved_input)) as pres:
                    pres.protection_manager.encrypt(password)
                    pres.save(str(resolved_output), slides.export.SaveFormat.PPTX)

                return {
                    "status": "success",
                    "message": f"Protected {input_filename} with password.",
                    "output_filename": output_filename,
                    "output_path": str(resolved_output),
                }
            except Exception as exc:
                logger.exception("Failed to protect presentation")
                return {"status": "error", "message": str(exc), "output_filename": output_filename}

        @mcp.tool()
        async def slides_unprotect_presentation(
            input_filename: str,
            password: str,
            output_filename: str | None = None,
        ) -> dict:
            """Remove the open password from a password-protected presentation.

            Uses aspose.slides.loading.LoadOptions to supply the current password,
            then calls pres.unprotect_presentation().

            IMPORTANT: All *_filename parameters accept ONLY the bare filename.

            Args:
                input_filename: Bare filename of the protected presentation.
                password: Current open password for the presentation.
                output_filename: Bare output filename. Auto-generated if omitted.

            Returns:
                dict: {"status": "success"|"error", "message": str, "output_filename": str, "output_path": str}

            Raises:
                FileNotFoundError: If the input file does not exist in ASPOSE_FILES_PATH.

            Example:
                result = await slides_unprotect_presentation("deck_protected.pptx", "secret")
            """
            input_filename = Path(input_filename.strip().replace("\x00", "")).name
            resolved_input = get_safe_path(input_filename)
            if not Path(resolved_input).is_file():
                raise FileNotFoundError(
                    f"File not found: {input_filename!r}. "
                    f"Check ASPOSE_FILES_PATH ({platform_hint()})."
                )

            if output_filename is not None:
                output_filename = Path(output_filename.strip().replace("\x00", "")).name
            else:
                stem = Path(input_filename).stem
                output_filename = f"{stem}_unprotected{Path(input_filename).suffix}"
            resolved_output = get_safe_path(output_filename)
            Path(resolved_output).parent.mkdir(parents=True, exist_ok=True)

            try:
                import aspose.slides as slides  # noqa: PLC0415

                opts = slides.LoadOptions()
                opts.password = password
                with slides.Presentation(str(resolved_input), opts) as pres:
                    pres.protection_manager.remove_encryption()
                    pres.save(str(resolved_output), slides.export.SaveFormat.PPTX)

                return {
                    "status": "success",
                    "message": f"Removed password protection from {input_filename}.",
                    "output_filename": output_filename,
                    "output_path": str(resolved_output),
                }
            except Exception as exc:
                logger.exception("Failed to unprotect presentation")
                return {"status": "error", "message": str(exc), "output_filename": output_filename}

        @mcp.tool()
        async def slides_find_and_replace_text(
            input_filename: str,
            find_text: str,
            replace_text: str,
            output_filename: str | None = None,
        ) -> dict:
            """Replace all occurrences of a text string across all slides.

            Iterates all slides, shapes, text frames, paragraphs, and portions.

            IMPORTANT: All *_filename parameters accept ONLY the bare filename.

            Args:
                input_filename: Bare filename of the source presentation.
                find_text: Text to search for.
                replace_text: Replacement text.
                output_filename: Bare output filename. Auto-generated if omitted.

            Returns:
                dict: {"status": "success"|"error", "message": str, "output_filename": str,
                       "output_path": str, "replacements": int}

            Raises:
                FileNotFoundError: If the input file does not exist in ASPOSE_FILES_PATH.

            Example:
                result = await slides_find_and_replace_text("deck.pptx", "{{NAME}}", "Shahzad")
            """
            input_filename = Path(input_filename.strip().replace("\x00", "")).name
            resolved_input = get_safe_path(input_filename)
            if not Path(resolved_input).is_file():
                raise FileNotFoundError(
                    f"File not found: {input_filename!r}. "
                    f"Check ASPOSE_FILES_PATH ({platform_hint()})."
                )

            if output_filename is not None:
                output_filename = Path(output_filename.strip().replace("\x00", "")).name
            else:
                stem = Path(input_filename).stem
                output_filename = f"{stem}_replaced{Path(input_filename).suffix}"
            resolved_output = get_safe_path(output_filename)
            Path(resolved_output).parent.mkdir(parents=True, exist_ok=True)

            try:
                import aspose.slides as slides  # noqa: PLC0415

                replacements = 0
                with slides.Presentation(str(resolved_input)) as pres:
                    for slide in pres.slides:
                        for shape in slide.shapes:
                            try:
                                tf = shape.text_frame
                            except AttributeError:
                                continue
                            for para in tf.paragraphs:
                                for portion in para.portions:
                                    if find_text in portion.text:
                                        count = portion.text.count(find_text)
                                        portion.text = portion.text.replace(find_text, replace_text)
                                        replacements += count
                    pres.save(str(resolved_output), slides.export.SaveFormat.PPTX)

                return {
                    "status": "success",
                    "message": f"Replaced {replacements} occurrence(s) of {find_text!r}.",
                    "output_filename": output_filename,
                    "output_path": str(resolved_output),
                    "replacements": replacements,
                }
            except FileNotFoundError:
                raise
            except Exception as exc:
                logger.exception("Failed to find and replace text")
                return {"status": "error", "message": str(exc), "output_filename": output_filename}

        @mcp.tool()
        async def slides_reorder_slide(
            input_filename: str,
            from_index: int,
            to_index: int,
            output_filename: str | None = None,
        ) -> dict:
            """Move a slide from one position to another (both indices are 0-based).

            Uses pres.slides.reorder(to_index, pres.slides[from_index]).
            Slide indexing is 0-based: from_index=0 is the first slide.

            IMPORTANT: All *_filename parameters accept ONLY the bare filename.

            Args:
                input_filename: Bare filename of the source presentation.
                from_index: 0-based current position of the slide to move.
                to_index: 0-based target position for the slide.
                output_filename: Bare output filename. Auto-generated if omitted.

            Returns:
                dict: {"status": "success"|"error", "message": str, "output_filename": str, "output_path": str}

            Raises:
                FileNotFoundError: If the input file does not exist in ASPOSE_FILES_PATH.

            Example:
                result = await slides_reorder_slide("deck.pptx", 2, 0, "deck_reordered.pptx")
            """
            input_filename = Path(input_filename.strip().replace("\x00", "")).name
            resolved_input = get_safe_path(input_filename)
            if not Path(resolved_input).is_file():
                raise FileNotFoundError(
                    f"File not found: {input_filename!r}. "
                    f"Check ASPOSE_FILES_PATH ({platform_hint()})."
                )

            if output_filename is not None:
                output_filename = Path(output_filename.strip().replace("\x00", "")).name
            else:
                stem = Path(input_filename).stem
                output_filename = f"{stem}_reordered{Path(input_filename).suffix}"
            resolved_output = get_safe_path(output_filename)
            Path(resolved_output).parent.mkdir(parents=True, exist_ok=True)

            try:
                import aspose.slides as slides  # noqa: PLC0415

                with slides.Presentation(str(resolved_input)) as pres:
                    slide_count = len(pres.slides)
                    if from_index < 0 or from_index >= slide_count:
                        raise IndexError(
                            f"from_index {from_index} out of range for "
                            f"{slide_count} slide(s)."
                        )
                    if to_index < 0 or to_index >= slide_count:
                        raise IndexError(
                            f"to_index {to_index} out of range for "
                            f"{slide_count} slide(s)."
                        )
                    pres.slides.reorder(to_index, pres.slides[from_index])
                    pres.save(str(resolved_output), slides.export.SaveFormat.PPTX)

                return {
                    "status": "success",
                    "message": f"Moved slide {from_index} → position {to_index}.",
                    "output_filename": output_filename,
                    "output_path": str(resolved_output),
                }
            except (FileNotFoundError, IndexError):
                raise
            except Exception as exc:
                logger.exception("Failed to reorder slide")
                return {"status": "error", "message": str(exc), "output_filename": output_filename}
